### ISSUE TITLE
Trendplot für ganz Deutschland im Mediumwidget fehlt

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#1]
gibt es eine Möglichkeit, beim breiten widget auch den Trend für ganz Deutschland anzuzeigen? Dieser ist ja bisher nur im schmalen Widget zu sehen

**Comment by rphl** [comment]
Habe es schon fürs nächste Update geplant. Hoffe das ich es am Wochenende fertig stellen kann.
So ungefähr soll es aussehen.

![widget_neu](https://user-images.githubusercontent.com/97642/97633057-be1a9700-1a33-11eb-80bc-afb1e89d9c3b.png)

**Comment by TheSpirit** [comment]
Sieht gut aus

**Comment by rphl** [comment]
Das Update ist online, gerne testen.

Ich bleibe aber erstmal bei den nach unten gerichteten Diagrammen, da mir es so besser gefällt.

Evtl. passe ich es später mal an, falls ich eine schönere Darstellungsform finde.
