### ISSUE TITLE
„Abgeschittener“ LK-Name.....

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#10]
![61FD3015-9DFC-45F4-AD95-F6341DA3650A](https://user-images.githubusercontent.com/8932465/97773673-11830700-1b52-11eb-8422-d3ab7e8fd169.jpeg)

....könntest Du bitte nochmal nmach dem LK-Namen schauen...wenn er so lange ist wie bei mir.......

Grüße und vielen Dank!!!!!

**Comment by STJIKA** [comment]
...sorry ...vergessen...iPad Pro 12.9 , iOS 14.1 ......

**Comment by pille85** [comment]
Verwende doch mal diese Parameter unter "Widget bearbeiten": 
0, 49.42, 11.31, LKR Nürnberg

**Comment by STJIKA** [comment]
![FA8156D7-2693-45A9-A17B-94B3351F3566](https://user-images.githubusercontent.com/8932465/97774570-39299d80-1b59-11eb-9b2c-b32fc5b5c6d8.jpeg)
...ja , okay....hab ich mir auch gedacht.......habe es jetzt so gelöst....VIELEN DANK!!!!

**Comment by pille85** [comment]
👍

**Comment by STJIKA** [comment]
![E8996489-48AD-4C7D-955C-00C4C0F5E3A1](https://user-images.githubusercontent.com/8932465/97774732-8eb27a00-1b5a-11eb-96b0-855271436673.jpeg)
...hier ist noch ein Problem bei der Inzidenzzahl und dem Pfeil nach rechts.......

**Comment by exneralex3009** [comment]
Inzidenz abgeschnitten, kann ich die Schrift verkleiner nur wo? Kann jemand helfen?

**Comment by tomacco81** [comment]
> ...hier ist noch ein Problem bei der Inzidenzzahl und dem Pfeil nach rechts.......

Das Problem hatte ich auch. Hab dann mit dem Wert in Zeile 221 rumgespielt (`stackMainRow.addSpacer(5)`)... 
Wenn ich den Wert von 5 auf 4 ändere, passt es bei mir wieder.

**Comment by rphl** [comment]
Habe mal ein Update gepusted. Jetzt sollten auch Zahlen bis 99,9 voll dargestellt werden.

Danke auch an @tomacco81 der Änderungen via PullRequest beigesteuert hat
