### ISSUE TITLE
Graph für Cases wird nicht übernommen bei Autoupdate

### ISSUE THREAD

**Issue by apfelbasti** [rphl/corona-widget#101]
Wenn graphShowValue den Wert 'c' hat und scriptSelfUpdate auf true eingestellt ist, wird der Wert von graphShowValue wieder auf 'i' gesetzt.

**Comment by apfelbasti** [comment]
Betrifft sämtliche Variablen, die geändert wurden (z.B. auch die angezeigten Tage im Graphen).

**Comment by rphl** [comment]
Oh ja stimmt, müsste mir mal eine Lösung überlegen. Bis dahin müsstest du erstmal `scriptSelfUpdate` abstellen.

**Comment by rphl** [comment]
Ein Update in Develop ist online. Siehe zur Konfiguration auch die README.

**Comment by apfelbasti** [comment]
Ist die config.json selbst anzulegen?

**Comment by apfelbasti** [comment]
Ready for Merge 👍🏻

**Comment by rphl** [comment]
Ja die muss man aktuell selbst anlegen. Habe deswegen in der README noch eine App erwähnt mit der man das machen kann.

Das es nicht in Scriptable auftaucht werde ich noch erwähnen.

**Comment by rphl** [comment]
Änderungen sind jetzt im master.

**Comment by apfelbasti** [comment]
Werden die Änderungen aus dem master bei Autoupdate übernommen?

**Comment by rphl** [comment]
Ja sollten. AutoUpdate bezieht sich immer auf den Master. 
Deine angelegte `config.json` wird also auch weiterverwendet.

**Comment by apfelbasti** [comment]
Ok. Ich frag nur, weil ich die neuesten Änderungen manuell übernehmen musste. Auch die Impfungen in #108 wurden nicht mit übernommen.
