### ISSUE TITLE
Tendenz Pfeil Falsch

### ISSUE THREAD

**Issue by Stefan-1982** [rphl/corona-widget#102]
Leider ist trotz gestiegener Zahl im Vergleich zum Vortag der Tendenz Pfeil falsch... er müsste nach oben gehen und nicht nach unten...

![746E2B19-0E33-42AD-9338-F74E857F7F98](https://user-images.githubusercontent.com/76473844/102873752-d4484080-4441-11eb-8018-47f8168e4e6d.jpeg)

![07CC8131-BBA2-422F-9E85-9EDD44A9E728](https://user-images.githubusercontent.com/76473844/102873783-dca07b80-4441-11eb-92dd-2951b886fa1c.jpeg)

**Comment by rphl** [comment]
Hallo. Das könnte durchaus passen, ist ja ein **Wochentrend**.  Man grob aus dem Diagram erahnen, dass die Zahlen in der Aktuellen Woche niedriger sind.

**Comment by rphl** [comment]
Aktuelle = 175.46651537061763
Vorwoche = 182.66230306720453

↓ Passt also.

**Comment by Stefan-1982** [comment]
Dann sollte es mal in der Beschreibung korrigiert werden dort steht nämlich eindeutig ↓ niedriger als Gestern

**Comment by rphl** [comment]
Danke für den Hinweis. Hatte es nur im Text der README angepasst.
