### ISSUE TITLE
Inzidenz Werte sind nicht korrekt

### ISSUE THREAD

**Issue by mIgU0815** [rphl/corona-widget#105]
Hallo,
deine Widget ist echt Super! Leider stimmen die Werte bei mir nicht überein...
ich habe noch eine "alte" Version eines coronaWidget das auch von der RKI api ihre Daten holt.
Leider Weichen die Zahlen ab. Ein Vergleich der Zahlen deines Widget mit dem RKI Dashboard decken sich leider nicht.
Ebenso der Trend der über die iCloud ermittelt wird ist nicht korrekt.
Was läuft bei mir falsch? Ich habe 5 deiner Widgets am laufen unterschiedlichste Standorte.
Parameter beginnt immer mit 0, dann GEO Position zB 47.904, 10.636 fertig.
Für das Beispiel des LK OAL bekomme ich mit Stand von Heute (23.12.2020 07:53) 197 Trend steigend.
Die RKI Zahl 148 Trend fallend. nur für den Standort 0, 48.13, 11.56 (München) und Landsberg am Lech passen die Werte mit 237 bzw 154 nur der Trend ist bei dir nicht korrekt.
Es würde mich sehr freuen wenn ich einen Tipp bekommen könnte was hier nicht richtig läuft.
![IMG_5604CBBBCD9F-1](https://user-images.githubusercontent.com/73383563/102973821-bd672400-44fd-11eb-8717-e5460b974bf1.jpeg)

**Comment by Stefan-1982** [comment]
Ich habe ebenfalls den Verdacht das der Trend Pfeil nicht stimmen kann... der Landkreis Rhön-Grabfeld hatte die ganze Zeit niedrige Zahlen um die 138 heute sind die Zahlen drastisch gestiegen auf 192 und der Pfeil zeigt nach unten.. 🙈

**Comment by DannyBoyKN** [comment]
Dito hier, siehe small widget links und medium rechts 

<img src="https://user-images.githubusercontent.com/22725819/103037984-7d3f8a00-456d-11eb-9a10-94a22d5d455c.png" width="128"><img src="https://user-images.githubusercontent.com/22725819/103038017-947e7780-456d-11eb-9baf-1faa84ab387d.png" width="256">

22.12.2020 = 146
23.12.2020 = 137

Oder wie ist der Trend-Pfeil zu verstehen ?

**Comment by ja-m** [comment]
Ich habe im Script folgende Zeile geändert und damit die Live-Daten deaktiviert:

`disableLiveIncidence: true`

Damit passen die Werte zu dem alten Script wieder.

**Comment by rphl** [comment]
Hallo. Bzgl der Pfeile. Siehe readme, diese zeigen den Wochentrend. Aktuelle vs. Vorwoche. 
Dies macht den Trend deutlich robuster.

**Comment by rphl** [comment]
Es ist also kein Trend heute vs. gestern. Der evtl. ein ↓↑↓↑↓↓↑ je Tag anzeigen würde.

**Comment by rphl** [comment]
@mIgU0815 @ja-m Das RKI dashboard zeigt immer nur den "statischen" Inzidenzwert an. Sollten sich die Fälle (je Meldedatum) über den Tag geändert haben (was die es oft tuen, siehe neue Fälle), so ist der "statische" Inzidenzwert  nicht mehr aktuell. Und wird auch nicht mehr in der API aktualsiert.

Ihr könnt euch die berechneten Inzidenzen via `CFG.debugIncidenceCalc` anzeigen lassen. Diese basieren immer auf dem Meldedatum (inkl. Aktualisierungen) der neuen Fälle

**Comment by rphl** [comment]
Siehe meine vorhergehenden Kommentare. Bei Problem gerne wieder öffnen.
