### ISSUE TITLE
Error on line 828

### ISSUE THREAD

**Issue by Larosen** [rphl/corona-widget#106]
Bei mir meldest Scriptable mit der aktuellen Version folgenden Fehler:
![image](https://user-images.githubusercontent.com/66299704/103050849-a6741080-4595-11eb-9e50-b4c454f1086a.jpeg)

Dass jetzt plötzlich ein Error aufgetreten ist, wundert mich, da das Widget, so wie es jetzt ist, gestern noch lief.

**Comment by rphl** [comment]
Wahrscheinlich ein Problem mit der API? Denke müsste sich aber von selbst gelöst haben. 
Falls nein, gerne nochmal aufmachen.
