### ISSUE TITLE
Daten für Main-Kinzig-Kreis falsch

### ISSUE THREAD

**Issue by UweLoyal** [rphl/corona-widget#107]
Hallo,

woran kann es liegen, dass die Daten für MKK nicht stimmen. Version aus Autoupdate und auch aktuelle Version aus Internet weisen Fehler auf.

![FCE280EC-BEAD-4D2F-8F56-E070DE43DCCF](https://user-images.githubusercontent.com/5464553/103284110-a41d1680-49da-11eb-875b-02714ce436e5.jpeg)

![4655A90A-C26D-44F0-9AC1-8D6A380A47A0](https://user-images.githubusercontent.com/5464553/103284178-d169c480-49da-11eb-9925-36d9efb74a7f.png)

LG
Uwe Loyal

**Comment by Stefan-1982** [comment]
Landkreis Bad Kissingen passt auch nicht... 

![AEDBC6E1-71A5-478C-9B6A-A2890EA19395](https://user-images.githubusercontent.com/76473844/103284604-f4e13f00-49db-11eb-920f-6fea84680528.jpeg)
![Uploading 1E801142-8D6F-4E11-9648-B4DFCE4E4264.png…]()

**Comment by rphl** [comment]
Ich denke ihr nutzt die Live-Inzidenz? Diese ändert sich ja je nachdem ob neue Fälle für die letzen 7tage, sich über den Tag ändern. Und entspricht dem aktuellen Wert.

Wenn ihr den "alten" / statischen Indizenzwert anzeigen lassen wollt. Einfach `CFG.disableLiveIncidence` auf `true` stellen. Damit gibt es keine Updates und ihr seht den alten, statischen, Wert immer.

**HINWEIS:** Wenn Ihr eine Option umstellen wollt, und AutoUpdate eingeschaltet habt, so muss das AutoUpdate leider abgeschaltet werden. Sonst wird die Option beim nächsten update überschrieben. (Siehe auch #101)

**Comment by rphl** [comment]
Siehe mein Kommentar zuvor. Mache erstmal hier zu, wenn noch etwas nicht passt gerne öffnen.
