### ISSUE TITLE
Impfzahlen ins Widget einbauen?

### ISSUE THREAD

**Issue by FIetch** [rphl/corona-widget#108]
Hi,
finde dein Widget sehr gut und heute habe ich entdeckt, dass jetzt auch die Anzahl der Impfungen an das RKI gemeldet werden. Wäre nice wenn du das mit ins Widget übernehmen könntest.

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html

**Comment by nicoh88** [comment]
+1

**Comment by princemaxwell** [comment]
+1
@Fletch Den Link kannst Du mittlerweile leider vergessen, weil dort nur noch ne XLSX Datei zum Download angeboten wird.
Die muss man erst aufwendig parsen, alles zu kompliziert.

Die Lösung:
https://rki-vaccination-data.vercel.app/api

https://gist.github.com/marco79cgn/b5f291d6242a2c530e56c748f1ae7f2c

**Comment by rphl** [comment]
Finde die Idee generell nicht schlecht. Aber da das Widget bereits schon sehr voll ist, würde ich eher ein eigenes Widget sehen. Alternativ im Mediumwidget auf den zweiten Standort verzichten ( Switch? )

Zudem habe ich schon im allgemeinen Ticket auf die Problematik mit der XLS hingewiesen. Eine CSV wie bei dem RWert wäre ein minimum.

@princemaxwell Danke für den Hinweis mit der API. Hier müsste auch geklärt werden ob ich die überhaupt in meinen Widget verwenden werden darf. Ist ja eine private. 
Und wenn die sich unerwartet ändert bzw. nicht mehr zu verfügung steht, muss auch noch eingeplant werden. Ist meist bei den "offiziellen" selten der Fall.

**Comment by 1rNidiD** [comment]
https://gist.github.com/marco79cgn/b5f291d6242a2c530e56c748f1ae7f2c

Hier gibts ein Widget, nur für die Impfzahlen. Vielleicht reicht das ja vorerst oder eventuell kann dieses Widget in ein Medium Widget mit eingebunden werden :)

**Comment by rphl** [comment]
Habe mal ein update mit den Impfquoten/-zahlen online gestellt. Basiert erstmal auf der vorgeschlagenen API von Benny. Aktuell nur im Develop. Gerne testen:
https://github.com/rphl/corona-widget/tree/develop

Zur Aktivierung muss `CFG.showVaccineInMedium` auf true gestellt werden.
**HINWEIS:** AutoUpdate abstellen! `CFG.scriptSelfUpdate` auf false

![image](https://user-images.githubusercontent.com/97642/103467118-09ab3300-4d4c-11eb-8e1a-e988c8e49bba.png)

**Comment by RosoV89** [comment]
Mir gefällt die Variante ganz rechts sehr gut. 

Wenn du noch Tausender Trennzeichen rein machst. :) ich hoffe ja mal, dass die Zahl der Impfungen bald 7 oder 8stellig sind. Dann wird’s Übersichtlicher.

**Comment by apfelbasti** [comment]
Gefällt mir sehr gut! Ich werde nachher mal den develop auschecken und mir das ganze auf meinem iPhone anschauen :-) Danke für die schnelle Umsetzung!

**Comment by Stefan-1982** [comment]
Naja fast etwas überladen, finde die impf Quote als separates Widged besser

**Comment by FIetch** [comment]
Bei mir funktioniert das Widget nicht mit impfzahlen. Wenn ich das Script im Scriptable einfüge, kann ich die Vorschau anzeigen und da werden die impfzahlen angezeigt, jedoch auch mit Standort Köln. Und wenn wenn ich das Widget auf den homescreen erstelle, bleibt oben Köln, und darunter steht mein Kreis.

**Comment by DannyBoyKN** [comment]
Kann @Stefan-1982 nur zustimmen: zu überladen.
Als separates Widget sinnvoller und [bereits vorhanden](https://gist.github.com/marco79cgn/b5f291d6242a2c530e56c748f1ae7f2c)...
![image](https://user-images.githubusercontent.com/22725819/103476703-604e5680-4db8-11eb-8b41-5951421a03f6.png)

**Comment by STJIKA** [comment]
zuerst nochmal dank für die tolle Arbeit und Unterstützung an rhpl..... und alle Beteiligten........

....Ich finde es besser wenn die Impfzahlen im Widget integriert sind...noch ein extra Widget wäre mir zuviel...

...am besten wäre es, denke ich, wenn man die Impfzahlen optional anzeigen oder ausblenden könnte....ich kann aber nicht beurteilen ob es machbar bzw. mit vertretbarem Aufwand machbar ist.... aber das wäre für mich und vielleicht für den ein oder anderen meiner meinung nach die beste Wahl.....

**Comment by firebowl** [comment]
Ich befürchte auch, dass das Widget mit Impfzahlen überladen wird. Gibt auch schon mindestens zwei eigenständige Widgets dafür. Eines auf ScriptDude. 

![image](https://user-images.githubusercontent.com/73579226/103476930-10708f00-4dba-11eb-9313-6ff522082bd2.jpeg)
![image](https://user-images.githubusercontent.com/73579226/103476931-15354300-4dba-11eb-8726-438205d82e52.jpeg)
![image](https://user-images.githubusercontent.com/73579226/103476934-1b2b2400-4dba-11eb-9d97-e89a405faa3e.jpeg)

**Comment by STJIKA** [comment]
> Ich befürchte auch, dass das Widget mit Impfzahlen überladen wird. Gibt auch schon mindestens zwei eigenständige Widgets dafür. Eines auf ScriptDude.
> 
> ![image](https://user-images.githubusercontent.com/73579226/103476930-10708f00-4dba-11eb-9313-6ff522082bd2.jpeg)
> ![image](https://user-images.githubusercontent.com/73579226/103476931-15354300-4dba-11eb-8726-438205d82e52.jpeg)
> ![image](https://user-images.githubusercontent.com/73579226/103476934-1b2b2400-4dba-11eb-9d97-e89a405faa3e.jpeg)

...das stimmt ...aber es ist nicht vergleichbar mit rphl‘s Arbeit......und ist meiner Meinung nach eher eine Beleidung fürs Auge....................

**Comment by firebowl** [comment]
> > Ich befürchte auch, dass das Widget mit Impfzahlen überladen wird. Gibt auch schon mindestens zwei eigenständige Widgets dafür. Eines auf ScriptDude.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/73579226/103476930-10708f00-4dba-11eb-9313-6ff522082bd2.jpeg)
> 
> > ![image](https://user-images.githubusercontent.com/73579226/103476931-15354300-4dba-11eb-8726-438205d82e52.jpeg)
> 
> > ![image](https://user-images.githubusercontent.com/73579226/103476934-1b2b2400-4dba-11eb-9d97-e89a405faa3e.jpeg)
> 
> 
> 
> ...das stimmt ...aber es ist nicht vergleichbar mit rphl‘s Arbeit......und ist meiner Meinung nach eher eine Beleidung fürs Auge....................

Da hast Du leider absolut recht. 😂

**Comment by apfelbasti** [comment]
Ich habe sowohl kleine als auch Medium-Widgets bei mir. Die kleinen funktionieren nun leider nicht mehr, da ich die Option showVaccineInMedium auf true gesetzt habe. Es wäre besser, wenn dies bei den kleinen Widgets nicht berücksichtigt wird.
![4670D6E4-6A7C-4CCA-964E-6F88AC598741_4_5005_c](https://user-images.githubusercontent.com/6957954/103477026-eec3d780-4dba-11eb-9f2b-08bc41f6c7a5.jpeg)

**Comment by FIetch** [comment]
![image](https://user-images.githubusercontent.com/59744922/103478459-2769ae00-4dc7-11eb-9847-e973c544062a.jpeg)

Wie bekomme denn Köln weg Grund stattdessen die impfzahlen?

**Comment by rphl** [comment]
> Ich habe sowohl kleine als auch Medium-Widgets bei mir. Die kleinen funktionieren nun leider nicht mehr, da ich die Option showVaccineInMedium auf true gesetzt habe. Es wäre besser, wenn dies bei den kleinen Widgets nicht berücksichtigt wird.

@apfelbasti Das Stimmt, habe selbst nur eins aktiv. Bedenke aber das das setzten (aktivieren) der Impquoten global ist. Gilt also für jedes aktive Widget. Eine Widgetspezifische Konfiguration, über die Parameter, müsste ich noch einbauen. Werde den Check erstmal mal prüfen, bzw entfernen.

**Comment by rphl** [comment]
> Wie bekomme denn Köln weg Grund stattdessen die impfzahlen?

@FIetch 
1. in der `incidence.js` die Option `showVaccineInMedium`auf true setzten.
2. Nur einen Standort nutzen: (Bild3)
   * Widgetparameter entfernen oder nur ersten ( 0 ) Standort setzten
2. **ODER** Zwei Standorte nutzen: (Bild1, Bild2)
   * Es werden nur die Impfquoten angezeigt.

**Comment by rphl** [comment]
> Ich befürchte auch, dass das Widget mit Impfzahlen überladen wird. Gibt auch schon mindestens zwei eigenständige Widgets dafür. Eines auf ScriptDude.

Habe mich erstmal gegen ein eigenständiges Entschieden:
1. Es gibt schon einige (s.o, wer mag kann die gerne nutzen)
2. Habe selbst keine Lust 20 Widgets für ein Thema auf den HomeScreen zu haben.

Deswegen sind die Informationen nur im MediumWidget verfügbar. Und es wird nur das nötigste angezeigt.

**Comment by FIetch** [comment]
@rphl 
Jetzt gehts 👍🏽

**Comment by rphl** [comment]
@apfelbasti Habe mal ein Update wegen dem Small Widget online gestellt. Gerne testen.

**Comment by apfelbasti** [comment]
> @apfelbasti Habe mal ein Update wegen dem Small Widget online gestellt. Gerne testen.

Sieht gut aus 👍🏻

**Comment by rphl** [comment]
Änderungen sind jetzt im master.

**Comment by RosoV89** [comment]
Hey, wo genau kann ich denn jetzt die Impfzahlen anzeigen lassen? Ich habe die neue Script Version gespeichert aber ich sehe keinen Unterschied 🙈

**Comment by apfelbasti** [comment]
Der master sieht gerade auch noch etwas unverändert aus. Der Parameter für die Impfungen ist zumindest nicht mit enthalten.

**Comment by rphl** [comment]
Master sollte aktuell fein aussehen, da ist wohl etwas durcheinander geraten. Zur Konfiguration siehe README bzw. meine Kommantare oben.

**Comment by RosoV89** [comment]
Hey, kannst du mir das mit der Konfiguration genauer erklären? Ich weiß nicht genau was ich machen muss damit mir die impfqoute angezeigt wird 🙈

**Comment by firebowl** [comment]
Du musst nur eine Datei mit Namen config.json im Ordner (iCloud Drive und dann Ordner Scriptable) coronaWidgetNext erstellen und als Inhalt 
`{
    "showVaccineInMedium": true
} `
einfügen.

**Comment by rphl** [comment]
Wie firebowl es erklärt hat, ist schon richtig. Falls du kein AutoUpdate eingeschaltet hast, kannst du es auch direkt in der `incidence.js` setzten.

Siehe auch : https://github.com/rphl/corona-widget#erweiterte-konfiguration (Incl Beispiele)

**Comment by dennerforen** [comment]
Noch mal danke für das tolle Widget

**Comment by RosoV89** [comment]
Wäre jemand so hilfreich und würde die Datei für mich anlegen? Sodass ich nur noch Copy/Paste machen muss? Bin da echt ein totaler Noob.. :(

**Comment by Thronis** [comment]
{
    "showVaccineInMedium": true
}

Mehr muss in die Datei nicht rein

**Comment by RosoV89** [comment]
Wie lege ich die Datei an?

**Comment by rphl** [comment]
@RosoV89 Siehe README ;-) Da steht es auch nochmal.

Du kannst z.B die Kodex App https://apps.apple.com/de/app/kodex/id1038574481 für iPhone/iPad verwendet werden.
dafür verwenden.

**Comment by RosoV89** [comment]
Ich glaube es hat geklappt 🤪

nur zum Verständnis: wenn ich die impfquote anzeigen lasse, kann ich dann parallel nicht die infektionszahlen zweier Standorte ansehen oder? Also entweder so oder so?

**Comment by rphl** [comment]
Wenn du auch die Impfzahlen für einen weiteren (zweiten) Standort sehen möchtest, geht es nur über ein zweites Widget. 

Bei zwei Standorten werden auf Grund des Platzes nur die Quoten angezeigt. Sind meiner Meinung schon sehr aussagekräftig. (sonst s.o)

**Comment by RosoV89** [comment]
Alles klar. Ne passt erstmal so. Top danke :) 

habe mich vorhin etwas schwer getan, das zu verstehen aber jetzt funzt alles

**Comment by rphl** [comment]
@RosoV89 Super. Falls man hier die README verständlicher schreiben könnte, gerne Änderungen vorschlagen.

**Comment by RosoV89** [comment]
Besser nicht. Sonst habt ihr mit noch mehr Noobs zu kämpfen 😂😂

eigentlich ist es schon gut geschrieben, man muss es halt nur verstehen

**Comment by firebowl** [comment]
Bei mir verschwinden die Impfzahlen immer wieder mal und tauchen dann irgendwann wieder auf. Als ob die nicht gecashed werden und nicht schnell genug aktualisiert werden, wenn sich das Widget aktualisiert.

**Comment by rphl** [comment]
@firebowl Hast du WidgetParameter gesetzt?

**Comment by firebowl** [comment]
> @firebowl Hast du WidgetParameter gesetzt?

Nö, absolut blankes Medium Widget und in der config.json aktivier ich nur den Impfstatus.

**Comment by icsAT** [comment]
Wird noch die API von Benny verwendet? Irgedwie weichen die Impfquoten für Niedersachsen ab.
![image](https://user-images.githubusercontent.com/74063738/103713860-9c063d80-4fbd-11eb-96f7-01fa935b06dd.jpeg)
![image](https://user-images.githubusercontent.com/74063738/103713888-ad4f4a00-4fbd-11eb-9f56-0d083fcdb77c.jpeg)

**Comment by rphl** [comment]
Die API zeigt den richtigen wert an, 0,11%. Ich prüfe man das Widget.

**Comment by rphl** [comment]
@icsAT Es gab bei Niedersachsen ein typo. Sollte jetzt gefixed sein.

**Comment by icsAT** [comment]
@rphl Perfekt. Funktioniert.
