### ISSUE TITLE
Aktuelle Version zeigt falschen Inzidenzwert an

### ISSUE THREAD

**Issue by cheinelt** [rphl/corona-widget#109]
Ich verwende die aktuelle Version aus dem Git Repo. Es zeigt für meinen Landkreis Ebersberg seit 2 Tagen nicht den aktuellen Inzidenzwert an.

**Comment by rphl** [comment]
Ich vermute du nutzt die LiveInzidenz? Daten kommen alle aus der API und sollten aktuell sein. Außer dein Landkreis/Stadt hat seit paar Tagen nichts gemeldet. 

Siehe auch Hinweise zur Quelle/Daten in der README.

Bitte auch die WidgetParameter oder groben Standort posten. Dann kann ich es prüfen.

**Comment by cheinelt** [comment]
Ich nutze die Defaulteinstellungen des JS Scripts. Auf der Übersichtsseite vom RKI sehe ich allerdings einen anderen Wert: Widget zeigt 196 and und RKI zeigt 141.

**Comment by rphl** [comment]
Der Inzidenzwert vom RKI ist "statisch" und ändert sich nicht mehr, auch nicht bei aktualisierungen der Fälle.
D.h Falls aber neue Fälle nachgemeldet (für die letzten Tage) werden, so ändert sich zwangsläufig die Inzidenz. Deswegen ist die LiveInzidenz die aktuelle. 

Falls du den alten / statischen Wert anzeigen möchtest, kannst du im Skript `disableLiveIncidence ` auf `true` stellen
