### ISSUE TITLE
Eigene Hintergrundfarbe

### ISSUE THREAD

**Issue by thatisjt** [rphl/corona-widget#111]
Hallo,
ich benutze dieses Widget sehr gerne und es funktioniert super. Klasse Arbeit !
Ich würde gerne die Hintergrundfarbe schwarz ändern. Ist das möglich ?

Viele Grüße!

**Comment by rphl** [comment]
Noch nicht, es wurde aber die Tage mal hier bereits erwähnt: https://github.com/rphl/corona-widget/issues/6#issuecomment-754039316

**Comment by thatisjt** [comment]
> Noch nicht, es wurde aber die Tage mal hier bereits erwähnt: [#6 (comment)](https://github.com/rphl/corona-widget/issues/6#issuecomment-754039316)


Danke, habe dies nun ausprobiert. Es erscheint immer dieser Fehler. 
Wie muss die Ordnerstruktur in der config.json sein, wenn ich das Bild in den Scriptable-Ordner gelegt habe ?
![15F185E3-72E2-4535-A3AE-BA13A7E61CF0](https://user-images.githubusercontent.com/73525954/103662583-6b4be700-4f70-11eb-9dae-9589f20a98cb.jpeg)

**Comment by ottiman** [comment]
Wenn das Hintergrundbild einfach nur im Scriptable-Ordner liegt muss in der config.json nur der Dateiname stehen, ohne Unterordner. Aber der Fehler sieht eher danach aus, dass du die Bild-Datei im Code der js-Datei zu früh anfragst.

Entweder du fügst den innerhalb von `class IncidenceWidget` -> `async init()`
am besten direkt nach `this.widget.setPadding(0, 0, 0, 0)` (müsste Zeile 130 sein) ein oder wartest bis rphl das Widget entsprechend überarbeitet hat. Denk dran dass nach jedem Update der geänderte Code wieder rausfliegt.

**Comment by thatisjt** [comment]
> Wenn das Hintergrundbild einfach nur im Scriptable-Ordner liegt muss in der config.json nur der Dateiname stehen, ohne Unterordner. Aber der Fehler sieht eher danach aus, dass du die Bild-Datei im Code der js-Datei zu früh anfragst.
> 
> Entweder du fügst den innerhalb von `class IncidenceWidget` -> `async init()`
> am besten direkt nach `this.widget.setPadding(0, 0, 0, 0)` (müsste Zeile 130 sein) ein oder wartest bis rphl das Widget entsprechend überarbeitet hat. Denk dran dass nach jedem Update der geänderte Code wieder rausfliegt.

Danke für Ihre Hilfe. Das hat schon besser funktioniert. Ich erhalte keine Fehlermeldung mehr. Jedoch bleibt der Hintergrund schwarz. 
Ich denke ich habe im Skript einen Fehler. Vielleicht findet ja jemand den Fehler !

  
![IMG_4583](https://user-images.githubusercontent.com/73525954/103766518-3f3b6f00-501f-11eb-9e02-357f0cf49970.jpeg)
![IMG_4584](https://user-images.githubusercontent.com/73525954/103766521-41053280-501f-11eb-88b5-d5887336e995.jpeg)
![IMG_4585](https://user-images.githubusercontent.com/73525954/103766527-43678c80-501f-11eb-9bdd-63db8bac6201.jpeg)

**Comment by ottiman** [comment]
Es fehlt der erste / vor dem Dateinamen.
Mit `"bgImage": "/coronabg.jpg"` müsste es funktionieren.

**Comment by thatisjt** [comment]
Super danke! Es hat funktioniert !
Ich würde gerne noch die Farben der weissen und grauen Schrift ändern. Wenn möglich auch die Kästen im Hintergrund. Ist es möglich das im Code zu ändern ?

![IMG_4586](https://user-images.githubusercontent.com/73525954/103769797-3ea5d700-5025-11eb-9dd3-81bb94e8db79.jpeg)

**Comment by ottiman** [comment]
Klar, im Code kannst du für deine Zwecke theoretisch alles ändern. Die Frage ist, ob du dir die Arbeit wirklich machen willst. Denn die Farbwerte sind alle quer im Code verteilt und wenn ein größeres Update des Widgets kommt und du updaten möchtest, wäre deine ganze Mühe umsonst.

Falls du noch interessiert bist, such für weiße Schriften nach Zeilen mit `#fff`, für graue Schriften `#777` und ich glaube auch `#888` und `#999`, die grauen Kästen haben `#99999915`, `#99999920` und `#99999930` (wobei die letzten beiden Ziffern bei den Kästen für die Transparenz steht). Alles zu finden innerhalb von `class IncidenceWidget` -> `async createWidget()`
Viel Erfolg ;)

@rphl : Theoretisch könntest du die Möglichkeit einbauen, über die `config.json` Farbwerte und Transparenzen festzulegen. Damit könnte jeder das Widget an seine Bedürfnisse anpassen.

**Comment by thatisjt** [comment]
DANKE !!!
Habe mein Widget jetzt angepasst.
![Uploading IMG_4598.png…]()

**Comment by thatisjt** [comment]
DANKE !!
Habe mein Widget jetzt angepasst !

![3764CD2A-D055-4B3D-87DF-2B26AD9B18E5](https://user-images.githubusercontent.com/73525954/103920063-1f847380-5111-11eb-8c3c-bea1de04d9e5.png)

**Comment by iam28** [comment]
@thatisjt Was genau hast du im Code geändert für den transparenten Background?
