### ISSUE TITLE
DNA-Strang durch Spritze ersetzen / Whitespace beim mittleren Widget

### ISSUE THREAD

**Issue by thomaskeim** [rphl/corona-widget#112]
Hallo,
Was hältst Du davon, bei den Impfungen das Icon DNA-Strang 🧬 durch die Spritze 💉 zu ersetzen?
Passt meiner Meinung nach etwas besser.

Vielleicht fällt Dir auch noch eine schlaue Idee ein, gerade beim mittleren Widget, den oberen Whitespace zu reduzieren, um die restlichen Elemente nicht ganz so gedrückt darzustellen.

Ich könnte mir vorstellen:
Icon und R-Faktor links, Icon gleiche Größe wie R-Faktor
Datum in aktueller Größe rechts ausgerichtet.

Hierdurch gewinnt man einige Pixel, was dem Platz für die restlichen Elemente zu Gute kommt.

Viele Grüße
Thomas

**Comment by rphl** [comment]
> Was hältst Du davon, bei den Impfungen das Icon DNA-Strang 🧬 durch die Spritze 💉 zu ersetzen?
Passt meiner Meinung nach etwas besser.

Generell schon, mir gefällt aber nicht das der Inhalt Rot ist: 💉
Müsste mal checken ob es bei den SF Symbols ein besseres gibt.

> ...
Zu den anderen Punkten müsste ich mal schauen, ob und wann. Gerne PR erstellen...

**Comment by jseegger** [comment]
Hallo,
vielleicht wäre das ein gutes Symbol für den Impfstatus:
https://cdn2.iconfinder.com/data/icons/corona-virus-covid-19-14/512/9_Flu_protection_vaccine_virus-512.png

Habe ich beim Widget von https://gist.github.com/marco79cgn/b5f291d6242a2c530e56c748f1ae7f2c gefunden ;-)

Gruß 
Jürgen

**Comment by Larosen** [comment]
> Hallo,
> vielleicht wäre das ein gutes Symbol für den Impfstatus:
> https://cdn2.iconfinder.com/data/icons/corona-virus-covid-19-14/512/9_Flu_protection_vaccine_virus-512.png
> 
> Habe ich beim Widget von https://gist.github.com/marco79cgn/b5f291d6242a2c530e56c748f1ae7f2c gefunden ;-)
> 
> Gruß
> Jürgen

Finde ich etwas „zu verspielt“ und zu groß. An sich wäre es vielleicht an der Zeit einen zweiseitigen Antrag auf ein neues Emoji zu stellen. Eine Spritze mit blauem Inhalt etwa. Das würde weltweit Anklang finden und müsste auch gut aufgenommen werden.

**Comment by rphl** [comment]
iOS 14.5 ersetzt das Blut in der Spritze. Werde nach dem Release das Icon wahrscheinlich updaten:

![iOS-14 5-new-syringe-emoji](https://user-images.githubusercontent.com/97642/110175559-4229c480-7e02-11eb-9b14-8407fc94ca9e.png)

**Comment by dennerforen** [comment]
Jupp, die Impfspritze ist gut, die Blutabnehmenspritze würde nicht zu impfen passen.

**Comment by PaulEwe** [comment]
Mittlerweile ist iOS 14.5 da 👍
