### ISSUE TITLE
Darstellung

### ISSUE THREAD

**Issue by Rfiach** [rphl/corona-widget#115]
Inzidenz kann seit heute nicht mehr korrekt dargestellt werden. 
![3772F98A-0FD6-4245-BD6D-6D271DE1F8AA](https://user-images.githubusercontent.com/74397552/103926140-d33d3180-5118-11eb-9474-962b34b896e6.jpeg)
Vielleicht ist das Problem aber auch schon bekannt.

**Comment by rphl** [comment]
Ist in der Tat ein edge case. Die Inzidenz liegt bei 99.95022138384554, der check ist aber nur gegen diesen ungerundeten Wert und erst ab >= 100 wird keine Nachkommastelle angezeigt. Sollte gefixt sein.
