### ISSUE TITLE
Nachkommastelle macht Inzidenz kaputt 

### ISSUE THREAD

**Issue by lkshck** [rphl/corona-widget#116]
Hi, mir ist heute aufgefallen, dass im Medium Widget eine Nachkommastelle angezeigt wird und dadurch kann die gesamte Inzidenz nicht angezeigt werden. Hat jemand eine Idee wie ich die Nachkommastellen komplett rauswerfen kann? Eigentlich wird ja schon immer entsprechend gerundet. Scheinbar tritt der Fehler nur bei ,0 auf.
![AD94E1A9-0D21-430D-AAEF-8FC18986D5A6](https://user-images.githubusercontent.com/46962619/103986978-fe149d80-518b-11eb-8750-646a621b2962.jpeg)

**Comment by rphl** [comment]
Verwendest du die aktuellste Version? 

Glaube das ist ein Duplikat von https://github.com/rphl/corona-widget/issues/115 Und da ist das Problem bereits gehoben.

**Comment by lkshck** [comment]
Habe mir die Version von gestern geholt. Gabs nochmal ein Update?

**Comment by lkshck** [comment]
Habe es nochmal neu kopiert, jetzt klappt es. Danke dir!

**Comment by rphl** [comment]
Falls es vor gestern 19 Uhr wahr dann ja. Siehe: https://github.com/rphl/corona-widget/commit/ed4ebfc6bddab1a720d11d31fed6d46c2468c771
