### ISSUE TITLE
...falsche Inzidenzwerte seit heute....???

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#117]
Hallo,

leider zeigt das Widget seit heute falsche Inzidenzwerte an. Hier:
„Nürnberg“ und „Nürnberger Land“
![948DD565-283F-4FE6-9F88-D2AFEE4F58A0](https://user-images.githubusercontent.com/8932465/104118417-31406380-5329-11eb-94e5-4f201c07b3e2.jpeg)

...???
![3AAACA65-32D8-4E98-95E5-0D5479B50E75](https://user-images.githubusercontent.com/8932465/104118388-05bd7900-5329-11eb-9fe2-a07f24921f73.jpeg)
![Uploading 1DAFDF77-F8D8-4D27-96FF-752D87D81E48.jpeg…]()

**Comment by firebowl** [comment]
Liegt vermutlich daran, dass Nürnberg seit 2 Tagen 0 Meldungen hat und am Tag davor 15, was garantiert nicht stimmt.

**Comment by STJIKA** [comment]
....das kann sein....im „Nürnberger Land“ ist es das Gleiche.....stimmt ebenfalls nicht.....

**Comment by apfelbasti** [comment]
Wollte eben auch schon ein Fehlerticket aufmachen. Lustig, dass unser Widget gleich aussieht, ich hab ebenfalls Nürnberger Land an erster und Nürnberg an zweiter Stelle.

**Comment by mrxoom1274** [comment]
Kreis Heinsberg auch fehlerhaft. RKI 111, lt Scrpt 144!

**Comment by icsAT** [comment]
Moin, ich hänge mich hier mal mit rein. Mir ist heute Morgen aufgefallen, dass das mittlere Widget den Inzidenzwert von gestern anzeigt, wogegen das kleine Widget den Inzidenzwert von heute anzeigt. Kann das sein?
![image](https://user-images.githubusercontent.com/74063738/104154252-c05e8180-53e4-11eb-9342-5dfb7155dbc2.jpeg)
Logge ich das ganze sehe ich ja leider erst mal nur das mittlere Widget:
![image](https://user-images.githubusercontent.com/74063738/104154307-e4ba5e00-53e4-11eb-9c52-88c1fca90504.png)
Addiere ich jetzt die 7 Werte vom 04.01. bis 10.01. komme ich auf 171. Geteilt durch die EWZ von Stade aus der RKI API (204.513) multipliziert mit 100.000 ergibt 83,6. Nehme ich den Zeitraum 03.01. bis 09.01. komme ich jedoch auf 175 Fälle und somit auf eine 85,6.

Hast Du eine Idee wo der Fehler in meinen Überlegungen ist und warum Dein kleines und mittleres Widget unterschiedliche Werte anzeigt?

Gruß André

**Comment by mrxoom1274** [comment]
![image](https://user-images.githubusercontent.com/70346648/104163242-6070d680-53f6-11eb-90ae-4e5d2adf8c21.jpeg)

Differenz sind 22-33 Punkte in Heinsberg.

**Comment by icsAT** [comment]
Ich habe mir das heute noch mal angesehen. Mittleres und kleines Widget stimmen wieder überein.
![image](https://user-images.githubusercontent.com/74063738/104283805-64156380-54b1-11eb-92ae-6d469885cdb4.jpeg)

Die berücksichtigten Werte sehen wie folgt aus.
![image](https://user-images.githubusercontent.com/74063738/104283904-87401300-54b1-11eb-932f-fd082df5698e.jpeg)

Wenn man nun vergleicht, stellt man fest, dass am 11.01. der jüngste Wert im Debug vom 10.01. ist. Die dort berechnete Inzidenz basiert auf den Werten vom 03.01. bis 09.01.
Heute ist der jüngste Wert von heute und die Inzidenz wird auf Basis der Werte 05.01. bis 11.01. berechnet.

Ich vermute, dass Du immer vom jüngsten Datum ausgehst, dass die Schnittstelle bei einer Summen-Abfrage "where=NeuerFall in (0,1)" zurückliefert und dann die Inzidenz für die davor liegenden 7 Tage berechnest. Wenn für den aktuellen Tag keine Daten vorliegen kommt es so zu einem Tag Versatz. Könnte das sein?
Beim kleinen Widget scheint das irgendwie anders zu laufen und es werden vom Tagesdatum ausgehend die davor liegenden 7 Tage berechnet.

Vielleicht kannst Du Dir das ja mal ansehen.

**Comment by icsAT** [comment]
@rphl darf ich fragen, warum Du das Issue kommentarlos geschlossen hast?
Ich bin nach wie vor der Meinung, dass Dein Widget keinen Inzidenzwert für den vergangenen Tag berechnet, wenn heute keine Daten vorhanden sind und die API für heute null zurück liefert. Dann wird der Inzidenzwert auf Basis der Daten von Vorgestern angezeigt.
Sollte das nicht so sein, wäre es schön, wenn Du mir kurz erklären könntest, wo mein Denkfehler liegt. Vielleicht habe ich ja auch einfach nur irgend etwas falsch verstanden.

Gruß André
