### ISSUE TITLE
Scriptable - Exception occured - RKI Api nicht verfügbar, Fehlermeldung,...

### ISSUE THREAD

**Issue by borrible13th** [rphl/corona-widget#118]
Folgende Fehlermeldung erhalte ich in Scriptable:

```
[timestamp]: SyntaxError: JSON Parse error: Expected '}'
[timestamp]: Error on line 785:79: TypeError: undefined is not an object (evaluating 'response.data.features[0].attributes')
```

Woran liegt dies? Konnten Daten nicht geladen werden?

**Comment by osxdoc** [comment]
Hier geht es seit heute auch nicht mehr, gleicher Fehler.

**Comment by icsAT** [comment]
RKI scheint aktuell Probleme zu haben. Einfach etwas Geduld haben ;-)

**Comment by mirko-pleli** [comment]
Auf eine hard-coded Stelle im Array zuzugreifen ist in meiner Erfahrung auch nicht common use.

**Comment by mirko-pleli** [comment]
@borrible13th Für die untere Fehlermeldung kannst du nichts, aber die obere musst du beheben. Da fehlt ein Semikolon das hast sehr wahrscheinlich beim bearbeiten entfernt.

**Comment by borrible13th** [comment]
@mirko-pleli Quellcode ist 1-zu-1 kopiert. Habe nichts verändert, sondern mir eine config.json angelegt. Erste Fehlermeldung kann daher nicht an mir liegen.

Mit Parameterübergabe für meinen Wohnort als statische Location 0 funktioniert es sporadisch. Hätte dies aber gerne dynamisch.

Aktuelle Fehlermeldung mit Location 0:
```
[timestamp]: Error on line 785:76: TypeError: undefined is not an object (evaluating 'response.data.features[0]')
```

Jetzt wird an eine andere Position verwiesen!? Sind die geladenen Daten korrupt?

**Comment by mirko-pleli** [comment]
@borrible13th Okay komisch. Ich habe eben das Script geupdatet und bei mir fehlt im Code kein Semikolon. Bei dem unteren Punkt gebe ich dir recht.

**Comment by bwcgn** [comment]
Es scheint ein API Problem zu geben im Moment. Habe die Requests mal über Postman rausgefeuert, und bekomme mal Ergebnisse und mal bekomme ich den Fehler:
`{"error":{"code":400,"message":"Invalid URL","details":["Invalid URL"]}}`

Das Fehlerhandling an dieser Stelle 
`return response.status === ENV.status.ok`
scheint in dem fall aber nicht zu greifen, da der HTTP Status mit 200 returned wird.

**Comment by rphl** [comment]
Leider ist hier die API wohl down. Was eigentlich kein Problem sein müsste. 

Das Problem ist eher wie @bwcgn  schon erwähnt hat, das der HTTP Statuscode `200` ist. Anstatt wie erwartet `400`.  Werde gleich mal ein fix online stellen... 

```
{
  "error": {
    "code": 400,
    "message": "Invalid URL",
    "details": [
      "Invalid URL"
    ]
  }
}

```

**Comment by rphl** [comment]
Durch die fehlerhafte Api Rückgabe wurden wohl auch die "falschen" Daten gecached. D.h. ein laden aus dem Cache wird vorerst auch "fehlschlagen". Denke wenn die Api vollständig wieder verfügbar ist, sollte auch beim nächsten Ausfall der cache greifen. 🤷‍♂️ Abwarten

Habe mal auf die schnelle ein Update online gestellt. .... Gerne testen.

**Comment by mirko-pleli** [comment]
Danke für den schnellen fix, bei mir tut es wieder zumindest mit den Cache Daten.

**Comment by jnhllTM4** [comment]
Muss man das Update manuell installieren oder zieht er sich das auch über Auto-Update?

**Comment by Stefan-1982** [comment]
Ich hab das neue Update eingestellt ging auch erst nun kommt ne neue Fehlermeldung.. 
![1F62F297-7362-4DE5-A4C2-72CA7006854F](https://user-images.githubusercontent.com/76473844/104614401-831a1e00-5688-11eb-84a9-5285717116de.jpeg)

**Comment by rphl** [comment]
Ist auch schon korrigiert... vor 18min
https://github.com/rphl/corona-widget/commit/d18796a2652aeac0c8527622fda025b3360f3bdf

**Comment by borrible13th** [comment]
Vielen Dank! Sieht soweit super aus bei mir. 
Hier, wo meine dynamischen Standortdaten wahrscheinlich nicht geladen werden konnten, bekomme ich jetzt eine anwenderfreundliche Fehlermeldung. 😄. Wohne halt direkt auf der Stadtrand- und gleichzeitig Bundeslandgrenze. Wahrscheinlich im Niemandsland dann. 😆

**Comment by rphl** [comment]
Bis die API vollständig wieder verfügbar ist. Sind die Daten aus dem "cache" oder eben die Fehlermeldung die einzige option.
