### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by LancerII** [rphl/corona-widget#119]
Hi, vorab schönen Dank für das super Script👍🏻

Seit Heute habe ich aber eine Fehlermeldung im Script. Hatte schon den Script neu gelesen, ist aber dabei geblieben. 

![2E720D00-094E-4F89-86F7-4DDA1B1F4A34](https://user-images.githubusercontent.com/77447889/104603079-5d871780-567c-11eb-93af-c97c3ac30c66.jpeg)

Was hat dieses zu bedeuten und was kann ich machen damit es wieder reibungslos funktioniert❓
Vllt kannst Du den Fehler begeben....

Besten Dank für deine Hilfe.

**Comment by rphl** [comment]
Siehe das bereits erstellte Ticket #118 Ein update ist schon online. Siehe auch #118.

**Comment by rphl** [comment]
Duplikat #118
