### ISSUE TITLE
Trend für die Gesamtzahl

### ISSUE THREAD

**Issue by Nils89** [rphl/corona-widget#12]
Bei den Gesamtzahlen wird aktuell nur zum Vortag Vergleich, sprich der Pfeil geht heute hoch. 

Wenn man allerdings den Trend der letzten Tage vergleicht, müsste der Pfeil runter gehen. 

Kannst du dort den Trend so einbauen wie bei den andern beiden?

**Comment by rphl** [comment]
Wäre eine Idee. Dann wäre die Logik für alle Trendpfeile gleich.

**Comment by STJIKA** [comment]
> Wäre eine Idee. Dann wäre die Logik für alle Trendpfeile gleich.
...echt TOP, DEIN Widget und der Code...!!!! Riesiges Kompliment und Respekt...!!!

...finde auch, daß es besser und logischer ist wenn im gesamten Widget die gleiche Logik anzustzen ist.....

**Comment by rphl** [comment]
Änderung ist jetzt online.

**Comment by STJIKA** [comment]
...super...Vielen Dank!!!
