### ISSUE TITLE
Fehlermeldung....?????

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#120]
![Bildschirmfoto 2021-01-14 um 16 55 29](https://user-images.githubusercontent.com/8932465/104615309-6af6ce80-5689-11eb-9e17-610dbfc3eaef.jpg)
...ich habe jetzt diese hier...
Parameter: 0,49.38,11.35,NÜRNBERGER LAND;1,49.44,11.08

...???

**Comment by rphl** [comment]
Duplikat #118
