### ISSUE TITLE
+ - neue Infektionen

### ISSUE THREAD

**Issue by 1rNidiD** [rphl/corona-widget#121]
Hey bei mir steht + - 138 und der Balken ist weiß. Ist so ein Fehler schon bekannt? Liegt war. am RKI aber ich wollte es mal teilen.. 
![image](https://user-images.githubusercontent.com/47744797/105331995-6627a280-5bd4-11eb-9a96-988d5c71ca82.jpeg)

Parameter:
0,48.1351,11.5819,Stadt München;1,48.0782,11.6392,Universität

**Comment by rphl** [comment]
Hmm strange. In der tat liefert die RKI API -138 Fälle für heute an deinem Standort. Wurden etwas zu viele gemeldet? Und das wird jetzt korrigiert? 
Denke mann müsste es abwarten... Bzw. du könnest es mal für deine Region checken.

Das `+-` ergibt sich daraus, dass nie negative Zahlen vorgesehen waren, und deswegen das `+` statisch drin ist.

```
{
  "objectIdFieldName": "ObjectId",
  "uniqueIdField": {
    "name": "ObjectId",
    "isSystemMaintained": true
  },
  "globalIdFieldName": "",
  "fields": [
    {
      "name": "cases",
      "type": "esriFieldTypeDouble",
      "alias": "cases",
      "sqlType": "sqlTypeFloat",
      "domain": null,
      "defaultValue": null
    },
    {
      "name": "date",
      "type": "esriFieldTypeDouble",
      "alias": "date",
      "sqlType": "sqlTypeFloat",
      "domain": null,
      "defaultValue": null
    }
  ],
  "features": [
    {
      "attributes": {
        "cases": -138,
        "date": 1611100800000
      }
    }
  ]
}
```

**Comment by 1rNidiD** [comment]
Ich versuche da mal was in Erfahrung zu bringen. Danke :)

**Comment by rphl** [comment]
@1rNidiD <img width="1134" alt="Bildschirmfoto 2021-01-21 um 14 08 34" src="https://user-images.githubusercontent.com/97642/105355279-3091b200-5bf2-11eb-86cd-105112dc3f0d.png">

**Comment by 1rNidiD** [comment]
Alles klar danke 😊 dann kann des hier ja wieder geschlossen werden 💪🏻 danke für dir schnelle Info und danke für deine tolle Arbeit!
