### ISSUE TITLE
Anzeige fehlerhaft, wenn Systemschrift fett

### ISSUE THREAD

**Issue by HappyGeoCacher** [rphl/corona-widget#122]
![image](https://user-images.githubusercontent.com/77704168/105616429-2381e800-5dd7-11eb-8d52-fe5675e7aa60.png)

**Comment by HappyGeoCacher** [comment]
... Problem liegt wohl auch an der Darstellung mit einer Nachkommastelle bei Inzidenz < 100.

**Comment by rphl** [comment]
Leider ist Platztechnisch nicht viel Spielraum. Und über das Widget lässt sich das bedingt steuern. Evtl  die min. Textskaliering anpassen. Müsste ich mal prüfen, da die Standardschrift nicht verändert werden sollte.

**Comment by HappyGeoCacher** [comment]
Schriftgröße in den iPhone Systemeinstellungen ist Standard (Mitte), nur soll wegen des besseren Kontrasts systemweit fett genutzt werden. Ü50 braucht das manchmal.
3-stellige Inzidenz wurde bislang ohne Nachkommastellen korrekt angezeigt, 2-stellige mit (unsinniger) Nachkommastelle passt nicht mehr.

**Comment by rphl** [comment]
Die Standardschrift war auf das Widget bezogen.

Und ja, dass mit den Nachkommastelle hatte ich auch schon mal nachgedacht. In einer früheren Version wurde die bei < 10 nur angezeigt. Evtl werde ich das wieder aufnehmen... Ich meine hatte es mal im Fragen Ticket gepostet.

**Comment by rphl** [comment]
habe die Schrift etwas angepasst. Ein update ist online gerne testen und sonst das Ticket wieder aufmachen.
