### ISSUE TITLE
Inzidenz Trend (Pfeil) nicht korrekt

### ISSUE THREAD

**Issue by HappyGeoCacher** [rphl/corona-widget#123]
Trotz leicht steigender Inzidenz von 59,x auf 65,x zeigt der Pfeil in grün nach unten.

**Comment by rphl** [comment]
Hallo. Die Tendenz zeigt einen Wochentrend: Vorwoche vs Aktuelle.


Siehe auch Readme: https://github.com/rphl/corona-widget#features

![Readme](https://raw.githubusercontent.com/rphl/corona-widget/master/screenshots/info.jpg)
