### ISSUE TITLE
Live-Incidence Value and Error on Line 915:25 TypeError: undefined is not an object

### ISSUE THREAD

**Issue by icsAT** [rphl/corona-widget#124]
Guten Morgen Raphael,

ich habe heute Morgen  einen Fehler im Widget (s. Screenshot) unter Verwendung des folgenden Parameters: "0,53.45,9.80;1,53.48,12.41".
Das hängt sicherlich mit diversen Korrekturen heute Nacht beim RKI zusammen. Da kommen aus der API möglicher Weise unerwartete Werte. 

Ich möchte auch noch einmal auf eine Unschärfe in der Live-Inzidenz hinweisen, wenn die RKI-API für heute null liefert, nimmst Du die Live-Inzidenz von vorgestern und nicht von gestern. (s. Screenshot / Parameter: "0,53.4709,9.7198;1,53.5503945,9.9924518")
Ich stimme mit Dir bei allen Live-Inzidenzwerten überein. Hamburg, Niedersachsen, Deutschland die auch abweichend zum RKI sind. Nur für Stade passt es nicht. Das müsste imho die Live-Inzidenz 42,5 sein. 

Gruß André

![image](https://user-images.githubusercontent.com/74063738/106098788-ea7ca700-6139-11eb-9ed6-e880af13c218.jpeg)

![image](https://user-images.githubusercontent.com/74063738/106098879-126c0a80-613a-11eb-8d09-099146ccf7a5.png)

**Comment by icsAT** [comment]
Die Fehlermeldung ist zwischenzeitlich weg. Ich denke, das lag an den vom RKI bereitgestellten Werten. Da kam zwischenzeitlich sicherlich irgend etwas unerwartetes über die API. 

Der zweite Punkt ist aber nach wie vor aktuell.

**Comment by rphl** [comment]
Hello. Wollte mir das eben anschauen, anscheinend wurde es aber schon korrigiert. Die Zahlen sind jetzt auch deutlich gesunken (D: 17,5k anstatt D:31k) Nicht desto trotz werde ich mal versuchen zu checken, was da von der rki-api zurück gekommen sein könnte.

...

Wegen der LiveInzidenz. In den Logs sehe ich das es für heute noch keine Infos in **Stade** gibt. Das führt dazu, das davon ausgegangen wird das eine "0" "Null" (noch keine Daten) gemeldet worden ist, und somit diese übersprungen wird. Was auch für "heute" korrekt wäre. 

Für den Fall müsste man die Werte bis "heute" mit einer "0" auffüllen. (Nicht nur die Lücken)

**Comment by rphl** [comment]
... Glaube auch das Datum ist manchmal irreführend, es müsste bei **Stade** den 27.01 anzeigen. Problem sind hier wiederherum zwei Standorte mit unterschiedlichen "letzen" Datumsangaben (27.01 Stade, 28.01. Hamburg) Aktuell bezieht sich das Datum auch auf D.

**Comment by rphl** [comment]
<img width="128" alt="Bildschirmfoto 2021-01-28 um 11 22 32" src="https://user-images.githubusercontent.com/97642/106124229-25430700-615b-11eb-82cb-2ec13796d3d1.png">

**Comment by icsAT** [comment]
Moin,

auf das Datum habe ich gar nicht geguckt ;-)

Und ja, die Tabelle müsste für heute mit Null aufgefüllt werden, so wie bei den Lücken. Denn faktisch berücksichtigst Du die Zahlen von gestern nicht, wenn für heute noch keine Daten vorhanden sind.

Danke übrigens für Dein tolles Projekt.

**Comment by icsAT** [comment]
Oh, Du hast es schon angepasst.

**Comment by rphl** [comment]
Habe mal das Update online gestellt. Gerne testen.

**Comment by icsAT** [comment]
Habe ich gemacht. Sieht gut aus, so passt es meiner Meinung nach. Danke.

**Comment by icsAT** [comment]
Moin Raphael,

was bei der Datenlage gestern noch gut aussah, sieht heute leider nicht mehr so gut aus ;-(

Meine Abfrage der neuen Fälle heute (NeuerFall in (-1,1)) liefert mir:
"attributes" : {
        "newCases" : 24, 
        "ncDate" : 1611705600000
      }

Meine Abfrage der älteren Fälle (NeuerFall in (1,0)) liefert mir:
{
      "attributes" : {
        "cases" : 15, 
        "MeldeDatum" : 1611705600000
      }
    }, 
    {
      "attributes" : {
        "cases" : 23, 
        "MeldeDatum" : 1611619200000
      }
    }, 
    {
      "attributes" : {
        "cases" : 14, 
        "MeldeDatum" : 1611532800000
      }
    }, 
    {
      "attributes" : {
        "cases" : 1, 
        "MeldeDatum" : 1611446400000
      }
    }, 
    {
      "attributes" : {
        "cases" : 16, 
        "MeldeDatum" : 1611360000000
      }
    }, 
    {
      "attributes" : {
        "cases" : 18, 
        "MeldeDatum" : 1611273600000
      }
    }

Für gestern "MeldeDatum" : 1611792000000  (28.01.2021) wurde von keiner der beiden Abfragen Werte geliefert, da es für gestern keine Meldungen gab.

Gucke ich mir jetzt Deinen Log für Stade an, sehe ich:
"29.01.2021" | 0 | 54.27554373337506
"28.01.2021" | 24 | 56.231419183226414
"27.01.2021" | 15 | 67.96667188233454
.
.
.

Eigentlich müsste die "24" beim 29.01. stehen und die "0" beim 28.01. Da ist bei Deinem Fix gestern was schief gelaufen, sorry.

Korrrekt wäre nach meiner Berechnung ein Inzidenzwert von 42,5.


Gruß André

**Comment by icsAT** [comment]
Moin Raphael,

was bei der Datenlage gestern noch gut aussah, sieht heute leider nicht mehr so gut aus ;-(

Meine Abfrage der neuen Fälle heute (NeuerFall in (-1,1)) liefert mir:
"attributes" : {
"newCases" : 24,
"ncDate" : 1611705600000
}

Meine Abfrage der älteren Fälle (NeuerFall in (1,0)) liefert mir:
{
"attributes" : {
"cases" : 15,
"MeldeDatum" : 1611705600000
}
},
{
"attributes" : {
"cases" : 23,
"MeldeDatum" : 1611619200000
}
},
{
"attributes" : {
"cases" : 14,
"MeldeDatum" : 1611532800000
}
},
{
"attributes" : {
"cases" : 1,
"MeldeDatum" : 1611446400000
}
},
{
"attributes" : {
"cases" : 16,
"MeldeDatum" : 1611360000000
}
},
{
"attributes" : {
"cases" : 18,
"MeldeDatum" : 1611273600000
}
}

Für gestern "MeldeDatum" : 1611792000000 (28.01.2021) wurde von keiner der beiden Abfragen Werte geliefert, da es für gestern keine Meldungen gab.

Gucke ich mir jetzt Deinen Log für Stade an, sehe ich:
"29.01.2021" | 0 | 54.27554373337506
"28.01.2021" | 24 | 56.231419183226414
"27.01.2021" | 15 | 67.96667188233454
.
.
.

Eigentlich müsste die "24" beim 29.01. stehen und die "0" beim 28.01. Da ist bei Deinem Fix gestern was schief gelaufen, sorry.

Korrrekt wäre nach meiner Berechnung ein Inzidenzwert von 42,5.

Gruß André
