### ISSUE TITLE
Neue Fälle BY / D bei 0 ?!?

### ISSUE THREAD

**Issue by Stefan-1982** [rphl/corona-widget#125]
Ich habe bei mir des Öfteren das Problem das beim Medium Widget der Wert der Neuinfektionen BY / D bei 0 ist und nicht aktualisiert wird.. wenn ich das Widget anklicke und es somit über Scriptable aktualisiere dauert es bisschen und dann werden die Zahlen korrigiert. Komischerweise wird der D Wert wenn die Zahlen bei 0 sind nach oben verfrachtet und BY unten doppelt angezeigt.

in der Cofig Datei habe ich folgendes eingetragen:  {"showVaccineInMedium": true}

![39B897CC-28ED-4F01-BEE2-65C7DD5E2826](https://user-images.githubusercontent.com/76473844/106272373-4118dc80-6231-11eb-8fdf-a3012fe62215.jpeg)

![9428E621-E4CB-4AAC-97D4-F9BAB9C22C64](https://user-images.githubusercontent.com/76473844/106272396-4a09ae00-6231-11eb-8b8e-cf54440f1030.jpeg)

**Comment by plorenz80** [comment]
Gibt es hier schon News? Für HH stehen die Zahlen auch auf "0"

**Comment by rphl** [comment]
Postet bitte mal die Widgetparameter, denn so muss ich immer den Standort erst suchen. Und das kann unter umständen zu fehlern führen.

**Comment by Stefan-1982** [comment]
1,50.323376,10.216617

**Comment by Stefan-1982** [comment]
1,50.323376,10.216617

**Comment by plorenz80** [comment]
0,53.5674,9.9951

**Comment by rphl** [comment]
@plorenz80  Für Hamburg liefert die RKI Api keine Daten: Anwtwort ist nur `Bad Request` Hier müssen wir mal wieder abwarten 🤷‍♂️

...

@Stefan-1982 Danke. Für diesen Standort kommen Daten mittlerweile raus. Denke hier hat das RKI das Problem behoben (Wie aktuell noch bei Hamburg):
![Bildschirmfoto 2021-02-05 um 12 51 10](https://user-images.githubusercontent.com/97642/107030531-168ace80-67b1-11eb-8e87-5f02d4ff9bd0.png)


Andere Standorte (incl. meinen) liefern Daten. Denke das es wieder ein problem der RKi API ist.

**Comment by plorenz80** [comment]
Danke für das Update :-)

**Comment by Stefan-1982** [comment]
> @plorenz80 Für Hamburg liefert die RKI Api keine Daten: Anwtwort ist nur `Bad Request` Hier müssen wir mal wieder abwarten 🤷‍♂️
> 
> ...
> 
> @Stefan-1982 Danke. Für diesen Standort kommen Daten mittlerweile raus. Denke hier hat das RKI das Problem behoben (Wie aktuell noch bei Hamburg):
> ![Bildschirmfoto 2021-02-05 um 12 51 10](https://user-images.githubusercontent.com/97642/107030531-168ace80-67b1-11eb-8e87-5f02d4ff9bd0.png)
> 
> Andere Standorte (incl. meinen) liefern Daten. Denke das es wieder ein problem der RKi API ist.


Und warum kommt beim Medium noch immer 0 ab und an ? Bei small Widget passt es! 
![287116B4-1DD8-4DC4-814E-E5E62607A33F](https://user-images.githubusercontent.com/76473844/107046607-1d244080-67c7-11eb-9e48-9ef5662111fa.jpeg)

**Comment by Stefan-1982** [comment]
Schon seltsam das ganze mit den 2 nullern... und gleichzeitig kommt dann auch die Satelliten Schüssel oben wenn ich das Widget dann anklicke aktualisiert es sich mit den Werten dann...

weiß keiner einen Rat?

**Comment by rphl** [comment]
Hier kann ich aktuell nichts machen, die RKI liefert keinen Werte für den Standort. Bzw. gibt nur Fehler aus. Siehe auch:  https://github.com/rphl/corona-widget/issues/6#issuecomment-781248349

Habe mal den Kommentar nochmal hier hineinkopiert:

```

@wombart @Larosen leider liefert hier die RKI Api für eure Standorte einen Fehler aus. Siehe:

https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?f=json&where=NeuerFall%20IN(1,-1)%20AND%20IdLandkreis%3D09375&objectIds&time&resultType=standard&outFields&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields&groupByFieldsForStatistics&outStatistics=%5B%7B%22statisticType%22:%22sum%22,%22onStatisticField%22:%22AnzahlFall%22,%22outStatisticFieldName%22:%22cases%22%7D,%20%7B%22statisticType%22:%22max%22,%22onStatisticField%22:%22MeldeDatum%22,%22outStatisticFieldName%22:%22date%22%7D%5D&having&resultOffset&resultRecordCount&sqlFormat=none&token" | "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall+IN%281%2C0%29+AND+IdLandkreis=09375+AND+MeldeDatum+%3E%3D+TIMESTAMP+%272021-01-21%27&objectIds=&time=&resultType=standard&outFields=AnzahlFall%2CMeldeDatum&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=MeldeDatum&groupByFieldsForStatistics=MeldeDatum&outStatistics=%5B%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22AnzahlFall%22%2C%22outStatisticFieldName%22%3A%22cases%22%7D%5D%0D%0A&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=``

z.B Regensburg heute, Antwort = "BAD REQUEST"

Bildschirmfoto 2021-02-18 um 11 31 32

Diese Rückgabe muss das Widget korrigieren, somit wird für heute eine 0 angezeigt. Evtl. kann man das noch besser Kennzeichnen.

Hier müssten wir auf einen fix vom RKI warten.
```
<img width="461" alt="Bildschirmfoto 2021-02-18 um 11 31 32" src="https://user-images.githubusercontent.com/97642/108343999-e2fe6a00-71dc-11eb-9d5a-91f1521bfb48.png">
