### ISSUE TITLE
Gelbe Inzidenz-Farbe nicht lesbar

### ISSUE THREAD

**Issue by chimcen** [rphl/corona-widget#126]
Servus,

bei mir ist die gelbe Inzidenz-Farbe nicht gut lesbar…
![2691D784-0F01-49DD-82F3-7343ADA11832](https://user-images.githubusercontent.com/22658487/108123838-bf390800-70a6-11eb-888a-96401dfa4d8d.jpeg)

Hab diese nun mit der hier (F8F602) - ist besser lesbar.

![CBA83223-D591-4280-B1E6-B52D781291D1](https://user-images.githubusercontent.com/22658487/108124110-16d77380-70a7-11eb-8437-f7c02c5f8966.jpeg)

Könnte man vll. einfließen lassen. Danke :)

**Comment by rphl** [comment]
Gelb, so eine ungewohnte Farbe seit langer Zeit. Habe die etwas angepasst.

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/120567955-3060b900-c413-11eb-863c-062aec083da2.jpeg)

**Comment by ragalthar** [comment]
Gelb unlesbar in small Widget
