### ISSUE TITLE
Dark Mode über config.json erzwingbar?

### ISSUE THREAD

**Issue by nicoh88** [rphl/corona-widget#127]
Hi, danke für das tolle Widget! Nutze es schon seit Monaten!

Ist der „Dark Mode“ über `config.json` erzwingbar?

Gruß Nico

**Comment by rphl** [comment]
Wäre eine Idee. Man müsste aber hier alle Schriftfarben setzen, da aktuell iOS die Farben kontrolliert.

**Comment by rphl** [comment]
Habe mal ein Update online gestellt. Gerne testen...

**Comment by nicoh88** [comment]
Läuft! Danke
