### ISSUE TITLE
Impfzahlen werden nicht mehr komplett angezeigt 

### ISSUE THREAD

**Issue by Nils89** [rphl/corona-widget#128]
Hallo,

die Impfzahlen auf dem iPhone SE werden nicht mehr ganz angezeigt, wenn diese im BL größer 1 Millionen sind:

![8E5F39C6-530E-4519-A057-8B0B6B04BBC2](https://user-images.githubusercontent.com/23194902/110235621-751ea600-7f31-11eb-9cfb-7e5ca8552ae2.jpeg)

Kann man da was machen?

**Comment by rphl** [comment]
Die Zahlen werden zum Glück nicht kleiner. Evtl. werde ich das Bundesland entwerfen oder Datum kürzen: `05.03`

**Comment by rphl** [comment]
Habe ich angepasst, update ist online.

![image](https://user-images.githubusercontent.com/97642/110787716-fcd81d80-826d-11eb-9f45-361a8b2d50a8.png)
