### ISSUE TITLE
R wert mit , nicht mit .

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#13]
Der R wert wird ja aktuell als 
x.xx
angezeigt.  
Der . ist aber sonst im Widget das 1000er Trennzeichen. 
Somit wäre es meiner Meinung nach sauberere, den R wert als 
x,xx
anzuzeigen.

**Comment by rphl** [comment]
Das stimmt, habe es mal angepasst..

**Comment by tomacco81** [comment]
Beim Inzidenzwert müsste das dann aber konsequenterweise ebenfalls angepasst werden 😉
