### ISSUE TITLE
script fails (undefined is not an object)

### ISSUE THREAD

**Issue by akuropka** [rphl/corona-widget#134]
copied and pasted the script, made no modifications.
iPhone 12 Pro Max with iOS 14.5b3 (18E5164h)

`2021-03-14 10:29:17: Error on line 642:37: TypeError: undefined is not an object (evaluating 'completeDataObj[curDate].cases = value.cases')`

**edit:** now it works; maybe some data was not retrieved, setting debugIncidencCalc to true didn't bring up anything.

![IMG_0636](https://user-images.githubusercontent.com/22570574/111063760-cb02c900-84b0-11eb-97a4-7768de799fb6.PNG)

**Comment by rphl** [comment]
> edit: now it works; maybe some data was not retrieved, setting debugIncidencCalc to true didn't bring up anything.

`debugIncidencCalc` prints only on console, not directly in the widget.

**Comment by akuropka** [comment]
Thanks for the hint, started the script before adding as widget and on console (Log) was only this error.

**Comment by rphl** [comment]
ok, closing for now.

**Comment by akuropka** [comment]
Happens today again…
![ABC74F5F-59B8-481C-87C2-3A79E6BAA3EC](https://user-images.githubusercontent.com/22570574/111592614-4cb46880-87c9-11eb-9e2f-7ebdca8fccbc.png)
