### ISSUE TITLE
7 Tage Schätzwert n/v

### ISSUE THREAD

**Issue by eros1810** [rphl/corona-widget#135]
Beim Wert erscheint seit Tagen.  N/V
Wie kann man das beheben?

**Comment by 1rNidiD** [comment]
Bei mir auch seit gestern. Denke des ist n Fehler vom RKI.

**Comment by Eeewald85** [comment]
Seit dem 11.3. wird die CSV Datei für den r-Wert vom RKI anscheinend nicht mehr aktualisiert. Zumindest ist der letzte Eintrag dort vom 11.3. 

-> https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile

**Comment by rphl** [comment]
Wie eewald85 es schon erwähnt hat, liegt es am RKI bzw. der CSV die hochgeladen wurde. Auf der Webseite steht zwar das es vom 15.03 sein soll, die Datei selbst ist aber älter.

Ich prüfe es trotzdem aber mal warum der Wert vom 11.03 nicht verwendet wird.

**Comment by eros1810** [comment]
> Wie eewald85 es schon erwähnt hat, liegt es am RKI bzw. der CSV die hochgeladen wurde. Auf der Webseite steht zwar das es vom 15.03 sein soll, die Datei selbst ist aber älter.
> 
> Ich prüfe es trotzdem aber mal warum der Wert vom 11.03 nicht verwendet wird.

Super danke fürs prüfen - hoffe ist lösbar dass dann auch immer aktuellste Werte automatisch sichtbar sind.  Aber sonst echt gutes Widget 👍💪

**Comment by rphl** [comment]
Wie es aussieht hat die Datei ein Windows1252 encoding, der RKI Server verschickt es aber als utf8. 
Das hat zur Folge, dass Sonderzeichen/Umlaute nicht korrekt konvertiert werden, und somit das Feld/Spalte nicht gefunden wird...

Ein vorläufiger workaround ist online. Gerne testen....

**Comment by eros1810** [comment]
wow Super zumindest nun ist ein Wert sichtbar
![A2D131D4-6523-4EF2-AB6D-9950B97CB572](https://user-images.githubusercontent.com/80743341/111366110-66ec2a80-8693-11eb-887a-52f43a6f5eb6.jpeg)

musst du dann erneut etwas anpassen wenn die Kodierung korrigiert wird seitens RKI?

**Comment by 1rNidiD** [comment]
Bei mir klappt alles! Danke für das schnelle Update 💪🏻
