### ISSUE TITLE
Fehlermeldung im Widget TypeError

### ISSUE THREAD

**Issue by eros1810** [rphl/corona-widget#136]
Hi zusammen habe heut folgende Fehlermeldung im Widget. Ist hierzu etwas bekannt bzw gib es eine Lösung hierzu?

![D02E6E9F-4F6D-4DEC-B794-3F70441D3CC1](https://user-images.githubusercontent.com/80743341/111584789-9f3c5780-87be-11eb-9d65-84a0413a1096.jpeg)

**Comment by eros1810** [comment]
Scheint nun erneut zu funktionieren
Problem aktuell ist dass der R Schätzwert immer auf 1,06 seit 2 Tagen fix bleibt?

**Comment by rphl** [comment]
Wert Stimmt. Ist der letzte vom RKI veröffentlichte. 
Daten werden wohl nur noch Zeitversetzt bereitgestellt. Siehe Quelle: 

`https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile`

**Evtl. werde ich das Datum splitten (RWert/Inzidenz). Damit es aktuell klarer wird, dass manche Werte evtl. nicht aktuell:**

---

![Bildschirmfoto 2021-03-18 um 13 03 16](https://user-images.githubusercontent.com/97642/111623281-729e3500-87ea-11eb-8bf5-7a350072d940.png)

**Comment by eros1810** [comment]
Oh ok super Idee finde ich
Danke fürs prüfen und die schnelle Rückmeldung.
Wie immer Top Arbeit deinerseits.
Bisher das beste corona Widget den ich verwendet habe 💪👍
