### ISSUE TITLE
Verstehe es nicht 

### ISSUE THREAD

**Issue by loui14** [rphl/corona-widget#137]
Ich bin wahrscheinlich einfach zu dumm und richte das Widget falsch ein 
![07E76F8E-FD9B-40D5-BF57-455124455D4B](https://user-images.githubusercontent.com/75144728/112022156-4d832c80-8b32-11eb-81e9-4f6f68c93408.jpeg)

**Comment by rphl** [comment]
Hallo. Siehe hier meine Info die ich vorhin gepostet hab. Das sollte es schnell lösen: https://github.com/rphl/corona-widget/issues/6#issuecomment-804108987
