### ISSUE TITLE
Error Line 770

### ISSUE THREAD

**Issue by ing-michel** [rphl/corona-widget#140]
Hallo, bekomme seit heute einen Error in line 770:49. 
bis gestern lief es tadellos:
`2021-04-14 12:22:37: Error on line 770:49: TypeError: undefined is not a function `

**Comment by rphl** [comment]
Sehe aktuell keine Fehlermeldung. Hast du Widgetparameter gesetzt?
Liegt wahrscheinlich an der RKI Api.

**Comment by ing-michel** [comment]
Hallo Rphl,
Danke für Deine Rückmeldung. Geht nun auch wieder. War wohl ein temporäres Problem. 
gruss
Michel
