### ISSUE TITLE
Hintergrundbild lässt sich nicht ändern

### ISSUE THREAD

**Issue by leonshr** [rphl/corona-widget#141]
Ich bin ein absoluter Fan von Deinem Script und freue mich total über die Option, einen eigenen Hintergrund für das Widget einstellen zu können. 

Leider klappt das nicht. Ich habe sowohl im Theme für den Light Mode, als auch für den Dark Mode meine URL für das Bild hinterlegt aber nichts passiert. Was mache ich falsch? 😔 

![image](https://user-images.githubusercontent.com/71948374/114881406-4551a080-9e03-11eb-84ce-10ea391f989f.png)

**Comment by rphl** [comment]
Es gab noch ein kleinen Fehler, jetzt geht es aber. Am besten dafür eine `config.json` anlegen, sonst musst du die Änderungen bei jeden Update erneut durchführen. 
**Noch als Hinweis: (Siehe auch Readme)** Wenn ein Hintergrundbild nutzen möchtest, muss das Theme angeben werden. Ab dann ist ein AutoSwitch nicht mehr möglich. (buggy in Scripable)

**config.json**
```
{
    "theme": "dark",
    "themes": {
         "dark": {
            "mainBackgroundImageURL": "https://picsum.photos/600/300"
        }
    }
}
```

**Comment by 1rNidiD** [comment]
![image](https://user-images.githubusercontent.com/47744797/114903773-6c19d200-9e17-11eb-9b37-a4ae89a40068.jpeg)

Bei "Dark" müsste dann der Darkmode als Erklärung kommen und nicht der Lightmode...nur ein kleiner Schönheitsfehler. 😊
Danke und liebe Grüße.

**Comment by rphl** [comment]
@1rNidiD Werde ich beim nächsten commit anpassen ;)
