### ISSUE TITLE
Trend Pfeil zeigt immer nach oben

### ISSUE THREAD

**Issue by Superduperduu04** [rphl/corona-widget#143]
Der Trend Pfeil für die Neuinfektionen zeigt neuerdings bei mir immer nach oben, obwohl die Zahlen gesunken sind

**Comment by rphl** [comment]
Die Pfeile sind **Wochentrends**. d.h Durchschnitt letzte Woche vs. Durchschnitt vorletzte Woche. Siehe auch readme.

Und falls der Pfeil in deiner Region lange nach oben zeigt, ist es wahrscheinlich ein Indiz das sich wohl nicht mehr so viele an die Regeln halten 🤷‍♂️

Poste gerne deine Widgetparameter / groben Standort. Dann könnte ich es trotzdem mal prüfen...

![image](https://user-images.githubusercontent.com/97642/116455566-8022f200-a861-11eb-9a75-cb4272dd6558.png)

**Comment by Superduperduu04** [comment]
Ah okay - danke für die schnelle Antwort. Ich habe vor kurzem erst seit längerem mal wieder geupdatet - aber früher waren es Tagestrends oder?

**Comment by rphl** [comment]
Ja früher was es ein Tagestrend. Ein Wochentrend ist aber stabiler/aussagekräftiger. Der Tagestrend war in vielen Regionen auf Grund von Meldeproblemen/Verzögerungen oft falsch.

Werde das Ticket mal schließen. Bei Problemen gerne eins öffnen.
