### ISSUE TITLE
Daten konnten nicht geladen werden

### ISSUE THREAD

**Issue by nicop2000** [rphl/corona-widget#144]
Das widget scheint die Daten nicht holen zu können. Weder mit festen Standort Daten noch mit automatischer Erkennung
![0B7A3AC3-E6D5-4D48-80E0-466C8CDBC7FD](https://user-images.githubusercontent.com/77485281/116561449-9c2aa000-a902-11eb-8467-c7fd8158582e.png)

**Comment by rphl** [comment]
Laut der Meldung würde ich auf eine alte Version des Widgets tippen.
Bitte die neuste aus dem Repo verwenden und nochmal ausprobieren.
