### ISSUE TITLE
Impfquote - Vollständig geimpft

### ISSUE THREAD

**Issue by MajorTomDE** [rphl/corona-widget#145]
Hallo,

aktuell zeigt das Widget die Impfquote auf Basis der Erstimpfung an.
Was hältst Du davon, alternativ die Impfquote auf Basis der vollständigen Impfungen anzuzeigen?

Aktuell ist der Unterscheid ziemlich gravierend.

Wenn ich mir die API anschaue, sollte es eigentlich möglich sein:
https://rki-vaccination-data.vercel.app/api >>> 2nd_vaccination

Beim Medium Widget könnte es vom Platz her sogar klappen, beide Werte anzuzeigen.

Viele Grüße
Thomas

**Comment by rphl** [comment]
> Beim Medium Widget könnte es vom Platz her sogar klappen, beide Werte anzuzeigen.

Finde es ist schon fasst zu viel im Widget. Beide werde werde ich wahrscheinlich nicht anzeigen. Muss aber mal überlegen...

Evtl. könnte man eine Konfiguration Option einfügen. Oder die absoluten Impfwerte umbauen/dafür entfernen.

**Comment by dennerforen** [comment]
Weiß nicht ob das machbar ist, aber da ja erstimpfung größer gleich zweitimpfung sein muss, könnte man die Anzahl der erstimpfungen rot darstellen und die zweitipfungen mit grün darüberliegende. Dann sieht man Rot für erstimpfung und kürzer grün für zweitipfung.

**Comment by rphl** [comment]
Widget zeigt jetzt Vollständig geimpft an.
