### ISSUE TITLE
Fehlende Tage im MediumWidget-Graph

### ISSUE THREAD

**Issue by ghost** [rphl/corona-widget#146]
Obwohl im SmallWidget alles in Ordnung ist werden im MediumWidget die letzten beiden Tage für das Bundesland und Deutschland im Graph nicht angezeigt. 
![graph](https://user-images.githubusercontent.com/83644343/116992956-18442f80-acd7-11eb-85b9-fc5c1dbc3e84.jpg)

**Comment by rphl** [comment]
Danke für die Info. Werde ich mal prüfen.

**Comment by h-0-r-u-s** [comment]
https://github.com/rphl/corona-widget/blob/e2429a9d30f0c51067c543f3c76d0ea6a9520e53/incidence.js#L531

Folgende Änderung hat bei mir geholfen: 
`let b2 = new UI(r).stack('v', false, false, false, false, [66, 30])`
