### ISSUE TITLE
Fixed Location automatisch ausblenden

### ISSUE THREAD

**Issue by lbrnds** [rphl/corona-widget#147]
Falls nur eine Location an zweiter Stelle gefixed ist, fände ich es gut wenn diese automatisch ausgeblendet wird, falls man sich innerhalb des selben Kreises befindet. Ich fixe z.B. Ingolstadt und sobald ich innerhalb von Ingolstadt bin zeigt es mir das automatisch so an als ob ich keinen Ort gefixed hätte.

Fände ich total cool um auf Reisen zu sehen wie es in der Heimat ist bzw. dann in der Heimat nicht immer den eigenen Kreis doppelt zu sehen.

**Comment by rphl** [comment]
Aktuell ist die Zeit etwas knapp. Aber ich versuche es mal einzuplanen.
