### ISSUE TITLE
Widget liefert falsche Zahl

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#148]
![image](https://user-images.githubusercontent.com/82751561/118271771-037b4f00-b4c2-11eb-87cc-d6dac71a3bd9.png)
![image](https://user-images.githubusercontent.com/82751561/118271803-0d9d4d80-b4c2-11eb-9fc0-6e5941722cdc.png)
![image](https://user-images.githubusercontent.com/82751561/118271824-17bf4c00-b4c2-11eb-90f0-f10d0c8af670.png)

**Comment by rphl** [comment]
Hallo. Ich kopiere mal meine Antwort von Heute zu "unterschiedlichen" Inzidenzen aus dem allgemeinen Ticket hier hinein:

> Wie in der Readme und oben im Ticket erklärt verwendet das Widget eine Live-Inzidenz. https://github.com/rphl/corona-widget#-quelledatenbasis
Das RKI stellt nur einen statischen Inzidenzwert für den Tag Bereit. D.h. auch wenn sich Meldezahlen ändern (was oft passiert), so ändert sich aber nicht die zuvor vom RKI gemeldete Inzidenz.
Das Widget verwendet die aktuellen Meldedaten vom RKI, d.h. die Inzidenz wird immer auf Basis der aktuellen Meldedaten zu Fallzahlen berechnet.

> Wenn du den statischen, oft ungenauen/veralteten Wert verwenden möchtest, so kannst du dies in der Konfiguration des Widgets einstellen. **disableLiveIncidence** auf **true** Siehe dazu auch den Abschnitt Konfiguration https://github.com/rphl/corona-widget#erweiterte-konfiguration

Du kannst dir auch alle berechneten Inzidenzen/Fallzahlen für die Tage anzeigen lassen. Dazu musst du in der Konfiguration `debugIncidenceCalc` auf `true` stellen. Auf der Scriptable Konsole kannst du dann alle sehen.

---

Warum bei dir +0 für Wiesbaden steht, müsste dir dein Gesundheitsamt erklären 🤷‍♂️. Denke aber das liegt an der RKI Api, hier heisst es abwarten.

**Comment by ragalthar** [comment]
Also ist dein Widget aktueller als die Anzeige beim RKI direkt, obwohl dein Widget die Daten aus der gleichen Quelle zieht? Demzufolge sind die 146 im Bild des Widgets aktueller als die 126 direkt beim RKI, verstehe ich dich da richtig? Ich dachte es sei umgekehrt und die Daten beim RKI aktueller.

**Comment by dennerforen** [comment]
Nein, Widget ist live (jede nach Meldung wird eingearbeitet) rki veröffentlicht nur 1 mal täglich und lasst die Zahl so. War ja gestern Thema bei der Tagesschau, das das rki immer zu niedrige Inzidenzen anzeigt.

**Comment by ragalthar** [comment]
Komisch nur, dass die Tage davor und danach die Werte für Wiesbaden im Widget und auf der RKI Seite immer übereinstimmten und sich die Werte im Widget den ganzen Tag über nicht geändert haben. Wie kann das sein, wenn das Widget sich öfter aktualisiert als die RKI Seite?

**Comment by cl4udiu5** [comment]
Bei mir ist es für LK Göppingen (48.70,9.65) auch ziemlich falsch die Anzeige. 
Egal ob ich Live Inzidenz an oder ausschalte. Im Moment liegt die Anzeige 20 über dem richtigen Wert. Jeden Tag stehen auch erst mal 0 Neuinfektionen da im Balkendiagramm und dann am nächsten Tag wieder aber der Balken zuvor ist dann trotzdem plötzlich rot geworden.

**Comment by cl4udiu5** [comment]
![DA99D4D4-56E8-48E9-9617-CFE6DF23C328](https://user-images.githubusercontent.com/74124378/119217722-52397200-badc-11eb-89e0-c6ba9ba07cdd.jpeg)

So sieht es gerade aktuell im LK Göppingen aus. Inzidenz um die 70.

**Comment by chimcen** [comment]
Servus,
habe leider für den Kreis Rottal-Inn das selbe Problem - widget sagt seit 2 Tagen 26,3, die Map des RKI seit Tagen 2,5…
0,49.31148,10.74321;1,48.2586244,12.9834021
![90923058-7EFA-4942-BE49-0783F3C9B5FE](https://user-images.githubusercontent.com/22658487/123330004-be751e80-d53d-11eb-8d68-f11b837b4314.jpeg)

**Comment by rphl** [comment]
@chimcen siehe #158
