### ISSUE TITLE
dark theme, black text on black background

### ISSUE THREAD

**Issue by just-doit** [rphl/corona-widget#152]
Setting the theme to "dark" while the setting in iOS is "light" will result in black text on dark grey background. 

![IMG_0424](https://user-images.githubusercontent.com/4004387/119796493-b3e14e00-bed9-11eb-930a-ef6d4ed20b52.jpeg)

The second image shows the correct result, when iOS is set to "dark" and the widget to automatic, which I would expect when dark theme is forced.
![IMG_0423](https://user-images.githubusercontent.com/4004387/119796684-de330b80-bed9-11eb-911b-62312076cb13.jpeg)

**Comment by wombart** [comment]
How can you enable the Diff row?

**Comment by just-doit** [comment]
> How can you enable the Diff row?

It is enabled by default, afaik. I've used the current code as is, no special config at all.

**Comment by wombart** [comment]
> 
> 
> > How can you enable the Diff row?
> 
> It is enabled by default, afaik. I've used the current code as is, no special config at all.

Thanks. Had a config.json setting which overrode this.

**Comment by chimcen** [comment]
Hab das gleiche Problem - iOS nutzt light mode und das widget is manuell auf dark gestellt.
Sieht dann aktuell so aus:
![A746A846-A97F-4A04-961E-20242BF26BA2](https://user-images.githubusercontent.com/22658487/142688806-350b01ff-4431-4659-8556-dd0e7f2d6122.jpeg)

**Comment by rphl** [comment]
Sollte im update gefixed sein
