### ISSUE TITLE
Hilfe zum einstellen

### ISSUE THREAD

**Issue by dottoremarkus** [rphl/corona-widget#153]
Hi ich bekomme immer nur die Fehlermeldung und weiß nicht wie ich das Script ans laufen bekomme 🤷🏻‍♂️ bin absoluter beginner mit scriptable ![image](https://user-images.githubusercontent.com/84927825/119873140-7eae1d80-bf24-11eb-8e6b-f51a097e9805.jpeg)
Hab schon ein anderes Script laufen und das lief ohne Probleme 

Dank und Gruß

**Comment by 1rNidiD** [comment]
Welche Parameter hast du eingestellt?
Oder hast du es ohne Parameter gemacht?
Hast du das komplette Script kopiert?

**Comment by dottoremarkus** [comment]
Hi. Parameter hab ich nicht eingestellt 🤷🏻‍♂️ hab es so verstanden, dass die für eine fixe Location sind - die soll gern flexibel bleiben. 
Was sollte ich denn eintragen ? 

Ich würde sagen ja ich habe es komplett kopiert. Hab es aus der scriptable app gezogen. 

Ok das mit dem kleinen Widget teste ich mal 

Danke 🤙🏼

**Comment by 1rNidiD** [comment]
Dort wo du das Script auswählst, welches angezeigt werden soll, könntest du Parameter einstellen wie deine Location, Impffortschritt usw. Das musst du nicht machen, das Widget funktioniert auch so, dann aber immer auf den Ort bezogen, wo du gerade bist. 

Wenn du das Medium Widget einstellst, könntest du dir auch die Daten vom aktuellen Ort und von einem weiteren festgelegten Ort anzeigen lassen. Was du genau eintragen musst, findest du alles in der Beschreibung.

LG Didi

**Comment by Eeewald85** [comment]
Eine Zeit lang hat das Script aus der Scriptable Gallery nicht funktioniert und ließ sich vom Programmierer auch nicht austauschen. Daher sollte man das Script direkt hier von Github kopieren und in Scriptable einfügen. Evtl. ist das immer noch so?

Kopier sonst einfach mal das Script direkt hier von Github.
