### ISSUE TITLE
Gelbe Inzidenz Zahl nicht lesbar

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#154]
![image](https://user-images.githubusercontent.com/82751561/120568197-b54bd280-c413-11eb-97c4-2afb6adea2c9.jpeg)

**Comment by ragalthar** [comment]
Man kann weder die Zahl lesen noch den gelben Balken, nur wenn man das Pic extrem vergrößert, was aber auf dem Homescreen nicht geht.

**Comment by fxhuhn** [comment]
Ich dachte schon es läge an meinem Augen.

**Comment by ragalthar** [comment]
Die Lösung des Problems kann aber nicht darin bestehen, dass man gezwungen wird, auf den dunklen Modus umzustellen. Es gibt eine Menge Apps, die gelbe Schrift auf weißem Grund darstellen und lesbar sind. Wenn ich die Zeit finde suche ich ein paar Hex-Werte der Farben heraus und präsentiere sie hier.

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/120752132-726c2680-c509-11eb-8eb4-32d41d0513b0.png)

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/120752232-9e87a780-c509-11eb-93dc-f698d7e105d8.jpeg)

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/120752642-5321c900-c50a-11eb-99cc-8395f3b6a268.jpeg)

**Comment by ragalthar** [comment]
Habe das Widget bei mir mal auf #ffd800 angepasst und das ist das Ergebnis:

![image](https://user-images.githubusercontent.com/82751561/120752996-d5aa8880-c50a-11eb-9c7c-c32d03443a1c.jpeg)

**Comment by rphl** [comment]
Lange Zeit die Farbe nicht gesehen...

@dersvenhesse Danke für den PR, habe es mal gemerged.
