### ISSUE TITLE
Anzeige der Inzidenzstufe

### ISSUE THREAD

**Issue by Frogy76** [rphl/corona-widget#156]
Hallo

wäre es möglich die aktuell gültige Inzidenzstufe (1/2/3) anzuzeigen?

Die Regel wäre

Für eine Verschärfung der Maßnahmen muss der Inzidenzwert in der Stadt oder im Kreis an drei Kalendertagen in Folge über der Grenze liegen. Die Verschärfung gilt dann ab dem übernächsten Tag.

Damit Maßnahmen gelockert werden und der Kreis oder die Stadt in eine "niedrigere" Stufe rutschen kann, muss der Inzidenzwert (z.B. 50) an fünf aufeinanderfolgenden Werktagen unterschritten werden. Gelockert wird zum übernächsten Tag.

Die Werte wären 35/50/100 

Die Verschärfung zu berechnen stelle ich mir leichter vor als die Entschärfung basierend auf den Werktagen.

Gruß

Bastian

**Comment by Reini2512** [comment]
https://gist.github.com/marcusraitner/a1b633625d1016498eaaab712461dfc4

**Comment by rphl** [comment]
Duplicate: #168
