### ISSUE TITLE
Widget funktioniert nicht

### ISSUE THREAD

**Issue by LeonardH21** [rphl/corona-widget#157]
Hallo rphl,

Das Widget funktioniert bei mir leider nicht. Habe ich dabei etwas falsch gemacht? Es kommt immer wieder folgende Meldung:![image](https://user-images.githubusercontent.com/78261940/121687381-93f97f00-cac2-11eb-9776-345fc0830e83.png), ich weiß aber nicht, welche ID ich in das WidgetParameter eintragen soll.

Grüße, Leonard

**Comment by rphl** [comment]
Sieht nach einer alten Version aus. Bitte neuste Version aus dem Repository hier verwenden.

**Comment by LeonardH21** [comment]
Ich habe aber bereits die neuste Version Installiert und es geht nicht

**Comment by rphl** [comment]
Siehe auch hier den Hinweis: https://github.com/rphl/corona-widget/issues/38 

Du Verwendest wahrscheinlich die Version aus der Scriptable Gallery, die ist nicht aktuell (Erkennbar an deinem Screenshot. Sowas wie CacheId gibt es schon länger nicht mehr)

Wie erwähnt,  die aktuelle Version aus dem Repo verwenden/kopieren. Dann wird es  funktionieren.
https://github.com/rphl/corona-widget/blob/master/incidence.js

**Comment by LeonardH21** [comment]
Danke für die schnelle Andwort. Grüße
