### ISSUE TITLE
Negative Inzidenz

### ISSUE THREAD

**Issue by EscolarProgramming** [rphl/corona-widget#158]
Eigentlich sind wir heute bei 4,9, beim Widget kommt aber eine negative Zahl raus

![37DBF74A-7A5F-4250-A50A-AB5A2A1D693A](https://user-images.githubusercontent.com/6965961/123055456-32141000-d406-11eb-80e6-03ce1e51032b.jpeg)

**Comment by EscolarProgramming** [comment]
Kleiner Nachtrag: In der Datei wird der Wert korrekt gespeichert ("cases7_per_100k":4.93819....), es wird also wohl nur bei der Anzeige falsch dargestellt.

**Comment by rphl** [comment]
Oh eine negative Inzidenz ist strange. Schaue ich mir mal an.

Wegen der Differenz habe ich schon einen verdacht. Die Annahme ist aktuell auch, dass bei "0" es noch keine Fälle gemeldet worden sind. Checke ich auch mal.

**Comment by EscolarProgramming** [comment]
Guten Morgen,
Heute ist die Zahl nicht mehr negativ, dafür viel zu hoch: Laut Widget hätten wir heute ne Inzidenz von 26,3, richtig wäre 2,5. In der Datei steht es korrekt drin, also wieder ein Anzeigefehler

Das bei keinen Fällen keine Daten per REST-API gemeldet werden, ist richtig, das ist mir auch schon aufgefallen. Könnte man ja dadurch fixen, dass einfach 0 angenommen wird, wenn keine Daten verfügbar sind

**Comment by rphl** [comment]
Es scheint das etwas mit den gemeldenten Zahlen in deinem Fall nicht stimmt: 

Wenn du in der Konfiguration `debugIncidenceCalc` auf `true` stellen könnest. Das wirst du beim Aufruf innerhalb Scriptable, auf der Konsole alle Inzidenzen/Fälle sehen. Wäre super wenn du die Ausgabe hier posten könntest.

**Comment by EscolarProgramming** [comment]
Na klar, hier hast du es: https://pastebin.com/WQu4WMqY

**Comment by rphl** [comment]
Danke. So wie ich das sehe ist die _26_ auf basis der gemeldenten Fälle "korrekt": 
Laut der RKI Api hat Rottal-Inn am 22.06.2021 **29** Fälle gemeldet. Was nun mal zu einer höheren Inzidenz führt.

Ich vermute aber einfach das es eine falsche Zahl sein könnte, die gemeldet worden ist (Genaue so wie bei der negativen Inzidenz, Wahrscheinlich zu hohe Korrekturen gemeldet)

```
2021-06-24 12:11:34: "calcIncidence" | "s0"
2021-06-24 12:11:34: "24.06.2021" | 0 | 26.3370150285592
2021-06-24 12:11:34: "23.06.2021" | 0 | 28.806110187486627
2021-06-24 12:11:34: "22.06.2021" | 29 | 6.5842537571398 <<<<<<<<<<
2021-06-24 12:11:34: "21.06.2021" | 1 | 6.5842537571398
2021-06-24 12:11:34: "20.06.2021" | 0 | 6.5842537571398
2021-06-24 12:11:34: "19.06.2021" | 0 | 8.23031719642475
2021-06-24 12:11:34: "18.06.2021" | 1 | 8.23031719642475
2021-06-24 12:11:34: "17.06.2021" | 1 | 12.345475794637125
2021-06-24 12:11:34: "16.06.2021" | 3 | 11.52244407499465
2021-06-24 12:11:34: "15.06.2021" | 2 | 15.637602673207025
2021-06-24 12:11:34: "14.06.2021" | 1 | 14.814570953564552
```

Falls die Meldungen der Fallzahlen in deiner Region nicht so Zuverlässig sind, kannst im Widget die "Live Berechnung" auch abstellen `disableLiveIncidence` auf `true` stellen, und den Statischen Inzidenz Wert vom RKI nutzen. 

Wie präzise/wahr dieser aber ist, hängt wieder herum von deiner Region ab. Die gemeldeten Fälle sagen nun mal **29** am 22.06

**Comment by EscolarProgramming** [comment]
Anscheinend hat das RKI die Zahlen nachträglich nochmal geändert, heute passt die Inzidenz wieder, und auch die 29 ist verschwunden. Aber warum berechnest du die Inzidenz eigentlich selbst, wenn in der jeweiligen Region-Config die richtige Inzidenzzahl sowieso steht?

Und danke für das Update der Differenz!

**Comment by rphl** [comment]
Das RKI stellt nur die Inzidenz für "heute" via API bereit. Um einen Trend darstellen zu können, benötigt man auch die anderen Tage. 

Das geht entweder durch caching der Inzidenz (Tag für Tag). Somit wäre aber der Trend/das Diagram auch erst nach 2Wochen verfügbar. Dies war so in der ersten Version des Widgets.

Oder man geht über die offiziellen Meldefälle. Diese können bis X Tage in die Vergangenheit abgerufen werden. Der Rest ist eine einfach Formel. Hier muss das RKI/Gesundheitsamt einfach sorgfältiger arbeiten, und nicht nur zB die Inzidenz für Region statisch korrigieren. Ohne die Daten im Hintergrund dafür zu fixen.
