### ISSUE TITLE
Der R-Wert wird nicht angezeigt

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#160]
![image](https://user-images.githubusercontent.com/82751561/124382732-417a3f80-dcc9-11eb-9bba-4d402443d6d7.jpeg)

Kein R-Wert

![image](https://user-images.githubusercontent.com/82751561/124382747-4fc85b80-dcc9-11eb-9310-a262f7c51254.jpeg)

Und hier die Parameter

**Comment by ragalthar** [comment]
Ist übrigens schon seit gestern so, hatte nur mit der Meldung gewartet, weil ich die Hoffnung hatte, dass es sich von selbst korrigiert.

**Comment by Ruppert76** [comment]
same here

**Comment by chimcen** [comment]
Da hat sicher das RKI wieder was am EcxelSheet geändert - Dass die‘s einfach nicht sein lassen können…

**Comment by rphl** [comment]
Ja haben sie leider. PR mit Änderung ist gemerged.

**Comment by chimcen** [comment]
Funktioniert bei mir leider immer noch nicht.
Hab auch schon alle json files in der cloud gelöscht - ohne Erfolg…

**Comment by dersvenhesse** [comment]
Für heute stehen in der entsprechenden Spalte der RKI-Tabelle auch noch keine Werte, sobald die befüllt sind sollte es mit der gestrigen Änderung (hoffentlich) funktionieren.
