### ISSUE TITLE
R Wert N/A

### ISSUE THREAD

**Issue by Teclini** [rphl/corona-widget#162]
R Wert wird nicht angezeigt.

**Comment by ragalthar** [comment]
Hier das Gleiche, selbst nach der Code-Korrektur von gestern Abend (siehe bereits geschlossene #160)

**Comment by rphl** [comment]
Das RKI hat wohl mehr als nur den Spaltennamen geändert. Neben eine neuen URL, hat sich das Format deutlich geändert.

Ein Update ist online.

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/124793682-8662d800-df4e-11eb-807e-ae28621ade91.jpeg)

Gestern Abend die Code-Korrektur eingespielt, scheint zu laufen. Danke!
