### ISSUE TITLE
0-Inzidenz

### ISSUE THREAD

**Issue by Metaxa7** [rphl/corona-widget#163]
Hallo. 0-Inzidenz wird nicht als 0 angezeigt, sondern als "n/v". Soll das so sein?

**Comment by rphl** [comment]
In welcher Region? Das macht es mir einfacher es zu korrigieren.

**Comment by Metaxa7** [comment]
Betrifft Coburg Stadt, Coburg Land

**Comment by rphl** [comment]
Habe ein Update online gestellt. Sollte also jetzt funktionieren.
