### ISSUE TITLE
Widget zeigt nur Text  Error in Line….. an

### ISSUE THREAD

**Issue by Sajin56** [rphl/corona-widget#164]
Seit 2 Tagen bekomme ich nur noch die Meldung: Error on line 768:37: TypeError: undefined is not an object (evaluating 'completeDataObj[curDate].cases = value.cases')
Wenn ich die betreffende Zeile lösche, zeigt das widget wieder was an, aber alle Inzidenzwerte werden auf Null gesetzt, also in meinem Fall Stadt/Landkreis/Bayern/Deutschland. Die Inzidenz in Bayern und Deutschland ist aber definitiv nicht Null.
Kann mir da jemand helfen, damit das wieder läuft?

Liebe Grüße,

Sajin56

**Comment by rphl** [comment]
Danke für die Info. Schaue es mir nachher an was das Problem sein könnte. Vermute etwas mit der RKI aber.

**Comment by Sajin56** [comment]
Vielen Dank. Finde das Widget absolut super und freue mich sehr, wenn es wieder funzt. Danke für die Arbeit, die du dir damit machst.

**Comment by rphl** [comment]
Hmm kann das Problem nicht reproduzieren. Bei mir zeigt es für Bayern alles korrekt an:

<img width="270" alt="Bildschirmfoto 2021-07-10 um 20 51 03" src="https://user-images.githubusercontent.com/97642/125173665-a0a3ec80-e1c0-11eb-9712-bebb3994e222.png">

Funktioniert es mit einem anderen Standort? Hast du Widgetparameter gesetzt?

**Comment by Sajin56** [comment]
Hallo Raphael,

So sieht das bei mir aus, sowohl auf meinem iPhone (IOS 14.7 beta5), das Foto ist iPad (auch 14.7 Beta5) und auf dem iPhone meiner Freundin mit IOS 14.6 (offizieller Release) sieht es seit dem 8.07. auch so aus.
Wenn ich diesen Teil: {
            let curDate = Format.dateStr(value.date)
            completeDataObj[curDate].cases = value.cases
        })
Rausnehme (Zeile 770 +- 3 Zeilen), dann wird das Widget wieder angezeigt, aber alle Inzidenzen gehen auf 0, wie ich schrieb, auch Bayern und Deutschland.

Hab den Code ganz normal (schon mehrfach) von der Webseite github kopiert.
Egal, ob ich Parameter setze (normal 0,48.88,12.54;1,48.91,12.68) für Landkreis Straubing-Bogen und Stadt Straubing, oder das rausnehme, kommt immer die Fehlermeldung.
Auch wenn ich andere Koordinaten wähle, z.B. Regensburg kommt die Meldung.
Ich hab auch keine Ahnung, woran das liegt, war ohne Änderung meinerseits von heute auf morgen so. Dachte auch, Fehler RKI API oder sonst was, geht bald wieder, war aber nicht so, es blieb.






Mit freundlichen Grüßen

Jürgen Schindele

Frauenbrünnlstr. 121
94315 Straubing
Tel.		09421-1898595
Fax		09421-960812
Mobil:	+49 170-2462260

**Comment by rphl** [comment]
Danke für die Info, kann jetzt den Fehler hier sehen. Checke es gerade.

PS: Habe mal deine Email Signatur (Name, Telefon & co) aus deinem Kommentar entfernt.

**Comment by Sajin56** [comment]
Danke, ich dachte, ich schreibe eine Mail an dich direkt. Wußte nicht, dass ich es hier poste.........
Danke dir.

**Comment by rphl** [comment]
Problem sollte jetzt im Widget gelöst sein. Das RKI meldet jedoch für deinen Standort keine Daten. 
Das Widget ignoriert es, und zeigt wieder die Daten aus dem Cache an ( Icon = ⚡️ )

![image](https://user-images.githubusercontent.com/97642/125174481-1d859500-e1c6-11eb-9728-2074c48589bd.png)

Sonst wird eine generelle Meldung angezeigt, bis Daten wieder vom RKI kommen.

<img width="269" alt="Bildschirmfoto 2021-07-10 um 21 26 36" src="https://user-images.githubusercontent.com/97642/125174450-eca56000-e1c5-11eb-9ec9-d43599a05caf.png">

**Comment by Sajin56** [comment]
Super, tut wieder wie es soll. Tausend Dank.👍

**Comment by Sajin56** [comment]
![image](https://user-images.githubusercontent.com/87224506/125174851-68081100-e1c8-11eb-8520-67e33bf2d12c.jpeg)

Zu früh gefreut, beim mir zeigt es überall 0 an, also auch Deutschland und Bayern, bei meiner Freundin geht es, da ist nur die Zahl für Bayern mit 14,x falsch, müßt bei 6,1 liegen.

**Comment by Sajin56** [comment]
Hab eben mal bei Parameter einen anderen Ort eingegeben, da wurden Zahlen für D und BAY angezeigt, nun wieder auf meine Einstellung geändert und nun ist es nicht mehr 0, scheint also alles wieder zu gehen.
Danke noch mal für die tolle Arbeit. Frage mich nur, warum das RKI für uns keine Zahlen liefert, evtl. Sind wir schon zu lange bei 0.....
