### ISSUE TITLE
"Kein Internet" Fehler trotz LTE

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#165]
![image](https://user-images.githubusercontent.com/82751561/127967699-162f50c8-dec8-4a16-870e-4506eb4e2d4f.jpeg)

Ein Bild sagt mehr als 1.000 Worte. Mein Fehler oder hat das Widget wieder mal Probleme, Daten vom RKI zu lesen?

**Comment by MacSteven** [comment]
Kann ich bestätigen. Dadurch werden auch Änderungen an den Geo-Koordinaten nicht umgesetzt.

**Comment by rphl** [comment]
Muss ich prüfen. Hier scheint es ein Problem mit der RKI Api zu geben.

**Comment by MacSteven** [comment]
Danke!

Gruß
Stephan

**Comment by MacSteven** [comment]
Geht bei mir heute morgen wieder...

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/128127424-4e0d71c4-2f01-4451-9a0c-7b96b72033de.jpeg)

Bei mir geht's heute auch wieder. Habe den Code nicht geändert.

**Comment by rphl** [comment]
Wie vermutet war es das RKI was keine Daten geliefert hat. 

⚡️ Bedeutet auch das keine Daten geladen werden konnte, was nicht immer kein Internet zur Grunde hat. Werde es mal in der Doku anpassen.
