### ISSUE TITLE
Corona Krankenhausampel für Bayern (Alle Bundesländer, Bundesweit)

### ISSUE THREAD

**Issue by apfelbasti** [rphl/corona-widget#168]
Seit dem 2. September gilt in Bayern die Krankenhausampel als Indikator. Es wäre super, wenn man die Ampel für Bayern einbauen könnte: https://www.stmgp.bayern.de/coronavirus/

**Comment by Larosen** [comment]
Das gilt nicht nur in Bayern, sondern in allen Bundesländern, nach und nach. Hier wäre eine generelle Anpassung wirklich spitze!

**Comment by matze276** [comment]
+1

**Comment by rphl** [comment]
Auch in #6 deswegen gefragt worden. Werde das mal einplanen. 

Muss noch zuvor checken welche API dafür verfügbar ist. Es muss Bundesweit + je Bundesland funktionieren. Nur für Bayern kann ich es nicht einbauen.

**Comment by icsAT** [comment]
Hallo Raphael, das RKI bietet hier passende Werte: https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv

Das Problem dabei ist allerdings, dass die Länder wohl auf Daten von IVENA zurückgreifen. Außerdem vermute ich hier zusätzlich auch wieder die bekannte Problematik, dass z.B. andere Einwohnerzahlen herangezogen werden. Kurz: Es wird vermutlich nicht gelingen die Werte der einzelnen Bundesländer identisch abzubilden.

Auch die Abbildung einer "Ampel" dürfte schwierig werden, da es diesbezüglich kein einheitliches Vorgehen der Länder gibt.
In Bayern z.B. wird die Anzahl der  COVID-19 Patienten auf Intensivstationen und teilweise die Anzahl der eingewiesenen COVID-19 Patienten in den letzten drei Tagen bewertet. 
In Niedersachsen ist die Hospitalisierungs-Inzidenz der Leitindikator. Weiter wird dort die Inzidenz der Neuinfektionen und der prozentuale Anteil der mit COVID-19 Patienten belegten Intensivbetten für die Bewertung der Lage beachtet.
In Hamburg hingegen spielt die Hospitalisierung wohl keine entscheidende Rolle. 
Um mal nur Beispiele aus drei Bundesländern zu nennen.
Von daher dürfte die Aufnahme bestimmter Zahlen richtig, der Anspruch einer allgemein gültigen Ampel aber sehr schwer zu realisieren sein.

**Comment by rphl** [comment]
Diese nicht einheitlichen Grenzen/Regeln sind in der Tat seeeeehr suboptimal. Ob sich das wirklich gut lösen lässt,  weiss ich noch nicht zu 100%. Habe jedoch mal angefangen die Daten aufzubereiten, um zu sehen was Abbildbar wäre. 

Hierzu werte ich die Daten vom **DIVI** (https://www.intensivregister.de/#/aktuelle-lage/downloads) aus, um die Belegung zu erhalten (https://diviexchange.blob.core.windows.net/%24web/zeitreihe-tagesdaten.csv)

Dazu werden noch die Hospitalisierungen ausgewertet (https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv)

---

Das ganze kann über Rudimäntäre API von mir abgerufen werden. (aktuell incl. ROH-Daten zum testen)
**DIVI / Hospitaliserungs API**: https://corona-its-api.vercel.app/api

Nächste Schritte:
- [ ] Regeln für die Warnstufen aufzulisten.
- [ ] Infos die Dargestellt werden sollen definieren (Ampel?, Bettenfrei? / BettenByCovid?)
- [ ] ...

---

**Regeln:**
Bayern:
* **Gelb**: > 450 `divi.bedsOccupiedByCovid `, 1200 > `hospitalization.7daysCases`
* **Rot**: > 600 `divi.bedsOccupiedByCovid `

....
    Berlin: ???
    Saarland: ???
    Baden-Württemberg: ???
    Schleswig-Holstein: ???
    Mecklenburg-Vorpommern: ???
    Sachsen-Anhalt: ???
    Hamburg: ???
    Brandenburg: ???
    Thüringen: ???
    Hessen: ???
    Rheinland-Pfalz: ???
    Bremen: ???
    Sachsen: ???
    Nordrhein-Westfalen: ???
    Niedersachsen: ???
...



---

**Comment by rphl** [comment]
Wäre nice wenn ihr mich bei der Regeln unterstützen würdet... Dauert sonst länger 😅

**Comment by Larosen** [comment]
> Diese nicht einheitlichen Grenzen/Regeln sind in der Tat seeeeehr suboptimal. Ob sich das wirklich gut lösen lässt,  weiss ich noch nicht zu 100%. Habe jedoch mal angefangen die Daten aufzubereiten, um zu sehen was Abbildbar wäre. 
> 
> 
> 
> Hierzu werte ich die Daten vom **DIVI** (https://www.intensivregister.de/#/aktuelle-lage/downloads) aus, um die Belegung zu erhalten (https://diviexchange.blob.core.windows.net/%24web/zeitreihe-tagesdaten.csv)
> 
> 
> 
> Dazu werden noch die Hospitalisierungen ausgewertet (https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv)
> 
> 
> 
> ---
> 
> 
> 
> Das ganze kann über Rudimäntäre API von mir abgerufen werden. (aktuell incl. ROH-Daten zum testen)
> 
> **DIVI / Hospitaliserungs API**: https://corona-its-api.vercel.app/api
> 
> 
> 
> Nächste Schritte:
> 
> - [ ] Regeln für die Warnstufen aufzulisten.
> 
> - [ ] Infos die Dargestellt werden sollen definieren (Ampel?, Bettenfrei? / BettenByCovid?)
> 
> - [ ] ...
> 
> 
> 
> ---
> 
> 
> 
> **Regeln:**
> 
> Bayern:
> 
> * **Gelb**: > 450 `divi.bedsOccupiedByCovid `, 1200 > `hospitalization.7daysCases`
> 
> * **Rot**: > 600 `divi.bedsOccupiedByCovid `
> 
> 
> 
> ....
> 
>     Berlin: ???
> 
>     Saarland: ???
> 
>     Baden-Württemberg: ???
> 
>     Schleswig-Holstein: ???
> 
>     Mecklenburg-Vorpommern: ???
> 
>     Sachsen-Anhalt: ???
> 
>     Hamburg: ???
> 
>     Brandenburg: ???
> 
>     Thüringen: ???
> 
>     Hessen: ???
> 
>     Rheinland-Pfalz: ???
> 
>     Bremen: ???
> 
>     Sachsen: ???
> 
>     Nordrhein-Westfalen: ???
> 
>     Niedersachsen: ???
> 
> ...
> 
> 
> 
> 
> 
> 
> 
> ---
> 
> 
> 
> 
> 
> 

Niedersachsen:

Indikatoren

Leitindikator (LI):
* Hospitalisierung (landesweite Kennzahl)

Indikatoren:
* Neuinfizierte (NI)(je Landkreis und kreisfreie Stadt)
* Intensivbetten (IB)(landesweite Kennzahl)

Warnstufe 1:
LI: >6 - <=8
NI: >35 - <=100
IB: >5% - <=10%

Warnstufe 2:
LI: >8 - <=11
NI: >100 - <=200
IB: >10% - <=20%

Warnstufe 3:
LI: >11
NI: >200
IB: >20%

Der Bedingung des Leitindikators muss erfüllt sein, sowie eine weitere um die nächst höhere Warnstufe auszulösen. 

Quelle: https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html

**Comment by icsAT** [comment]
Berlin:

Die Berliner Corona-Ampel berücksichtigt drei Indikatoren:
Neuinfektionen (Quelle: SurvNet)
Hospitalisierungen (Quelle: SurvNet)
Bettenbelegung (Quelle: IVENA)

Jeder Indikator kann unabhängig von den anderen beiden Indikatoren auf rot, gelb oder grün stehen. Der Status wird anhand von Schwellenwerten bestimmt, alle Werte beziehen sich hierbei ausschließlich auf Berlin.

Neuinfektionen pro 100.000 Einwohner:
Rot: über 100 pro Woche
Gelb: über 35 pro Woche
Grün: unter 35 pro Woche

Hospitalisierungen pro 100.000 Einwohner:
Rot: über 8 pro Woche
Gelb: über 4 pro Woche
Grün: unter 4 pro Woche

Bettenbelegung der Intensivstationen:
Rot: über 20 %
Gelb: über 5 %
Grün: unter 5 %

Der Gesamtstatus der Berliner Corona-Ampel wird aus den Ampeln der drei Indikatoren ermittelt.
Bei mindestens zwei roten Indikatoren schaltet die Ampel auf rot.
Bei mindestens zwei gelben Indikatoren schaltet die Ampel auf gelb.
Bei weniger als zwei gelben Indikatoren bleibt die Ampel grün

Quelle: https://www.corona-ampel-berlin.de/ und https://www.berlin.de/corona/lagebericht/

**Comment by icsAT** [comment]
Hamburg:

Mir ist für Hamburg aktuell keine "Ampel" oder irgend eine Art von Warnstufen bekannt.

Quelle: https://www.hamburg.de/corona-zahlen/

**Comment by icsAT** [comment]
Schleswig Holstein:

Auch hier scheint es keine Ampel oder Warnstufen zu geben.

Quelle: https://www.schleswig-holstein.de/DE/Schwerpunkte/Coronavirus/Zahlen/zahlen_node.html

**Comment by icsAT** [comment]
Mecklenburg-Vorpommern:

Die Ampel selbst hat die vier Stufen grün, gelb, orange und rot.
Das Ampelsystem setzt auf Ebene der Kreise und kreisfreien Städte an.

Leitkriterium:
7-Tage-Inzidenz Hospitalisierungendes Landkreises bzw. der kreisfreien Stadt

Gewichtungskriterien:
ITS-Auslastungdes Klinik-Clusters (Errechnet durch ITS-pflichtige COVID-19 Fälle pro 100 ITS-Betten für Erwachsene (Quelle: DIVI-Register).), dem der LK bzw. der SK angehört
7-Tage-Inzidenz Neuinfektionendes Landkreises bzw. der kreisfreien Stadt

Die Einstufung erfolgt anhand des Leitkriteriums und wird durch die Gewichtungskriterien um maximal eine Stufe angepasst.
Für eine Verschärfung der Maßnahmen muss die Einstufung für mind. 3 Tage konstant in einer höheren Stufe liegen.
Für eine Entlastung der Maßnahmen muss die Einstufung für mind. 5 Tage konstant in einer niedrigeren Stufe liegen.

Basisstufe Grün (Stufe 1):
7-Tage-Inzidenz Hospitalisierungen ≤ 5
ITS-Auslastung ≤ 5 %
7-Tage-Inzidenz Neuinfektionen ≤ 35

Warnstufe Gelb (Stufe 2):
7-Tage-Inzidenz Hospitalisierungen > 5 bis≤ 7
ITS-Auslastung > 5 % bis≤ 9 %
7-Tage-Inzidenz Neuinfektionen > 35 bis≤ 50

Warnstufe Orange (Stufe 3):
7-Tage-Inzidenz Hospitalisierungen > 7 bis≤ 11
ITS-Auslastung > 9 % bis≤ 15 %
7-Tage-Inzidenz Neuinfektionen > 50 bis≤ 200

Warnstufe Rot (Stufe 4):
7-Tage-Inzidenz Hospitalisierungen > 11
ITS-Auslastung > 15 %
7-Tage-Inzidenz Neuinfektionen > 200


Quelle: http://www.mv-corona.de/sites/default/files/2021-11/Risikogewichteter%20Stufenplan%20ab%2013.11.2021.pdf

**Comment by icsAT** [comment]
Bremen:

Warnstufe 0 gilt bei einer Hospitalisierungsinzidenz zwischen 0 und 3
Warnstufe 1 gilt bei einer Hospitalisierungsinzidenz zwischen 3 und 6
Warnstufe 2 gilt bei einer Hospitalisierungsinzidenz zwischen 6 und 12
Warnstufe 3 gilt bei einer Hospitalisierungsinzidenz über 12


Quelle: https://www.bremen.de/corona

**Comment by rphl** [comment]
- [ ] Lizenz des DIVI Registers & RKI Hospitalisierungen checken.

**Comment by MajorTomDE** [comment]
Wenn ich es korrekt verstanden habe, haben wir durch die heutige Ministerpräsidenten-Konferenz nun einen Standard bei der Hospitalisierungsrate: 3, 6 und 9

**Comment by rphl** [comment]
Das hat die Sache direkt deutlich klarer / einfacher gemacht. Im Update wäre die neue Deutschlandweite "Ampel" für Hospitalisierungen verfügbar:
<img width="268" alt="Bildschirmfoto 2021-11-18 um 21 40 07" src="https://user-images.githubusercontent.com/97642/142493960-3cc2c940-22ee-4bad-ac19-fddf0fc1f67c.png">
<img width="266" alt="Bildschirmfoto 2021-11-18 um 21 40 34" src="https://user-images.githubusercontent.com/97642/142493961-15294f2f-5808-471d-bdec-966b7a752701.png">
<img width="264" alt="Bildschirmfoto 2021-11-18 um 21 40 59" src="https://user-images.githubusercontent.com/97642/142493964-9dd85d87-79b2-41ae-ad98-a0c4429ac499.png">

**Comment by alexaecho** [comment]
Super cool, dass die Hospitalisierungsrate so schnell umgesetzt wurde 👍
Wäre es möglich nur die Ampelfarbe (ohne Zahl) auch im kleinen Widget für das Bundesland und Deutschland anzuzeigen? Um Platz zu schaffen könnte die Statistik gerne gekürzt werden.

**Comment by matze276** [comment]
Vielleicht konfigurierbar anstelle des R-Faktors oben links?

**Comment by MajorTomDE** [comment]
Bald haben wir soviel Kennzahlen, das wir ein Widget in "Large" brauchen. Wäre ich persönlich nicht ganz abgeneigt. Small und Medium wirkt teilweise ziemlich überladen.

**Comment by rphl** [comment]
So wird es im Small aussehen. Für mich passt es noch. ist aber das MAX!
![image](https://user-images.githubusercontent.com/97642/142626128-b63ca686-ff2a-4fbe-a6f8-6a919931e17e.png)

Evtl. werde ich den R Wert komplett entfernen... Hat sich in der Zeit nicht wirklich als guter Leitwert etabliert.

Habe keine Planung für ein LargeWidget. Würde wie erwähnt eher Infos entfernen. Wie z.B den R-Wert. 
Ist aber eine andere Todo (Ticket)

**Comment by rphl** [comment]
Update ist online... Bei Feedback Ticket wieder öffnen, oder neues erstellen.

**Comment by Larosen** [comment]
Mein Vorschlag wie man die Ampel beim Medium Widget mit 2 Landkreisen implementieren könnte: 
![76F960BC-5F5C-4EA4-B751-39B2EBB1354A](https://user-images.githubusercontent.com/66299704/142721862-4b50775c-b568-4591-8e41-9b093b911086.jpeg)
![51778CCC-4C75-4E7F-9A9E-48249F8CD64D](https://user-images.githubusercontent.com/66299704/142721865-d616abf2-e79e-4323-a4a0-aa169a5660e0.jpeg)

**Comment by alexaecho** [comment]
Beim small widget muss man den Parameter showDataInBlocks manuell auf hospitalization ändern damit die Ampel angezeigt wird. Ist das beabsichtigt? Eigentlich ist dieser Parameter ja für das medium widget.

**Comment by rphl** [comment]
@Larosen Die Ampel ist bereits im MediumWidget und 2 Standorten verfügbar.

So bleibt es noch übersichtlich. Wie zuvor erwähnt werde ich wahrscheinlich den R Wert konfigurierbar machen. Damit oben zB Impfungen/Ampel angezeigt/RWert wird.

 ![image](https://user-images.githubusercontent.com/97642/142727763-d93db61b-a287-4bb3-8969-c45f1d51081a.jpeg)

**Comment by rphl** [comment]
> Beim small widget muss man den Parameter showDataInBlocks manuell auf hospitalization ändern damit die Ampel angezeigt wird. Ist das beabsichtigt? Eigentlich ist dieser Parameter ja für das medium widget.

Habe die Parameter etwas angepasst, die Doku aber nicht komplett angepasst. Wie von dir erwähnt zeigt `showDataInBlocks` = `hospitalization` diese auch im SmallWidget an. Vaccine wird weiterhin nur im Medium angezeigt.

**Comment by Larosen** [comment]
> @Larosen Die Ampel ist bereits im MediumWidget und 2 Standorten verfügbar.
> 
> So bleibt es noch übersichtlich. Wie zuvor erwähnt werde ich wahrscheinlich den R Wert konfigurierbar machen. Damit oben zB Impfungen/Ampel angezeigt/RWert wird.
> 
>  ![image](https://user-images.githubusercontent.com/97642/142727763-d93db61b-a287-4bb3-8969-c45f1d51081a.jpeg)

Danke für die Antwort, dann liegt der Fehler wohl bei mir! Wie genau muss das config.json aussehen, damit die Anzeige so wie bei dir aussieht? Meins sieht bisher so aus und es funktioniert nicht. 
![image](https://user-images.githubusercontent.com/66299704/142730076-084593a5-27f5-46d7-afe9-14439daeefd5.png)

**Comment by rphl** [comment]
@Larosen Es fehlen nur die Anführungszeichen. Dann sollte es funktionieren.

{
"showDataInBlocks": "hospitalization"
}
