### ISSUE TITLE
Trendpfeil neben Inzidenzwert für den Landkreis zeigt nach oben, obwohl der Wert zu gestern gleich geblieben ist

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#17]
Hi. 
Der Trendpfeil neben Inzidenzwert für Landkreis zeigt nach oben, obwohl der Wert zu gestern gleich geblieben ist. 
Kann das sein?
Anbei das json. 
Danke

{"26.10.2020":{"incidence":58.6,"incidenceBL":87.2,"areaName":"Erding","areaCases":1021,"nameBL":"BY","shouldCache":true,"updated":"26.10.2020, 00:00 Uhr","incidencePerState":[{"BL":"SH","incidence":36.332041106519,"cases":6777},{"BL":"HH","incidence":74.8137910724736,"cases":11514},{"BL":"NI","incidence":51.3785514626186,"cases":30476},{"BL":"HB","incidence":121.25624998165,"cases":4407},{"BL":"NRW","incidence":104.796168721609,"cases":110516},{"BL":"HE","incidence":108.983982392082,"cases":32852},{"BL":"RP","incidence":65.3654959582579,"cases":16549},{"BL":"BW","incidence":80.5196644371362,"cases":69601},{"BL":"BY","incidence":87.2169857575051,"cases":91569},{"BL":"SL","incidence":91.2971799202948,"cases":5321},{"BL":"BE","incidence":122.605560280704,"cases":26094},{"BL":"BB","incidence":35.568519362241,"cases":6515},{"BL":"MV","incidence":28.0448568468626,"cases":2165},{"BL":"SN","incidence":71.2185818612166,"cases":13653},{"BL":"ST","incidence":30.5725124408711,"cases":3994},{"BL":"TH","incidence":42.6084828848896,"cases":5863}],"averageIncidence":72,"cases":8685},"27.10.2020":{"incidence":73.8,"incidenceBL":92.2,"areaName":"Erding","areaCases":1052,"nameBL":"BY","shouldCache":true,"updated":"27.10.2020, 00:00 Uhr","incidencePerState":[{"BL":"SH","incidence":36.6075447357627,"cases":6942},{"BL":"HH","incidence":83.6918386382374,"cases":11853},{"BL":"NI","incidence":53.9931405192749,"cases":31038},{"BL":"HB","incidence":126.834624678142,"cases":4495},{"BL":"NRW","incidence":116.83145819623,"cases":114194},{"BL":"HE","incidence":119.464128955102,"cases":34200},{"BL":"RP","incidence":72.2782147012277,"cases":17090},{"BL":"BW","incidence":84.5465485279171,"cases":70792},{"BL":"BY","incidence":92.1618467478625,"cases":93290},{"BL":"SL","incidence":99.9101214222094,"cases":5455},{"BL":"BE","incidence":126.693320681261,"cases":27024},{"BL":"BB","incidence":34.2996312690507,"cases":6599},{"BL":"MV","incidence":29.2885312081426,"cases":2200},{"BL":"SN","incidence":72.7657441568223,"cases":14001},{"BL":"ST","incidence":34.4908970458114,"cases":4166},{"BL":"TH","incidence":43.1240970892172,"cases":5936}],"averageIncidence":76.7,"cases":11409},"28.10.2020":{"incidence":82.5,"incidenceBL":105,"areaName":"Erding","areaCases":1075,"nameBL":"BY","shouldCache":true,"updated":"28.10.2020, 00:00 Uhr","incidencePerState":[{"BL":"SH","incidence":41.8076757377385,"cases":7218},{"BL":"HH","incidence":87.6977869301065,"cases":12153},{"BL":"NI","incidence":61.7743577118117,"cases":32244},{"BL":"HB","incidence":142.982551431147,"cases":4689},{"BL":"NRW","incidence":121.768155638135,"cases":117278},{"BL":"HE","incidence":129.180926451317,"cases":35688},{"BL":"RP","incidence":80.3145555720299,"cases":17789},{"BL":"BW","incidence":91.1138829846941,"cases":72884},{"BL":"BY","incidence":104.962103240621,"cases":96420},{"BL":"SL","incidence":96.8702597156513,"cases":5576},{"BL":"BE","incidence":130.50856372178,"cases":28064},{"BL":"BB","incidence":40.2475442058803,"cases":6957},{"BL":"MV","incidence":31.2784101861905,"cases":2328},{"BL":"SN","incidence":68.3452804550917,"cases":14409},{"BL":"ST","incidence":39.5939095545708,"cases":4342},{"BL":"TH","incidence":50.0614518383521,"cases":6200}],"averageIncidence":82.4,"cases":14964},"29.10.2020":{"incidence":87.6,"incidenceBL":107.8,"areaName":"Erding","areaCases":1109,"nameBL":"BY","shouldCache":true,"updated":"29.10.2020, 00:00 Uhr","incidencePerState":[{"BL":"SH","incidence":45.9746681300501,"cases":7499},{"BL":"HH","incidence":92.4616173312481,"cases":12557},{"BL":"NI","incidence":60.448298190254,"cases":32980},{"BL":"HB","incidence":152.230909480595,"cases":4891},{"BL":"NRW","incidence":131.524540763163,"cases":122051},{"BL":"HE","incidence":137.005254386077,"cases":37385},{"BL":"RP","incidence":82.7083592356731,"cases":18420},{"BL":"BW","incidence":95.9245230394525,"cases":75164},{"BL":"BY","incidence":107.758349748265,"cases":98998},{"BL":"SL","incidence":101.227394828385,"cases":5806},{"BL":"BE","incidence":139.801405699047,"cases":29225},{"BL":"BB","incidence":42.9042786509975,"cases":7208},{"BL":"MV","incidence":35.9421890409903,"cases":2484},{"BL":"SN","incidence":78.1685331256043,"cases":15380},{"BL":"ST","incidence":43.1933558777136,"cases":4582},{"BL":"TH","incidence":51.233302302733,"cases":6383}],"averageIncidence":87.4,"cases":7229},"30.10.2020":{"incidence":102,"incidenceBL":114.1,"areaName":"Erding","areaCases":1146,"nameBL":"BY","shouldCache":true,"updated":"30.10.2020, 00:00 Uhr","incidencePerState":[{"BL":"SH","incidence":46.1468578983275,"cases":7716},{"BL":"HH","incidence":93.3819027496504,"cases":12947},{"BL":"NI","incidence":64.4264767549272,"cases":34228},{"BL":"HB","incidence":160.304872857097,"cases":5100},{"BL":"NRW","incidence":139.960387181949,"cases":127447},{"BL":"HE","incidence":145.751962443226,"cases":39093},{"BL":"RP","incidence":85.9815193471853,"cases":19108},{"BL":"BW","incidence":99.0955816523269,"cases":77477},{"BL":"BY","incidence":114.074666791418,"cases":102074},{"BL":"SL","incidence":116.528032084727,"cases":6142},{"BL":"BE","incidence":146.096556715904,"cases":30356},{"BL":"BB","incidence":43.2611534272073,"cases":7468},{"BL":"MV","incidence":37.8698843009742,"cases":2616},{"BL":"SN","incidence":89.9318781985432,"cases":16493},{"BL":"ST","incidence":49.6176841253482,"cases":4804},{"BL":"TH","incidence":54.8426017330262,"cases":6625}],"averageIncidence":93,"cases":18681},"31.10.2020":{"incidence":110,"incidenceBL":118.5,"areaName":"Erding","areaCases":1177,"nameBL":"BY","shouldCache":true,"updated":"31.10.2020, 00:00 Uhr","incidencePerState":[{"BL":"SH","incidence":50.1416605223618,"cases":8028},{"BL":"HH","incidence":92.9488272586376,"cases":13357},{"BL":"NI","incidence":76.2859524760283,"cases":35942},{"BL":"HB","incidence":175.71880293951,"cases":5331},{"BL":"NRW","incidence":146.574224499715,"cases":132479},{"BL":"HE","incidence":150.968181066399,"cases":40998},{"BL":"RP","incidence":96.6070764256017,"cases":20103},{"BL":"BW","incidence":106.572793722457,"cases":80233},{"BL":"BY","incidence":118.501422161831,"cases":104764},{"BL":"SL","incidence":105.483201217566,"cases":6249},{"BL":"BE","incidence":150.238820588469,"cases":31440},{"BL":"BB","incidence":48.8918443407393,"cases":7831},{"BL":"MV","incidence":42.9067654641579,"cases":2782},{"BL":"SN","incidence":92.4859238928764,"cases":17196},{"BL":"ST","incidence":50.4378111356845,"cases":5067},{"BL":"TH","incidence":60.7018540549307,"cases":6953}],"averageIncidence":97.8,"cases":19059,"r":1.19,"blockPosition":1},"01.11.2020":{"incidence":110,"incidenceBL":123.2,"areaName":"Erding","areaCases":1177,"nameBL":"BY","shouldCache":true,"updated":"01.11.2020, 00:00 Uhr","incidencePerState":[{"BL":"SH","incidence":53.8609595171523,"cases":8293},{"BL":"HH","incidence":100.744186096869,"cases":13753},{"BL":"NI","incidence":78.3125717448241,"cases":36949},{"BL":"HB","incidence":176.746398278337,"cases":5522},{"BL":"NRW","incidence":147.265139265851,"cases":136116},{"BL":"HE","incidence":148.868971132683,"cases":42072},{"BL":"RP","incidence":96.9734749455471,"cases":20574},{"BL":"BW","incidence":113.374354099503,"cases":82334},{"BL":"BY","incidence":123.240564744269,"cases":107044},{"BL":"SL","incidence":143.177486378886,"cases":6740},{"BL":"BE","incidence":164.191709422369,"cases":32231},{"BL":"BB","incidence":52.857119631959,"cases":8088},{"BL":"MV","incidence":43.9638886712459,"cases":2865},{"BL":"SN","incidence":97.0046201213123,"cases":17974},{"BL":"ST","incidence":53.0348800017496,"cases":5204},{"BL":"TH","incidence":61.4049643335593,"cases":7171}],"averageIncidence":103.4,"cases":14177,"r":1.19,"blockPosition":0}}

**Comment by TheSpirit** [comment]
Hängt vermutlich mit issue #18 zusammen

**Comment by rphl** [comment]
Ich mache mal das Ticket hier zu. Da das Problem mit #18 #19 zusammenhängt, und bereits gefixed ist.

Gerne wieder öffnen wenn problem besteht
