### ISSUE TITLE
Standortdaten konnten nicht geladen werden

### ISSUE THREAD

**Issue by regetskcob** [rphl/corona-widget#170]
Nachdem ich - nach Monaten - das Script aktualisiert habe, kann es keine Daten mehr für meinen Standort liefern/anzeigen.

![1E8582DC-EB1D-44FE-9127-F2CA3B61968F](https://user-images.githubusercontent.com/52231719/132809644-da686ca6-4fbc-46ad-a666-1686f73d3717.png)

Hat jemand eine Lösung für mich?

**Comment by yanham** [comment]
Ich habe das selbe Problem

**Comment by rphl** [comment]
Seit gestern hat das RKI nach Monaten wieder etwas an der API gedreht. Der Fehler wurde bereits gemeldet. Ich checke es sobald ich kann. Schliesse deswegen das Ticket als Duplikat. Siehe: #169
