### ISSUE TITLE
Wallpaper Pfad wird nicht genommen

### ISSUE THREAD

**Issue by Xeferis** [rphl/corona-widget#171]
Hi Rphl, 

ich wollte in der aktuellsten Version ein Wallpaper als Hintergrund setzen. Leider sagt er jedes mal Pfad invalid. Ich hab versucht selbst die Zuweisungen zu schreiben. Hat aber leider nicht geklappt. Hättest du ne Hilfestellung wie ich win Bild aus der Fotomediathek oder dem iCloud Ordner qo du auch die config.js abfragst benutzen kann ?

**Comment by rphl** [comment]
Hello. Du muss eine URL zum Bild Hinterlegen. Thema hatten wir schon mal https://github.com/rphl/corona-widget/issues/141#issuecomment-820553242


```
{
    "theme": "dark",
    "themes": {
         "dark": {
            "mainBackgroundImageURL": "https://picsum.photos/600/300"
        }
    }
}
```

**Comment by Xeferis** [comment]
Hi, 

ja das war für meinen Zweck nicht ganz Optimal. Hab es jetzt umgebaut das auch iCloud Ordnerpfade bei mir klappen: 

        if (Theme.getCurrentTheme() === 'light' || Theme.getCurrentTheme() === 'dark') {
            const backgroundImageUrl = ENV.themes[Theme.getCurrentTheme()]['mainBackgroundImageURL']
            //BackupUrl
            let BackUpUrl = fm.documentsDirectory() + "/coronaWidgetNext/image.jpg"
            Helper.log (BackUpUrl)
            if (backgroundImageUrl!== '') {
                //const i = await new Request(backgroundImageUrl);
                //const img = await i.loadImage();
                this.widget.backgroundImage = fm.readImage(backgroundImageUrl)//img
            }
        }

lediglich den i cloud fm musste ich am ende noch zusätzlich deklarieren, da ich keinen von dir verwenden wollte. 

let fm = FileManager.iCloud()

Mit freundlichen Grüßen Flo

**Comment by rphl** [comment]
👍 Via `cfm.fm` kannst du auch iCloud zugreifen (Funktioniert auch ohne iCloud) 

Falls du eine Lösung hast, die nicht Hardcoded ist, erstelle gern ein PR. Dann könnte man das direkt ins Widget übernehmen.
