### ISSUE TITLE
Inzidenzen über 1000 werden abgeschnitten 

### ISSUE THREAD

**Issue by EscolarProgramming** [rphl/corona-widget#172]
Wir haben seit heute im LK Rottal-Inn das „Glück“, als erster Landkreis die 1000er Marke überschritten zu haben. Leider spielt da das Widget nicht ganz mit. Als Inzidenz wird nur „1…“ angezeigt. Es wäre cool, wenn z.B. die Schriftgröße verkleinert wird, damit der volle Wert angezeigt werden kann

**Comment by rphl** [comment]
Hmm, uncool. Ich versuche es heute anzupassen.

**Comment by EscolarProgramming** [comment]
Dankeschön! Es würde reichen, in Zeile 380 die Schriftgröße auf 19 abzuändern. Damit kann die volle Inzidenz wieder angezeigt werden

**Comment by rphl** [comment]
Danke. Schrift 19 nur ab 1000, sonst ist es für die anderen zu klein ;-) Habe mal ein Update online gestellt.
