### ISSUE TITLE
Landkreise mit 1.000er Inzidenz

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#173]
Es gibt mittlerweile Landkreise mir über 1.000 Inzidenz, da wird in den Widgets aber die Zahl nicht richtig angezeigt (siehe Screenshot)

![image](https://user-images.githubusercontent.com/82751561/142055003-c0966f0e-a136-49fb-86d4-4623881fefb1.jpeg)
![image](https://user-images.githubusercontent.com/82751561/142055029-7fc4f485-ea53-4b24-9cf5-9b7e7f96ec4c.jpeg)

Die Koordinaten siehst du hier...
![image](https://user-images.githubusercontent.com/82751561/142055077-fa690e87-a64d-45d1-988c-75ce2ef792f3.png)

Da das RKI zwei neue Farben für Inzidenzen über 500 (Pink #D90183) und 1.000 (Lila #780175) hinzugefügt hat, habe ich mein Widget mal angepasst. Vielleicht kannst du das auch updaten?

**Comment by rphl** [comment]
https://github.com/rphl/corona-widget/issues/172

Wurde bereits korrigiert. Bitte neuste Version verwenden.

**Comment by ragalthar** [comment]
Danke, werde es gleich al updaten. Sind da auch die neuen Farben drin?

**Comment by rphl** [comment]
Das mit dem Farben wäre eine Überlegung wert. 

Wobei ob nun dunkel rot oder lila ist, macht den Käse auch nicht mehr fett xD

Habe mal die Farben eingebaut...

**Comment by ragalthar** [comment]
Musst du nicht noch Zeilen 1190 bis 1195 ergänzen?

class Helper {
    static getIncidenceLimits(incidence) {
        if (incidence >= ENV.incidenceColors.green.limit && incidence < ENV.incidenceColors.yellow.limit) {
            return { min: ENV.incidenceColors.green.limit, max: ENV.incidenceColors.yellow.limit }
        } else if (incidence >= ENV.incidenceColors.yellow.limit && incidence < ENV.incidenceColors.orange.limit) {
            return { min: ENV.incidenceColors.red.limit, max: ENV.incidenceColors.darkred.limit }
        } else if (incidence >= ENV.incidenceColors.orange.limit && incidence < ENV.incidenceColors.red.limit) {
            return { min: ENV.incidenceColors.red.limit, max: ENV.incidenceColors.darkred.limit }
        } else if (incidence >= ENV.incidenceColors.red.limit && incidence < ENV.incidenceColors.darkred.limit) {
            return { min: ENV.incidenceColors.red.limit, max: ENV.incidenceColors.darkred.limit }
        } else if (incidence >= ENV.incidenceColors.darkred.limit && incidence < ENV.incidenceColors.darkdarkred.limit) {
            return { min: ENV.incidenceColors.darkred.limit, max: ENV.incidenceColors.darkdarkred.limit }
        } else if (incidence >= ENV.incidenceColors.darkdarkred.limit && incidence < ENV.incidenceColors.pink.limit) {
            return { min: ENV.incidenceColors.darkdarkred.limit, max: ENV.incidenceColors.pink.limit }
        } else if (incidence >= ENV.incidenceColors.pink.limit && incidence < ENV.incidenceColors.lila.limit) {
            return { min: ENV.incidenceColors.pink.limit, max: ENV.incidenceColors.lila.limit }
        } else if (incidence > ENV.incidenceColors.lila.limit) {
            return { min: ENV.incidenceColors.lila.limit, max: 2500 }
        }
        return { min: 0, max: 0 }
    }
