### ISSUE TITLE
Musst du nicht noch Zeilen 1190 bis 1195 ergänzen?

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#174]
Musst du nicht noch Zeilen 1190 bis 1195 ergänzen?

```
       } else if (incidence >= ENV.incidenceColors.darkdarkred.limit && incidence < ENV.incidenceColors.pink.limit) {
            return { min: ENV.incidenceColors.darkdarkred.limit, max: ENV.incidenceColors.pink.limit }
        } else if (incidence >= ENV.incidenceColors.pink.limit && incidence < ENV.incidenceColors.lila.limit) {
            return { min: ENV.incidenceColors.pink.limit, max: ENV.incidenceColors.lila.limit }
        } else if (incidence > ENV.incidenceColors.lila.limit) {
            return { min: ENV.incidenceColors.lila.limit, max: 2500 }
```

__Originally posted by @ragalthar in https://github.com/rphl/corona-widget/issues/173#issuecomment-974660236__

**Comment by ragalthar** [comment]
Es geht um die Farben Pink und Lila bei 500er und 1000 Inzidenzen. 

Sorry, wenn ich hier einen neuen Fall aufgemacht habe, aber ich habe keine Möglichkeit gefunden, einen geschlossenen Fall wieder zu öffnen.

**Comment by rphl** [comment]
Danke für den Hinweis, aber die Funktion wird nicht mehr verwendet. War mal für irgendwas geplannt... 🤔. Farben werden via `getIncidenceColor()` festgelegt.
