### ISSUE TITLE
Inzidenz größer 1000 wird abgeschnitten

### ISSUE THREAD

**Issue by OliverH77** [rphl/corona-widget#175]
Seit heute ist die Inzidenz in meinem Landkreis größer 1000 und im Widget wird jetzt nur noch "1...." angezeigt.
Wie kann man die Schriftgrößer verkleinern damit ein Wert größer 1000 wieder hinpasst?

Edit: Sorry, nicht gesehen das es dazu schon ein Update gab. ^_^

**Comment by rphl** [comment]
#172
