### ISSUE TITLE
Das Script zieht falsche Werte

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#176]
Die Koordinaten für Wiesbaden lauten 50.08 und 8.24

![image](https://user-images.githubusercontent.com/82751561/143189570-9568b85c-ed06-4762-a80d-66db49521cb2.jpeg)

![image](https://user-images.githubusercontent.com/82751561/143189605-7c9bb1a5-c4bd-4167-9ab2-a7051c91f379.png)

**Comment by icsAT** [comment]
Ich glaube nicht, dass das Skript "falsche" Werte zieht. In diesem Skript werden die Live-Werte Verwendet.
Es wird also nicht die über die RKI API gemeldete Inzidenz mit Stand 0:00 Uhr verwendet, sondern die Inzidenz wird auf Basis der aktuell gemeldeten und nachgemeldeten Fälle der letzten 7 Tage berechnet. 
Aktuell scheint es beim RKI eine Unschärfe in den Meldungen zu geben oder gegeben zu haben. 
Üblicher Weise wird das im Laufe des Tages wieder richtig gestellt. 
Spätestens morgen sollte es wohl wieder passen. Betroffen scheinen übrigens viele (alle?) Landkreise zu sein.

**Comment by icsAT** [comment]
Als Workaround kannst Du aber auch folgenden Parameter setzen:
![image](https://user-images.githubusercontent.com/74063738/143195396-3f9d2ae3-8f5f-4834-a1e4-e59ed6c2770a.jpeg)

**Comment by icsAT** [comment]
Ganz aktuell meldet die RKI API Fehler 499 Token required. Spätestens damit dürften dann jetzt alle Widgets, die auf der RKI API basieren aktuell ein Problem haben und einen Fehler oder die zuletzt ermittelten Werte anzeigen.

**Comment by icsAT** [comment]
Bei mir läuft es wieder;-)

**Comment by ragalthar** [comment]
Bei mir auch

![image](https://user-images.githubusercontent.com/82751561/143228642-0fd671fe-5d89-44b4-ba32-e09d65834047.jpeg)

**Comment by rphl** [comment]
Wie schon von @icsAT wars es die Rki-Api. Da es wieder läuft mache ich hier mal zu.
