### ISSUE TITLE
Hospitalisierung Landkreis

### ISSUE THREAD

**Issue by ldiekmann** [rphl/corona-widget#178]
Hallo,
vielen Dank für das Mega Script.
Ist es möglich, die Hospitalisierung auch für den Landkreis anzuzeigen? Ich bekomme es nur für das Bundesland und Deutschland hin.

Vielen Dank im Voraus.
Gruß Lars

**Comment by rphl** [comment]
Bietet das RKI nicht an, siehe: https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/issues/2
