### ISSUE TITLE
Fehlendes GPS Signal beim Corona Widget

### ISSUE THREAD

**Issue by LancerII** [rphl/corona-widget#179]
Hi rphl, 

Vorab ein Herzlichen Dank für Deine unermüdliche Arbeit….👏🏻

Mein Problem stellt sich seit einigen Tagen wie folgt dar. 

Ich habe zwei Widgets, welche auf das selbe Script zugreifen.
Dazu haben ich in einem Widget (KS Dortmund), in den Parametern, die GEO Daten eingetragen, bei dem Widget für Wuppertal ist es leer, das es die lokalen Daten nehmen soll. 
Nun verliert das Widget für Wuppertal immer das GPS Signal, egal ob auf dem iPad oder iPhone, das andere aber nicht. Klicke ich aber das Widget mit dem fehlendem Signal an, startet Scriptable, läd das Script und das GPS ist wieder da. Dies geht aber nach einer geraumen Zeit wieder verloren. 

Hierzu habe ich die Tage bereits manuell das Script von der Seite kopiert, aber es hatte keinen Erfolg. 

![8E2529BA-5C4E-4109-A139-D8BAC6F62F6B](https://user-images.githubusercontent.com/77447889/144324012-92b5daee-2f2c-424f-b635-2424ab49625e.jpeg)

Hast Du eine Idee, was dass verursachen könnte….

Esten Gruß

**Comment by rphl** [comment]
Hmm, mal versucht die Dateien aus dem Cache zu löschen? (icloud/Scriptable/CoronaWidgetNext/...)

Kommt die GPS-Meldung auch wenn nur das eine Widget verwendet wird?

**Comment by rphl** [comment]
Was ist wenn du beide Standort in einem Widget nur verwendest? Also GEO + Statisch?

**Comment by LancerII** [comment]
Leider haben deine Vorschläge keinen Erfolg gebracht. Die Uhrzeit im Widget wird aktualisiert und die Fehlermeldung über das GPS wird angezeigt. Auch wenn die beiden in einem Fenster zusammengefügt sind und ich Scrolle.

**Comment by LancerII** [comment]
@rphl Moin….

Ich glaube dich beim letzten mal missverstanden zu haben und habe dann auch noch versehentlich den Chat geschlossen🙈

Hier habe ich aber mal dass Widget so erstellt, wie Du es gemeint hattest. 

Das kuriose daran ist, dass wenn sich das Script aktualisiert, auch dass GPS wieder da ist…

![BECE1765-1CDA-48CB-981E-D35AE0AB4F17](https://user-images.githubusercontent.com/77447889/145191713-0c3bde14-8f44-48b6-990b-8877b3780970.jpeg)

**Comment by jot-we** [comment]
Hallo,

ich kann das beschriebene Verhalten bestätigen. Ich habe die Standorte ebenfalls als GEO + Statisch konfiguriert. Nach einer manuellen Aktualisierung über Scriptable funktioniert wieder alles normal.
