### ISSUE TITLE
API Impfquote

### ISSUE THREAD

**Issue by mikomedia** [rphl/corona-widget#180]
Hey! :)
Ich habe bemerkt, dass die Impfquoten (local und bundesweit) stark von den Werten des RKI abweichen. 
Die Ursache könnte sein, dass das RKI in der https://rki-vaccination-data.vercel.app/api auf die neue URL /v2 verweist. 

Ganz naiv habe ich die URL im Script erweitert und auch die Variable von 2nd_vaccination auf secondDoses geändert, aber das scheint nicht alles zu sein denn damit funktioniert es nicht. 

Da muss der Fachmann ran 😬
Wenn Du Zeit hast würde ich mich über eine Anpassung freuen! 
Viele Grüße

**Comment by rphl** [comment]
Sollte jetzt wieder passen. Ein Update ist online. 

![image](https://user-images.githubusercontent.com/97642/147373168-6542923a-7c56-488b-9e6c-47c884427a58.png)

**Comment by mikomedia** [comment]
Wow und das sogar am Heiligen Abend 👍🏼
Funktioniert wieder wunderbar. 
Vielen Dank und Frohe Weihnachten!
