### ISSUE TITLE
SyntaxError: JSON Parse error: Property name must be a string literal

### ISSUE THREAD

**Issue by pin00b** [rphl/corona-widget#181]
wie im Titel zu lesen, es gibt einen durch erneutes copy&paste der aktuellsten Scriptversion nich zu behebenden  konstanten JSON parse error... Ideen zur Abhilfe? Thx

<img width="296" alt="Bildschirmfoto 2022-01-11 um 17 59 55" src="https://user-images.githubusercontent.com/61549899/148988644-db73fe73-d547-493c-b8da-998f911d5f18.png">

**Comment by rphl** [comment]
Kann das Problem nicht reproduzieren. Copy&Paste von der neusten Version (https://raw.githubusercontent.com/rphl/corona-widget/master/incidence.js) funktioniert problemlos (iOS, iPadOS & macOS)

Evtl. liegt das an einer Rückgabe von der API. Für welchen groben Standort wird das Widget ausgeführt?

**Comment by pin00b** [comment]
Danke für die schnelle Antwort! – Copy&paste der aktuellsten Version habe ich schon gemacht, identische  Fehlermeldung auf macOS, iPadOS und iOS. – Berlin...

**Comment by rphl** [comment]
Hmm. Habe es mal mit Standardkoordinaten(google: 52.515816, 13.454293) für Berlin getestet. Alles funktioniert. 

Bitte mal mit den oberen Koordinaten testen. https://github.com/rphl/corona-widget#statische-standort-koordinaten Brauche sonst mehr feedback.

<img width="356" alt="Bildschirmfoto 2022-01-11 um 18 32 35" src="https://user-images.githubusercontent.com/97642/148992662-48231868-216e-4160-b6e2-e84b8dc94dad.png">
