### ISSUE TITLE
Error on Line 64:54 - Api für Impfungen (Vaccine) nicht verfügbar

### ISSUE THREAD

**Issue by andreas0087** [rphl/corona-widget#182]
Hallo,

seit gestern Morgen erhalte ich angehängten Fehler.
![6548ED11-F103-4886-9B8D-83187C10741F](https://user-images.githubusercontent.com/50969483/150078735-7accdace-808d-4e8d-811d-99f6bc75f7f2.jpeg)

An den Einstellungen in Scriptable bzw. dem Code in Scriptable habe ich in den letzten Tagen keine Änderungen vorgenommen.

Mit freundlichen Grüßen,
Andreas

**Comment by ravenhal** [comment]
Denselben Fehler bekomme ich auch, jedoch nur wenn ich die mittlere Variante des Widgets verwende, in der auch die Impfdaten abgefragt und dann angezeigt werden. Bei Aufruf des kleinen Widgets ohne Impfdaten kommt dieser Fehler nicht.

**Comment by Bastelnator** [comment]
Hallo,

den Fehler kann/muss ich leider bestätigen, ebenfalls seit gestern (oder schon Montag?).

![46B55AB5-E6EF-4533-ADC4-F31CAA8D142D](https://user-images.githubusercontent.com/98017282/150097655-2b342665-fbc7-417e-a8cf-54848e1898de.jpeg)

**Comment by rphl** [comment]
Hmm. Sehe die API liefert für die Impfungen keine Daten. Ist Wahrscheinlich temporär. 
Checke aber trotzdem mal wegen einer besseren Fehlermeldung

```
{
"message": "scrapping data from RKI excel failed"
}
```

**Comment by rphl** [comment]
Habe mal kleines Update online gestellt was zumindest eine Bessere Fehlermeldung anzeigt. 

Weswegen die Impfquoten nicht abgerufen werden können, muss ich später in Detail checken.

<img width="279" alt="Bildschirmfoto 2022-01-19 um 10 42 25" src="https://user-images.githubusercontent.com/97642/150104958-7b1306a4-a98a-46bc-addd-7070ef9cd04b.png">

**Comment by rphl** [comment]
Sollte jetzt gefixed sein.
