### ISSUE TITLE
Darstellungsprobleme 2x Medium Widget

### ISSUE THREAD

**Issue by mrks115** [rphl/corona-widget#185]
Sobald ich 2 Medium Widgets habe bekomme ich die im Anhang zu sehenden Darstellungsprobleme im unteren Widget, siehe Anhang.

![Bildschirmfoto 2022-01-27 um 09 16 22](https://user-images.githubusercontent.com/3636209/151347882-216e1f94-d93a-4225-9c3f-fff067a57ffb.png)

**Comment by rphl** [comment]
Da Mainz in RheinlandPfalz liegt und Kleve in NRW, werden beide Bundesländer angezeigt. D(eutschland) ist dann im Kopfbereich.

Im oberen Widget liegen beide Orte in NRW. Deswegen wird NRW nur 1x angezeigt und D(eutschland) wird unten angezeigt (Nimmt den Platz vom doppelten NRW ein)

Für mich sieht alles aus wie erwartet.

**Comment by mrks115** [comment]
Ahh, Feature und kein Bug, verstehe 👍
Danke fürs Feedback :)

**Comment by rphl** [comment]
jepp :-)
