### ISSUE TITLE
Was sind das für Zahlen beim Hospitalisierungsindex in den Klammern?

### ISSUE THREAD

**Issue by andreas0087** [rphl/corona-widget#188]
Hallo,

ich versuche nachzuvollziehen, was die Zahlen in den Klammern beim Hospitalisierungsindex bedeuten?
Denn z.B. kann es für BW weder freie noch belegte Intensivbetten sein, denn die Zahl dafür ist vollkommen anders.

![D3278B09-AFBA-434E-AE62-DFCD62BF8789](https://user-images.githubusercontent.com/50969483/152690972-11adc9f7-fdfa-41c1-8a55-58ee1cc525db.jpeg)

Danke für die Erläuterung :)

Mit freundlichen Grüßen,
Andreas

**Comment by rphl** [comment]
Fälle (Hospitalisierubgen) der letzten 7 Tage. Jeweils für Land und Bund.

**Comment by andreas0087** [comment]
Ah, verstehe. Also grundsätzlich Krankenhauseinlieferungen (egal ob Normal oder Intensivstation).

Danke für die Aufklärung :)
