### ISSUE TITLE
Keine Datenaktualisierung

### ISSUE THREAD

**Issue by Callidus2000** [rphl/corona-widget#189]
Es werden heute keine aktuellen Daten angezeigt, beim Aufruf der URL wird nach einem Token gefragt.

**Comment by ravenhal** [comment]
Bei mir werden aus dem Cache noch die Daten vom 14.02. 20:08 Uhr angezeigt (letzter Abruf) und gestern und heute den ganzen Tag über das Blitzsymbol oben rechts, dass keine Verbindung besteht.

**Comment by rphl** [comment]
Das RKI scheint wieder etwas im Hintergrund geändert / "optimiert" zu haben. Müssen wahrscheinlich bis zum nächsten Datenupdate warten. Versuche aber es aber parallel in detail zu prüfen.

**Comment by neelix82** [comment]
https://arcgis.esri.de/aenderung-des-rki-covid-19-datensatzes/

**Comment by icsAT** [comment]
@neelix82 hat es ja bereits aufgezeigt @rphl.

Vermutlich reicht es
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/RKI_COVID19/FeatureServer/0...
durch
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/Covid19_hubv/FeatureServer/0...
zu ersetzen.

**Comment by rphl** [comment]
Api endpoints im Widget habe ich angepasst. Sieht soweit gut. Habe ein Update online gestellt.

**Comment by ravenhal** [comment]
Vielen Dank, nun funktioniert es wieder!

**Comment by surfincool** [comment]
salve....herzlichen dank für die arbeit....

ich hätte gerne nur die zahlen für die bundesweite neue infektionszahlen und die inzidenz ...weil in dem widget soviel
dargestellt wird ist leider auch der schriftgrad klein......ohne fernglas für mich nicht möglich zu lesen....
was muß ich tun ?

danke im vorraus

eberhard
