### ISSUE TITLE
Updatedatum fehlt im widget

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#19]
Sehe kein Update Datum im widget

![3EC25606-1A61-49DE-82CE-E89193E332D9](https://user-images.githubusercontent.com/6056918/97796687-83705480-1c15-11eb-83b3-1ba1823da1b5.jpeg)

**Comment by Nils89** [comment]
Es scheint  ein Problem mit dem Monatswechsel zu geben. 
Die Daten vom 1.11. werden gespeichert, aber im Widget werden die Daten vom 31.10. angezeigt.

**Comment by pille85** [comment]
Ich denke auch, dass es ein Problem mit dem Monatswechsel ist.

Im Widget wird bei mir sogar noch das Datum von gestern angezeigt. Die Werte sind auch von gestern.

Das Balkendiagramm ist aber um einen Wert seit gestern erweitert worden und auch in der json-Datei ist das heutige Datum vorhanden.

![image](https://user-images.githubusercontent.com/73462313/97797740-c8998400-1c1f-11eb-8649-b21313f0cae1.jpeg)

**Comment by rphl** [comment]
Ja da gab es tatsächlich ein Problem mit dem Monatswechsel. Habe mal ein Update online gestellt.
