### ISSUE TITLE
Frage zu Inzidenz D

### ISSUE THREAD

**Issue by toddy1986** [rphl/corona-widget#190]
![635C7B6D-2CFF-40D1-9056-B3A6D6965798](https://user-images.githubusercontent.com/83943893/154792908-2940914c-279b-4786-8319-3be1f534cd43.png)
![8FE9603E-C7F0-432E-BBAC-B82C2CD81BA9](https://user-images.githubusercontent.com/83943893/154792912-69ad8315-420e-422e-92e3-f16ba40a9e29.jpeg)

Die Inzidenz zwischen dem RKI und dem Widget weicht manchmal ab. Heute 1350 vs 1353. liegt das an unterschiedlichen Daten?

**Comment by rphl** [comment]
Das Widget berechnet die Inzidenz anhand der gemeldeten Fälle vom RKI. Daraus ergibt sich der Graph und die angezeigte (Live)-Inzidenz. Siehe auch https://github.com/rphl/corona-widget#-quelledatenbasis

Falls es hier einen Unterschied gibt. So liegt es an Korrekturen (Nachmeldungen,etc der Fälle) in der RKI API der jeweiligen Region, die nicht in die Dashboard (statische) Inzidenz eingeflossen sind.

Will man dennoch stattdessen die Dashboard (statische) Inzidenz anzeigen, so lässt es sieht in der Konfiguration einstellen. Siehe Abschnitt "Konfiguration"
