### ISSUE TITLE
Seit 3 Tagen kein Update der Daten

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#191]
Seit 3 Tagen steht der Wert für Wiesbaden (Koordinaten 50.0782,8.2398) auf 1.308, obwohl das RKI die Zahlen updatet. 

![image](https://user-images.githubusercontent.com/82751561/154995575-b5824ba0-9ad9-4359-a8bb-34cd1885919d.jpeg)

Haben die vielleicht wieder ihre Spalten umbenannt und das Script findet deswegen nichts?

**Comment by ragalthar** [comment]
Hier noch der Beweis, dass das RKI aktuellere Werte liefert.

![image](https://user-images.githubusercontent.com/82751561/154996719-b8dca156-97a7-40ec-986e-3fca2ac51419.png)

**Comment by ragalthar** [comment]
Idee: keine Ahnung, ob das umsetzbar ist oder ich jetzt gegen irgendwelche ungeschrieben "Gesetze" verstoße. Unter https://github.com/marcusraitner/COVID-19-Dashboard hat jemand ein ähnliches Covid-Inzidenz-Script geschrieben und hier werden die Daten vom RKI problemlos gelesen. Könnte man seine Art, die Daten auszulesen nicht übernehmen?

Sorry, wenn ich jemanden damit auf die Füße treten oder irgendwie verletzen sollte, war nicht meine Absicht, dann bitte löschen!

**Comment by rphl** [comment]
Bitte aktuelle/letzte Version nutzen. Problem bereits vor Tagen gelöst: https://github.com/rphl/corona-widget/issues/189
