### ISSUE TITLE
Widget aktualisiert sich nicht mehr 

### ISSUE THREAD

**Issue by bondskin** [rphl/corona-widget#192]
Das Datum bleibt auf dem 15.2.2022 stehen und die Daten sind ebenfalls unverändert 
![E39ED657-5501-4EA8-83D9-8E3D2B720560](https://user-images.githubusercontent.com/55050117/155077446-e00d3199-f7d4-4603-9582-607744b8a47a.jpeg)

Was hat der Blitz anstelle der Antenne oben rechts zu bedeuten?

**Comment by rphl** [comment]
Bitte aktuelle Version verwenden. Wurde bereits korrigiert. Siehe #189

**Comment by bondskin** [comment]
Danke; hatte ich übersehen. Funktioniert jetzt
