### ISSUE TITLE
Keine Aktualisierung

### ISSUE THREAD

**Issue by emeff68** [rphl/corona-widget#193]
Moin, das Widget aktualisiert sich seit 15.02. nicht mehr. Hat sich was geändert?

**Comment by emeff68** [comment]
Hatte testweise mal den Cache gelöscht, bekomme nun natürlich die Meldung, dass kein Cache vorhanden ist und keine Standortdaten geladen werden können.
GPS nutze ich eigentlich nicht, ich habe zwei Standorte als URL definiert.

**Comment by rphl** [comment]
Bitte die neuste Version verwenden. Es hat sich in der Vergangenheit etwas an der RKI API geändert. Dann sollte es wieder funktionieren.

**Comment by emeff68** [comment]
Sorry, hatte die neue Version nicht gesehen. Funktioniert jetzt so wie es soll. Danke für deine schnelle Rückmeldung!!!
