### ISSUE TITLE
API für Neuinfektionen geändert?

### ISSUE THREAD

**Issue by andreas0087** [rphl/corona-widget#195]
Hallo,

seit heute zeigt bei mir das Widget sowohl für meinen Kreis als auch für BW und D Neuinfektionen +0. Wurde ggf. die API geändert?

**Comment by BastianLinge** [comment]
Hallo,
funktioniert bei mir seit gestern auch nicht mehr. Keine Neuinfektionen, kein Aktueller Wert.

**Comment by ravenhal** [comment]
Ich kann bestätigen, dass es seit dem 19.03. auch bei mir keine neuen Infektionszahlen gibt. Es wird überall +0 angezeigt und damit die Inzidenz falsch (zu gering) berechnet. Eine Fehlermeldung taucht aber nicht auf.

**Comment by Stefan-1982** [comment]
Bei mir zeigt es auch 0 bei den Neuinfektionen an und die inzidenz liegt im Widget bei 740 obwohl sie laut rki Dashboard bei 1005 liegt

**Comment by ragalthar** [comment]
Das Widget zieht falsche Werte

Koordinaten Wiesbaden 50.0782, 8.2398

![image](https://user-images.githubusercontent.com/82751561/159221931-a97d45c4-e28a-42e2-a8b8-920604c71158.jpeg)

![image](https://user-images.githubusercontent.com/82751561/159221961-820a67bb-0c16-4821-8fa7-80cf3ca269ee.png)

**Comment by rphl** [comment]
Hier gab es wohl seitens RKI für die letzten 3 Tage keine Tagesaktuellen Daten die mittels API abgerufen werden konnten. Alles auf 0, letzter Datenstand laut Api war der 18.03

Heute scheint dies behoben worden zu sein. 

<img width="143" alt="Bildschirmfoto 2022-03-21 um 10 49 03" src="https://user-images.githubusercontent.com/97642/159237928-c939a5fe-4e63-4fc2-a564-56ce4191569b.png">

**Comment by andreas0087** [comment]
Die Daten werden mittlerweile wieder korrekt angezeigt. Ich schließe das Ticket daher.
