### ISSUE TITLE
Datenformat falsch

### ISSUE THREAD

**Issue by rehcappil** [rphl/corona-widget#196]
> 2022-05-09` 3:40:14 PM: "Current Theme:" | "auto"

> 2022-05-09 3:40:14 PM: "script selfUpdate" | "running"

> 2022-05-09` 3:40:14 PM: "script selfUpdate" | "updated"

> 2022-05-09 3:40:15 PM: Error: Die Daten konnten nicht gelesen werden, da sie nicht das korrekte Format haben.

Ist der Fehler zu oben genannten log bereits bekannt?

**Comment by Tongo91** [comment]
Den Fehler habe ich auch seit ungefähr einer Woche, seltsamerweise scheint trotzdem noch eine Aktualisierung zu laufen.

**Comment by Piwio** [comment]
Habe auch genau den Fehler, komplette Neuinstallation hat nichts gebracht, leider :-(

**Comment by Piwio** [comment]
Danke dir! Nach erneuter Neuinstallation geht es erstmal wieder 😃
