### ISSUE TITLE
Widget zeigt falsche Werte an

### ISSUE THREAD

**Issue by ragalthar** [rphl/corona-widget#198]
Das zeigt das Widget heute
![image](https://user-images.githubusercontent.com/82751561/170811057-6ff78d73-4405-48b8-9306-2464a8343ee4.jpeg)
und das sind die Werte vom RKI
![image](https://user-images.githubusercontent.com/82751561/170811068-29fb598c-3b3d-49ea-9103-ec9afe5a7abd.png)
Koordinaten von Wiesbaden:
50.0782,8.2398

Hat das RKI mal wieder die Tabelle umgebaut?

**Comment by firebowl** [comment]
Schein ein generelles Problem zu sein, hier bei mir das gleiche. 
Obwohl die Werte wohl eher der Realität entsprechen als die „richtigen“ Werte. ;)

**Comment by lululasse** [comment]
Same here! Irgendwas stimmt nicht.

**Comment by ragalthar** [comment]
Heute ist die Abweichung noch schlimmer. Das Widget 
![image](https://user-images.githubusercontent.com/82751561/170854368-4b0f83aa-3326-4c6e-8c58-4eaedebb42ed.jpeg)
vs. das RKI
![image](https://user-images.githubusercontent.com/82751561/170854381-2e85563c-74f5-4579-a1cb-6b49477cc58f.png)

**Comment by Genuine-G** [comment]
Kann ich (leider) nur bestätigen. Auch bei mir weichen die Daten im Wigdet sehr weit vom RKI-Dashboard ab… 😕

**Comment by Stefan-1982** [comment]
Bei mir lk Bad Kissingen auch falsche Werte

**Comment by dennerforen** [comment]
![image](https://user-images.githubusercontent.com/73590285/170862978-140053d0-27f5-4b8a-9a6d-68d43bb32543.png)

Ich denke da jennifer.Traub@icloud.com das RKI oder der Datenanbieter wieder kräftig die Datenbank verändert. Ist nicht das einzige Widget mit schrägen Zahlen.

**Comment by lululasse** [comment]
> ![image](https://user-images.githubusercontent.com/73590285/170862978-140053d0-27f5-4b8a-9a6d-68d43bb32543.png)
> 
> Ich denke da, dass RKI oder der Datenanbieter wieder kräftig die Datenbank verändert. Ist nicht das einzige Widget mit schrägen Zahlen.

Ja, kann ich bestätigen. Wenn ich zum Beispiel bei Deinem 3 Widget von oben (mittlere Größe) den Parameter auf 2 für Deutschland statt Kreis DA-DI eingebe kommt auch nur Unsinn dabei raus. Oder es passiert gar nichts. Könnte es sein, dass es alles Forks betrifft, die auf Kevin Kub's Original zurückgreifen?

Wer kann helfen, das Ding wieder zum Laufen zu bringen?

**Comment by dennerforen** [comment]
Das dritte Widget ist das von tzschies und holt sich hier die Daten

const outputFields = 'GEN,RS,EWZ,EWZ_BL,BL_ID,cases,cases_per_100k,cases7_per_100k,cases7_bl_per_100k,last_update,BL';
const apiUrl = (location) => `https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=1%3D1&outFields=${outputFields}&geometry=${location.longitude.toFixed(3)}%2C${location.latitude.toFixed(3)}&geometryType=esriGeometryPoint&inSR=4326&spatialRel=esriSpatialRelWithin&returnGeometry=false&outSR=4326&f=json`;
const outputFieldsStates = 'Fallzahl,LAN_ew_GEN,cases7_bl_per_100k';

**Comment by ragalthar** [comment]
Es wird schlimmer, das Widget heute...
![image](https://user-images.githubusercontent.com/82751561/170906736-ecbb9ac7-347e-454a-b171-43706da68733.jpeg)
und die Werte vom RKI
![image](https://user-images.githubusercontent.com/82751561/170906771-4f243575-6848-454e-95c2-029d083983a0.png)

**Comment by arianamania** [comment]
> Es wird schlimmer, das Widget heute...

Bei mir geht es jetzt plötzlich wieder!

**Comment by lululasse** [comment]
Hier auch! 😊
Manchmal hilft wohl doch Geduld.

**Comment by rphl** [comment]
> Manchmal hilft wohl doch Geduld.

Das ist bei der RKI API leider immer die erste Todo. Vor allen wenn die am Wochenende wieder was verbastelt haben 🤷‍♂️

**Comment by ragalthar** [comment]
Das folgende Widget hatte bisher noch nie Probleme, während dieses hier teilweise utopische oder gar keine Werte angezeigt hat. Vielleicht kann sich mal einer den Code ansehen, von woher der Autor seine Daten zieht, ich kenne mich dafür zu wenig aus, um das zu erkennen. Der Link zum Widget hier auf Github ist https://github.com/marcusraitner/COVID-19-Dashboard
