### ISSUE TITLE
Falsches "runden" bei Inzidenzwerten >100

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#2]
Wenn die Werte für die Inzidenz größer als 100 sind, lässt du die Nachkommastellen ja weg.
`Math.floor`
Damit wird aber aus einem Wert von z.B. 108,7 eine 108.
Würdest du aber
`Math.round`
nehmen würde aus den 108,7 eine 109 werden.
Das wäre meiner Meinung nach der sauberere Weg.

**Comment by rphl** [comment]
Danke. Ist korrigiert.
