### ISSUE TITLE
Klick auf Widget öffnet URL

### ISSUE THREAD

**Issue by youmakemyday** [rphl/corona-widget#20]
Guten Morgen. Beim Klicken auf das Medium Widget öffnet sich immer Safari und öffnet den Link: https://experience.arcgis.com/experience/... 

Im Widget ist RunScript angegeben. Ist das Verhalten gewünscht oder ein Bug? Falls gewünscht kann man das wieder ändern, sodass das Skript per Klick ausgeführt wird?

**Comment by youmakemyday** [comment]
danke 👍

**Comment by rphl** [comment]
Aktuell ist das verhalten erwünscht. Im Kopfbereich des Skriptes ist jetzt aber auch ein Schalter um dies abzustellen. `CONFIG_OPEN_URL=false` stellen, dann öffnet ein Tippen keine URL mehr
