### ISSUE TITLE
Widget wird unter iOS 16(.3?) nicht ausgeführt

### ISSUE THREAD

**Issue by DannyBoyKN** [rphl/corona-widget#201]
Hallo,
habe aktuell auf iOS 16.3 gewechselt. Jetzt wird das Corona Widget überhaupt nicht mehr angezeigt, bleibt leer:

<img src="https://user-images.githubusercontent.com/22725819/216829425-154cd12e-7671-406f-8366-d23bf53ce718.png" data-canonical-src="https://user-images.githubusercontent.com/22725819/216829425-154cd12e-7671-406f-8366-d23bf53ce718.png" width="200"/>

<img src="https://user-images.githubusercontent.com/22725819/216829384-ca1197ed-c77b-4130-9017-c707ec1f0ab5.png" data-canonical-src="https://user-images.githubusercontent.com/22725819/216829384-ca1197ed-c77b-4130-9017-c707ec1f0ab5.png" width="200"/>

Beim Starten aus der Scriptable App heraus funktioniert es jedoch:

<img src="https://user-images.githubusercontent.com/22725819/216829034-187f1d0b-b29c-4b4f-ba48-371b9f717829.png" data-canonical-src="https://user-images.githubusercontent.com/22725819/216829034-187f1d0b-b29c-4b4f-ba48-371b9f717829.png" width="300"/>

Ist dir das bekannt ?

Das merkwürdige ist, dass alle anderen Scripts als Widgets funktionieren, nur dieses 'Corona' Script nicht ! Fehlt da evtl. ein Setting, welches das Script ab iOS 16 zusätzlich benötigt ?

Grüße

**Comment by dennerforen** [comment]
Bei mir läuft es. Lösche es und installiere es neu.

**Comment by DannyBoyKN** [comment]
Löschen was ? 
das corona Script aus Scriptable oder Scriptable komplett? Letzteres ist mir zu radikal … zunächst …

ich hab mal nur das Script entfernt und neu eingetragen, ohne Erfolg.

nebenbei, das homebridgeStatusWidget.js Script / Widget verhält sich genauso, VodafoneDE.ja, PremiumSim.js oder covid-19-7-day-incidence-county.js funktionieren weiterhin.

**Comment by dennerforen** [comment]
Erst das Widget löschen und neu platzieren.

Wenn das nicht hilft das Script löschen und neu in Scriptable anlegen.


Version prüfen, ob du das Neueste hast.

Aber wenn es aus Scriptable läuft, aber nicht als Widget hast du das Widget falsch konfiguriert

Run Script

Setze mal diesen Parameter ein beim Medium Widget

0,49.86,8.76,DA Di;1,49.88,8.63,DA Mitte

Das sind meine Koordinaten, damit kannst du wenigstens die Funktion testen.

![image](https://user-images.githubusercontent.com/73590285/216842893-9b0ac653-f25f-4b98-825f-6bdba2105aa0.jpeg)

**Comment by DannyBoyKN** [comment]
> Erst das Widget löschen und neu platzieren

Bleibt weiterhin leer, auch mit Deinen Koordinaten ...

> Wenn das nicht hilft das Script löschen und neu in Scriptable anlegen.

Bleibt weiterhin leer, ebenfalls mit Deinen Koordinaten ...

> Version prüfen, ob du das Neueste hast.

Ich hab's jetzt über ScriptDude aufgesetzt, sollte also die Neues sein ...

> Aber wenn es aus Scriptable läuft, aber nicht als Widget hast du das Widget falsch konfiguriert
> Run Script

Aber es lief doch hervorragend die letzten Jahren, genauso so, medium + small, fixen Koordinaten, Run Script ...

**Comment by DannyBoyKN** [comment]
@dennerforen: Was ist Deine iOS Version ?

**Comment by dennerforen** [comment]
iPadOS 16.3 (20D47)

**Comment by DannyBoyKN** [comment]
Auf meinem iPad, jetzt auch mit 16.3 funktioniert es ebenfalls. Ein iOS 16.3 Problem ? Bei dem [HomebridgeStatusWidget](https://github.com/lwitzani/homebridgeStatusWidget) hat er mir bestätigt, dass es bei ihm unter iOS 16.3 ebenfalls läuft, ich dagegen ein "request timeout" erhalte" !?

Ich habe auch schon an den Datenschutz-Einstellungen gedreht, ohne Erfolg.
Kann es evtl. an irgendwelchen Einschränkungen in meinem Home LAN liegen (Phiole, DNS, ...) ?
Das [covid-19-7-day-incidence-county.js](https://gist.github.com/marcusraitner/a1b633625d1016498eaaab712461dfc4) funktioniert ohne Anstand, greift ja auch auf die selbe RKI API zu ...

Heute morgen hatte ich im Widget die Meldung 
```
"Standortdaten konnten nicht geladen werden.
Kein Cache verfügbar.

Bitte später nochmal versuchen"
```
Das deutet doch dann auf eine (grobe) Verzögerung bei mir im LAN hin, oder ? 
Könnte ich evtl. einen Timeout Wert hochstehen und es dann ausprobieren ?

**Comment by DannyBoyKN** [comment]
Ich habe jetzt einfach die Scriptable App einfach auf dem iPhone gelöscht und wieder neu aus dem AppStore geladen. Siehe da, jetzt funktioniert das Widget wie gehabt 😄
