### ISSUE TITLE
Keine neue Daten mehr

### ISSUE THREAD

**Issue by lululasse** [rphl/corona-widget#202]
Seit 1. März funktioniert das Widget nicht mehr. Scheint am RKI zu liegen. 
Habe gesehen, dass möglicherweise hier die Lösung schon vorliegt 
https://github.com/marlon360/rki-covid-api/issues/504
Wer könnte dies einpflegen?
Gruß und Danke vorab.

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/226109041-2288f6f5-489e-4e88-b3e0-4c8bf1af6136.jpeg)

Den Screenshot habe ich gerade erstellt. Das Widget zieht keine neuen Daten mehr seit dem 01.03., auch bei mir.

**Comment by dennerforen** [comment]
Ja, die Schnittstelle ist jetzt kostenpflichtig und der Author müsste den Code umschreiben auf die neue kostenlose Quelle.

Ob er das macht ist fraglich, da ja angeblich die Pandemie vorbei ist. 😅

**Comment by ragalthar** [comment]
> Ja, die Schnittstelle ist jetzt kostenpflichtig und der Author müsste den Code umschreiben auf die neue kostenlose Quelle.

In dem von mir verlinkten anderen Corona Widget wurde der Code seit mehr als einem Jahr nicht mehr verändert und das Widget funktionierte, auch wenn dieses hier "Schluckauf" hatte.

Vielleicht kann man den Code, wie das andere Widget die Daten aus dem RKI-API zieht, hier übernehmen? Ich kann es leider nicht.

**Comment by dennerforen** [comment]
Würde ich Code verstehen, würde ich es für mich machen. So bleiben mir nur die Alternativen, die zu nutzen, die noch funktionieren, wie dieses 

https://raw.githubusercontent.com/marcusraitner/COVID-19-Dashboard/master/covid-19-7-day-incidence-county.js

**Comment by lululasse** [comment]
Wenn ich richtig verstehe hat Rubber1Duck hat bei Marlon360 eine neue RKI Schnittstelle definiert? Leider kann ich das nicht entsprechend einprogrammieren. Hoffe einer von Euch?

**Comment by lululasse** [comment]
Marcus' Widget funktioniert wieder nach Änderung. Ich hab dies auch und auch da musste die Quelle geändert werden.

**Comment by icsAT** [comment]
Man muss hier zwei Dinge unterscheiden.
Das Widget von Raphael holt sich die Daten "direkt" vom RKI.
Das Widget von Marcus nutzt aufbereitete Daten von Marlon.

Was ist passiert.
Das RKI hat die Schnittstelle auf die sowohl Marlon, als auch Raphael bisher zugegriffen haben eingestellt.
Es gibt eine neue Schnittstelle aus der man die benötigten Daten imho erhalten kann.
Allerdings sind die beide Schnittstellen völlig unterschiedlich, so dass eine Umstellung auf die neue Schnittstelle etwas mehr Aufwand bedeutet, als z.B. letztes Jahr, wo sich nur die URL geändert hat. 

Marlon bzw. Peter haben diese Umstellung für Marlons API vorgenommen.
Das ist der Grund, warum das Widget von Marcus wieder funktioniert, ohne dass Marcus selber etwas anpassen musste.

Raphael oder jemand anderes müsste diese Umstellung jetzt für Raphaels Widget durchführen. Ist die Frage, ob dafür jemand die Zeit findet.
