### ISSUE TITLE
Diagramm für ganz DE

### ISSUE THREAD

**Issue by Nils89** [rphl/corona-widget#21]
Müsste der Balken für heute (1.11.) nicht kleiner sein als der von gestern 31.10?

Bei mir ist der größer.

**Comment by rphl** [comment]
Im Diagram wird wie bei der Stadt und BL die Inzidenz ausgewertet. Nicht die absoluten zahlen.

Die Zahl der Infektionen ist zwar gesunken, die Gemsamt-Inzidenz stieg aber leider wieder. Und das diesmal über 100. Deswegen auch Dunkelrot :-(

**Comment by Nils89** [comment]
Ah ok, danke. 
Dachte hier bezieht sich das auf die Fall zahlen.
