### ISSUE TITLE
Trend Pfeil im Widget falsch?

### ISSUE THREAD

**Issue by UweLoyal** [rphl/corona-widget#22]
Die Trend Pfeile im unteren Teil des Widgets sind meiner Ansicht nach falsch.
![6B0ADB44-6C53-47DD-9EFC-DB87F26B9A25](https://user-images.githubusercontent.com/5464553/97809591-0e7d3900-1c6e-11eb-9ed0-271eb87367c2.jpeg)
Bei +60 müsste der Pfeil nach oben sein!
Oder soll hier der Pfeil nach unten eine Verschlechterung bedeuten?
Dann ist der Pfeil bei Gesamtwert rechts oben aber entgegen der Logik.

LG
Uwe Loyal

**Comment by tomacco81** [comment]
So wie ich das verstehe soll der Pfeil die Veränderung zum Vortag zeigen. Wenn die vorherigen Werte höher waren geht der Trend ja logischerweise wieder nach unten.

**Comment by UweLoyal** [comment]
RKI sagt bei Hessen +1.074, der Pfeil im Widget zeigt aber nach unten. Beim Wert 60 zeigt der Pfeil nach unten, das Widget links oben sagt +60, sollte das auch nicht richtig sein, dann ist der Balken auch falsch (ist kleiner).

![A95F97E3-031E-449F-97F8-5558073C2873](https://user-images.githubusercontent.com/5464553/97812269-8b191300-1c80-11eb-8509-1d522a12a933.jpeg)

Gruß
Uwe Loyal

**Comment by Eeewald85** [comment]
Es wird ja immer mit dem vorherigen Tag verglichen. Waren da +100 Infektionen und sind heute +60 Infektionen, dann ist die Steigrate gesunken. Also wird der Pfeil nach unten angezeigt. Gleiches auch beim Bundesland.

**Comment by rphl** [comment]
Die Pfeile bei den Fallzahlen sind ein "3Tage Trend"
D.h Die Differenz zwischen `heute (minus) gestern` & `gestern (minus) vorgestern` ist hier entscheidend.

Die Diagramme zeigen die Inzidenz an (Stadt/Land/Bund), nicht die Fallzahlen. 
D.h selbst bei einer geringereren Infektionszahl, steigt diese. Erst bei +0 wird diese wieder Fallen.

**Comment by tooomm** [comment]
>Die Diagramme zeigen die Inzidenz an (Stadt/Land/Bund), nicht die Fallzahlen.

Oh, das ist aber nicht selbsterklärend und tatsächlich überraschend, da sie direkt neben den Fallzahlen angezeigt werden... das war für mich der logische Zusammenhang. Die Fallzahlen haben zwar auch keine Beschreibung, im Moment zumindest ist aber klar, dass es keine Inzidenz sein kann.

Im obigen Beispielfoto war das sogar zufälligerweise übereinstimmend (ich gehe davon aus, dass der letzte Balken die heutigen Daten wiederspiegelt und nicht die von gestern):
- 60 neue Fälle im Kreis, aber weniger als am Vortag wie man im Diagramm sieht --> daher fallend
- 1074 neue Fälle im Bundesland, ~gleich viele zum Vortag laut Diagramm, scheinbar leicht weniger --> daher fallend
- 14177 neue Fälle in Deutschland, mehr als am Vortag laut Diagramm --> daher steigend

**Comment by Nils89** [comment]
Ein Trend ist kein Vergleich zum Vortag, sondern immer wie sich die Zahlen entwickeln. Und hier Zeit der Trend nach unten  heißt die Zahlen steigen zwar aber weniger „schnell“ und damit geht der Trend nach unten. Somit passen alle Pfeile (mit der aktuellen Version). 

Die Balken haben, wie oben beschrieben, nichts mit der jeweiligen Zahl drüber zu tuen (nur indirekt). Das Diagramm zeigt lediglich den Verlauf des Inzidenz Wertes, nicht dem der Fallzahlen.

**Comment by rphl** [comment]
Ich finde wenn man die Fälle im Diagramm verwendet, ist die Ausprägung nicht so gut erkennbar. Hier mal ein Beispiel:

![image](https://user-images.githubusercontent.com/97642/97815089-03390600-1c8c-11eb-9bed-3b2a6eb9f565.png)


Ich überlege mir etwas, wie man den Trend "besser" kennzeichnet. **Ideen?**

**Comment by Nils89** [comment]
Evtl. Eine Option einbauen, was als Diagramm von beiden angezeigt wird. Und bei den Fallzahlen einen Faktor mit reinnehmen, mit welchem der Diagramm wert multipliziert/ dividiert wird, damit man einen besseren Unterschied sieht?

**Comment by tooomm** [comment]
>Ein Trend ist kein Vergleich zum Vortag, sondern immer wie sich die Zahlen entwickeln. Und hier Zeit der Trend nach unten heißt die Zahlen steigen zwar aber weniger „schnell“ und damit geht der Trend nach unten. Somit passen alle Pfeile (mit der aktuellen Version).

@Nils89 rphl hat oben ja geschrieben wie es funktioniert. Man vergleicht schon mit dem Vortag, aber nicht die absoluten Werte, sondern ihre Veränderung. Und wenn man **zwei Veränderungen** vergleicht betrachtete man genau genommen **drei Tage**, 
nämlich von `d -2` --> `d -1` und von `d -1` --> `d`.

Ich habe nur versucht zu zeigen, dass man die Darstellung falsch deuten und einen sichtbaren Zusammenhang herstellen könnte, der aber einer falschen Annahme unterliegt.

>Die Balken haben, wie oben beschrieben, nichts mit der jeweiligen Zahl drüber zu tuen (nur indirekt). Das Diagramm zeigt lediglich den Verlauf des Inzidenz Wertes, nicht dem der Fallzahlen.

Korrekt, das ist aber nicht unbedingt verständlich oder ersichtlich.

---

@rphl Ja, das stimmt. Es sieht weniger hübscht aus. Aber das kann ja auch an der aktuellen Situation liegen und in 2 Wochen anders sein. Zur besseren Darstellung von Unterschieden einen Faktor zu nehmen hört sich interessant an!
Wenn man statt den direkten Fallzahlen ihre Veränderung nimmt wird die Darstellung vermutlich kompliziert...

**Comment by rphl** [comment]
Hier ist schon mal meine Idee. Damit es etwas klarer wird:

Habe jetzt die Fälle mal als Basis für die Diagramme genommen, und diese zur besseren Darstellung "Umgerechnet"
Auch die Pfeile habe jetzt eine einfacherer Logik.

![IMG_5462](https://user-images.githubusercontent.com/97642/97871593-04fadc00-1d15-11eb-9ffe-056a5d142499.jpg)

**Comment by STJIKA** [comment]
"NEUE FÄLLE" je Tag gemeint...oder??? ...oder "DERZEIT INFIZIERTE" ????
![Bildschirmfoto 2020-11-02 um 14 18 15](https://user-images.githubusercontent.com/8932465/97872609-9ae33680-1d16-11eb-9440-5dce9f14b096.jpg)

**Comment by JoeGit42** [comment]
> "NEUE FÄLLE" je Tag gemeint...oder??? ...oder "DERZEIT INFIZIERTE" ????

In den Balken werden die neuen Fälle je Tag angezeigt vermute ich (bzw. würde ich für sinnvoll halten).

Die (kleinen) Pfeile halte ich für schwierig. Alles was man mit den neuen Fällen der letzten **drei** Tagen anstellt, wird am Wochenende Blödsinn anzeigen. Man muss das WE also rausglätten. Schwups - ist man bei der 7-Tage Inzidenz.

Um das ganze zu vereinfachen, würde ich etwas Komplexität rausnehmen:
- Den R-Wert würde ich rauswerfen. Letztendlich ist der zwar total wichtig und entscheidend, aber die Berechnung vom RKI scheint mir doch wenig nachvollziehbar und wenig vertrauenswürdig. 
- Stattdessen würde ich die Inzidenz von DE anzeigen (inkl. Pfeil)
- Die drei kleinen Pfeile würde ich rausnehmen. Es gibt für Stadt - Land - Bund bereits eine Indikation über die 7-Tage Inzidenz - inkl. Pfeil. Das müsste reichen.

**Comment by UweLoyal** [comment]
Sehr gut ist auch das Vorzeichen vor dem Wert, damit wird auch deutlicher, dass bei positiven Werten der Pfeil eine Tendenz anzeigt!
Da das Widget sehr klein ist und man keine Beschriftung vornehmen kann, wäre eine Kurzbeschreibung sehr gut, oder ein Tippen auf das Widget führt zu einer Infoseite.

LG
Uwe Loyal

**Comment by rphl** [comment]
> "NEUE FÄLLE" je Tag gemeint...oder??? ...oder "DERZEIT INFIZIERTE" ????

@STJIKA JA ES SIND NEUE FÄLLE JE TAG!!!!


So jetzt kann ich wieder caps ausmachen ;-)

---
> Den R-Wert würde ich rauswerfen. Letztendlich ist der zwar total wichtig und entscheidend, aber die Berechnung vom RKI scheint mir doch wenig nachvollziehbar und wenig vertrauenswürdig.
Stattdessen würde ich die Inzidenz von DE anzeigen (inkl. Pfeil)

@JoeGit42 Wäre eine Überlegung Wert. Wobei der R-Wert ja direkt vom RKI kommt. Wenn man den nicht trauen kann wen dann ? 😄 Könnte mir aber eine Option vorstellen. Wo man sich das Aussuchen kann, was oben dargestellt wird.


Erstmal baue ich aber mal die Diagramme um :-) 

Gerne ein separates Ticket dafür aufmachen.

**Comment by JoeGit42** [comment]
> @JoeGit42 Wäre eine Überlegung Wert. Wobei der R-Wert ja direkt vom RKI kommt. Wenn man den nicht trauen kann wen dann ?

Generell traue ich dem RKI natürlich, und der R-Wert ist auch nicht komplett falsch oder gar manipuliert. Es ist aber halt nur ein Schätzeisen. Was da im April an Daten abgeliefert wurde, war eher dürftig. Ich kann mich noch an die Pressekonferenz erinnern, als der "Experte für die R-Berechnung" selber das erklären durfte. Vermutlich hat Prof. Dr. Wieler seinem Mitarbeiter gesagt, dass er das mal schön selbst der Öffentlichkeit verkaufen kann, was er da verzapft. (Stelle ich mir ganz naiv so vor.)
Auch das ausgewiesene 7-Tage R schwingt doch mehr als ich es erwarten würde.
=> Letztendlich bin ich kein Experte, der selber den R-Wert rechnen oder schätzen könnte. Daher kann ich nur sagen, dass die Zahl vermutlich grob passen wird, sich im Detail aber merkwürdig verhält. Daher schaue ich nur selten auf den R-Wert.

**Comment by rphl** [comment]
So Update ist online. Habe mal die Diagramme überarbeitet. Gerne mal testen.
Siehe auch hier. https://github.com/rphl/corona-widget/blob/master/README.md
