### ISSUE TITLE
Erläuterung was die Zahlen und Balken bedeuten

### ISSUE THREAD

**Issue by simonCGN** [rphl/corona-widget#23]
Sehr hilfreich wäre noch eine Erläuterung zu den Zahlen und Balken:

Am Beispiel des Screenshots:
140 Inzidenz pro 100.000 Einwohner rollender Durchschnitt der letzten 7 Tage?
+72 Anzahl der Fälle in Düsseldorf gestern innerhalb der letzten 7 Tage?
+3.678 Anzahl neuer der Fälle in NRW Summe der letzten 7 Tage?
+11.###

Ich weiss ehrlich gesagt nicht was die unteren Balken und Zahlen darstellen, daher oben nur ein Beispiel wie man es erläutern könnte

**Comment by rphl** [comment]
So ein Update ist online. Habe mal die Readme etwas mit ein Erklärungen erweitert.

Gerne mal checken. Sonst ticket wieder aufmachen. 

Siehe auch hier. https://github.com/rphl/corona-widget/blob/master/README.md
