### ISSUE TITLE
AutoUpdate (Install) Funktion

### ISSUE THREAD

**Issue by rphl** [rphl/corona-widget#24]
Möglichkeiten für AutoUpdate (Install) des Skriptes checken.

> Ich finde die Idee von @dennerforen irgendwie recht praktisch. 😉
> Mich nervt es auch ein wenig, nich den ganzen Quellcode kopieren zu können. Ich benutze am iPhone entweder die GitHub > App oder Microsoft Edge und in beiden gibt beim markieren die Option "Alles" nicht.
> Hier ist das Intensivbettenwidget, das den eigentlichen Code erst beim Aufruf oder aktualisieren lädt:
> https://github.com/Keyes/its-beds-widget
> [](https://github.com/Keyes/its-beds-widget)
> Vielleicht wäre das ja auch ne Option.

_Originally posted by @firebowl in https://github.com/rphl/corona-widget/issues/6#issuecomment-720270166_

**Comment by jnhllTM4** [comment]
Funktioniert das schon?

**Comment by chimcen** [comment]
Das wär mal porno...ich copier mir aktuell per Shortcuts das RAW Script und überschreibe es dann manuell in Scriptable - wenn einer ne Idee hat das kpl. automatisch per Shortcuts zu machen würde mir das auch schon reichen...
Mein Ansatz via Shortcuts und iCloud führte immer dazu dass ich zu viel iOS Rückfragen bestätigen musste und das Script nicht richtig überschrieben wurde bzw. x-Kopien angelegt wurden...

**Comment by dennerforen** [comment]
Scriptdude erledigt das für dich

**Comment by fireman130655** [comment]
Wie funzt ScriptDude?

**Comment by chimcen** [comment]
Grad asprobiert - top Sache. Vorallem die Abfrage über hashes ist sehr elegant. Danke

**Comment by rphl** [comment]
Eine neue Version mit autoupdate ist online. Vorerst ist die Option aus. `CFG.scriptSelfUpdate: false`aus. Wäre super wenn das noch mehrere testen würden.

**Comment by chimcen** [comment]
Coole Sache, danke. Aber ich hab mittlerweile ScriptDude im Einsatz, da es alle meine Scripts updatet...
