### ISSUE TITLE
Widget Gallery

### ISSUE THREAD

**Issue by dennerforen** [rphl/corona-widget#25]
Der scriptable Entwickler bringt eine Widget Gallery, ähnlich Apples Gallery für Kurzbefehle mit dem nächsten Update. Damit erreicht man ein mio Publikum.  

Er hat ein online Formular, in dem man sein Widget einreichen kann. 

Edit, link korrigiert

https://www.iphone-ticker.de/scriptable-app-mit-galerie-einfacher-zum-eigenen-widget-165478/

**Comment by rphl** [comment]
Danke für die Info, habe die News auch schon aufgeschnappt. Werde es mal ein planen.
