### ISSUE TITLE
Vorschlag: JSONs in Unterorderner / MediumWidget doppelte BL Daten ersetzten...

### ISSUE THREAD

**Issue by smar77** [rphl/corona-widget#26]
Hallo und vielen Dank für die tolle Arbeit! 
1. Die json files könnten vielleicht in einem Unterordner landen? Wäre etwas übersichtlicher, aufgeräumter!
2. Beim Medium-size Widget könnte man Zahl der Fälle (im Screenshot "5396") vielleicht nur einmal anzeigen, anstatt auf beiden Seiten? Dafür vielleicht den R-Wert runterziehen? 
Danke & Grüße!

**Comment by rphl** [comment]
Danke für das Feedback

> 1. Die json files könnten vielleicht in einem Unterordner landen? Wäre etwas übersichtlicher, aufgeräumter!

Ich denke die meisten Leute haben 1-3 Jsons (heim, arbeit) im Ordner liegen. Aber ja, es wäre nicht schlecht diese zu verschieben. Ich plane es mal ein

> Beim Medium-size Widget könnte man Zahl der Fälle (im Screenshot "5396") vielleicht nur einmal anzeigen, anstatt auf beiden Seiten? Dafür vielleicht den R-Wert runterziehen?

Das macht nur dann sinn wenn die Leute zwei Orte im gleichen Bundesland eingetragen haben. Viele haben jedoch zwei verschiedene Bundesländer. 

Aber auch hier, drüber nachdenken kann man ja. Wenn ich mit #22 durch bin, werde ich es mal checken.

**Comment by smar77** [comment]
danke! :-)

**Comment by rphl** [comment]
So Update ist online. Die JSONs werden jetzt in einen Unterordner verschoben/ bzw. dort direkt erstellt

Gerne mal testen (JSON backup davor erstellen ;-))

Siehe auch hier. https://github.com/rphl/corona-widget/blob/master/README.md

**Comment by grisu112** [comment]
Danke für das Update. Das verschieben hat bei mir nicht geklappt. Musste die Datei manuell verschieben, ansonsten super!

**Comment by smar77** [comment]
nach 2 mal refresh/reopen hat es verschoben und funktioniert. vielen Dank dafür!!

**Comment by rphl** [comment]
Neue Version online.
