### ISSUE TITLE
Anzeige Inzidenzwert 

### ISSUE THREAD

**Issue by RosoV89** [rphl/corona-widget#27]
Hey, 

Schau mal dieses Skript an:
![C9837A3C-BC4E-46D5-8D6C-77BE0BC9DEAA](https://user-images.githubusercontent.com/73339863/98007469-b6703f00-1df3-11eb-82af-67801103e0f2.jpeg)

Hier ist der inzidenzwert der letzten 3 Wochen glaub ich abgebildet. Kannst du das auch erweitern? Derzeit werden ja die letzten 7 Tage abgebildet. Platztechnisch könnte man 14 Tage problemlos abbilden.

Kann ich das selbst einstellen?

**Comment by RosoV89** [comment]
![DA734BAB-B951-4344-94C2-57A9FD8E11F2](https://user-images.githubusercontent.com/73339863/98091854-42cb4200-1e86-11eb-917a-1c4e014f27ff.jpeg)

Wird der R Wert bei euch auch mit 0 angezeigt? ich habe nur den Namen geändert, sonst an den Parametern nichts

**Comment by rphl** [comment]
> Hier ist der inzidenzwert der letzten 3 Wochen glaub ich abgebildet. Kannst du das auch erweitern? Derzeit werden ja die letzten 7 Tage abgebildet. Platztechnisch könnte man 14 Tage problemlos abbilden.

Kannst theoretisch auch allein machen. Du musst die Limitierung des caching (limitData) von 7 auf 14 stellen. Und bei den Diagrammen (createGraph) 14 anstatt 7 eintragen.

Wenn du dich etwas gedulden kannst. Hier gibt es bald aber ein Update wo ich 10-14 darstellen werde. 

---

Wegen R-Wert schau mal bitte hier: https://github.com/rphl/corona-widget/issues/28#issuecomment-721608811

**Comment by TheSpirit** [comment]
Mehr Daten bei den Inzidenzwerten würde ich auch super finden. Geht ja scheinbar. Und dann müsste auch nix gespeichert werden

**Comment by RosoV89** [comment]
Ja kann mich gedulden. Warte gerne auf dein Update. :)

**Comment by TheSpirit** [comment]
`Kannst theoretisch auch allein machen. Du musst die Limitierung des caching (limitData) von 7 auf 14 stellen. Und bei den Diagrammen (createGraph) 14 anstatt 7 eintragen.`
finde die beiden variablen nicht im code

**Comment by rphl** [comment]
> Mehr Daten bei den Inzidenzwerten würde ich auch super finden. Geht ja scheinbar. Und dann müsste auch nix gespeichert werden

Problem sind immer noch die "Daily New Cases" für Stadt/BL. Dieser Wert ist nicht in der Api. Deswegen bleibt vorerst der Weg des cachings.

**Comment by TheSpirit** [comment]
bin auch halber Programmierer und bisher konnte ich auch ein paar Änderungen für mich umsetzen. aber die beiden parameter finde ich einfach nicht (bin sonst eigentlich nur in python unterwegs)
super Arbeit

**Comment by rphl** [comment]
So Update ist online. Es können jetzt beliebig viele Tage gecached/angezeigt werden. Aktuell sind es 14Tage. Gerne mal testen. Siehe auch hier. https://github.com/rphl/corona-widget/blob/master/README.md
