### ISSUE TITLE
Anzeige keine Darstellung 

### ISSUE THREAD

**Issue by kermit1984** [rphl/corona-widget#28]
Hallo, ich habe das Widget installiert aber irgendwie zeigt er mir nicht die Daten an die er laut deinem Screenshot anzeigen soll. 
![F362230B-3627-4F70-8B0A-187490E8FE3B](https://user-images.githubusercontent.com/73926233/98072591-a776a480-1e66-11eb-8a27-19b49c2e7e08.jpeg)

Danke schon mal
Gruß 
Kermit

**Comment by TheSpirit** [comment]
Heute gibt es. Ich keine neuen Daten.

**Comment by kermit1984** [comment]
Das Gleiche hatte ich gestern aber auch.

**Comment by firebowl** [comment]
Liegt wohl am RKI, wenn man direkt dort nachschaut dann bekommt man die Info, dass die Zahlen teilweise noch nicht aktualisiert wurden. Nürnberg hat z.B. die Zahlen von gestern.

**Comment by kermit1984** [comment]
Wie schon geschrieben, seit gestern keine Änderungen, innerhalb von 24 Stunden sollten da ja schon neue Zahlen kommen.

**Comment by 1rNidiD** [comment]
Wenn du genau 24h gewartet hast, wird es keine neue Daten geben. Sobald das RKI neue Daten veröffentlich, können neue Daten geladen werden und dann muss man wieder warten bis es neue Daten gibt. 
Im Widget wird alles automatisch dargestellt und aktualisiert.

Allerdings machts bei mir auch gerade Probleme. Mal abwarten ob's da iwelche Probleme beim RKI gibt oder sowas..

**Comment by smar77** [comment]
Ging gestern schon los mit R 0. 
Vielleicht könnte man das Script so umbauen, dass es als failover die letzten Daten aus dem/n json anzeigt. Dann wäre zumindest das Widget nicht blank.

**Comment by kermit1984** [comment]
Ok, danke euch für die Infos, dann warten wir mal ab.

**Comment by rphl** [comment]
Wie schon einige bemerkt haben, hat das RKI Probleme beim update. Was dazu führt das keine Daten abgerufen werden können. Bzw das Daten fehlerhaft abgerufen werden, was dazu führt das nicht angezeigt werden kann.

Auch scheinen hier sich die Strukturen, für den R-Wert geändert zu haben, was einen R 0 zur folge hat. 
Hier heisst es nur abwarten (13 Uhr?) Bevor ich Änderungen vornehme.

Anscheinend kommen jetzt zumindest schon mal valide, aber nicht aktuelle Daten, aus der Api.

> Vielleicht könnte man das Script so umbauen, dass es als failover die letzten Daten aus dem/n json anzeigt. Dann wäre zumindest das Widget nicht blank.

@smar77  Danke fürs feedback. Das ist bereits vorgesehen. Auch mit einer Kennzeichnung.

**Comment by kersten-lohmeyer** [comment]
Jetzt grad kamen aktuelle Daten.

**Comment by EscolarProgramming** [comment]
> Auch scheinen hier sich die Strukturen, für den R-Wert geändert zu haben, was einen R 0 zur folge hat.
> Hier heisst es nur abwarten (13 Uhr?) Bevor ich Änderungen vornehme.

https://github.com/rphl/corona-widget/blob/master/incidence.js#L392 und https://github.com/rphl/corona-widget/blob/master/incidence.js#L396 muss `'Schätzer_7_Tage_R_Wert'` auf `Punktsch„tzer des 7-Tage-R Wertes` (ja, mit dem Gänsefüßchen statt dem ä) abgeändert werden, dann funktioniert der R-Wert wieder

**Comment by rphl** [comment]
Das mit dem R-Wert ist mir auch aufgefallen :-(

Heute Abend/Morgen Vormittag gibt es ein Update zum Widget, wo ich auch #22 angepasst habe.

**Comment by EscolarProgramming** [comment]
Inzwischen haben sie ihre CSV wieder geändert, der alte Wert (Schätzer_7_Tage_R_Wert) ist wieder der Spaltenname

**Comment by rphl** [comment]
> Inzwischen haben sie ihre CSV wieder geändert, der alte Wert (Schätzer_7_Tage_R_Wert) ist wieder der Spaltenname

Das mit CSV hatte ich schon vermutet. Im hetigen Update gibt es jetzt eine Config dafür damit man schneller drauf reagieren kann falls sich wieder unerwartet ändert :-(

Gerne mal testen. Und ggfls Ticket wieder öffnen.

Siehe auch hier. https://github.com/rphl/corona-widget/blob/master/README.md
