### ISSUE TITLE
R-Wert am iPhone 8 verschoben....

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#30]
![IMG_3034517200A6-1](https://user-images.githubusercontent.com/8932465/98230424-68764b00-1f5b-11eb-9b88-8d8b602731a7.jpeg)
...sieht super aus...danke ...am iPad 12,9 passt es ...am iPhone 8 ist der R-Wert etwas verrutscht......???

**Comment by rphl** [comment]
Ups. Sehe die Fälle für Bund sind total Verschoben 🤔

**Comment by rphl** [comment]
Hmm. Bei mir auf dem 8er Passt es:
![IMG_0127](https://user-images.githubusercontent.com/97642/98231550-d7a06f00-1f5c-11eb-8aa4-65c87135653c.jpg)


Hast du evtl den Anzeigezoom an?

**Comment by STJIKA** [comment]
> Hmm. Bei mir auf dem 8er Passt es:
> ![IMG_0127](https://user-images.githubusercontent.com/97642/98231550-d7a06f00-1f5c-11eb-8aa4-65c87135653c.jpg)
> 
> Hast du evtl den Anzeigezoom an?

...Anzeigezoom ist aus... bzw. "Standard"..........?????????????????

**Comment by STJIKA** [comment]
> > Hmm. Bei mir auf dem 8er Passt es:
> > ![IMG_0127](https://user-images.githubusercontent.com/97642/98231550-d7a06f00-1f5c-11eb-8aa4-65c87135653c.jpg)
> > Hast du evtl den Anzeigezoom an?
> 
> ...Anzeigezoom ist aus... bzw. "Standard"..........?????????????????

![IMG_F9007F8A4654-1](https://user-images.githubusercontent.com/8932465/98233432-53032000-1f5f-11eb-8b7d-61ef08c34250.jpeg)
...könntest du das so verschieben.....wenn es nicht zu viel Aufwand macht.....das wäre "symmetrischer...und optisch noch ansprechender...denk ich.....

**Comment by smar77** [comment]
![IMG_4812](https://user-images.githubusercontent.com/55975733/98233927-f8b68f00-1f5f-11eb-9d4c-d7e048a35b8d.jpg)

iPhone XS Max
oben rechts, die neuen Fälle werden nicht ganz dargestellt. ab 5-stellig wirds eng da ...
sonst top!

**Comment by rphl** [comment]
Das Layoutsystem von Scriptable ist leider sehr eingeschränkt. Es muss auf allen Geräten iwie passen. 

> ...könntest du das so verschieben.....wenn es nicht zu viel Aufwand macht.....das wäre "symmetrischer...und optisch noch ansprechender...denk ich.....

@STJIKA gerne ein PullRequest dazu erstellen. 

@smar77 hast du eine andere Schrift eingestellt? Die sieht "fett" nicht "normal" aus. 🤔

**Comment by smar77** [comment]
interessant. hab (hatte) BoldText in den iPhone settings aktiv. schlechte Augen ... 
wenn ich das ausschalte passt es! Danke, das reicht mir als Antwort :-)

**Comment by rphl** [comment]
Danke für die Info. 
Evtl. kann man in ScriptableWidget eine andere, als die Systemschrift nutzen. Die dann die "Systemeinstellungen" ignoriert.
Bei Gelegenheit checke ich es mal.

**Comment by dennerforen** [comment]
![IMG_5167](https://user-images.githubusercontent.com/73590285/98247788-5c4ab780-1f74-11eb-881f-c7e83e8d9a25.jpeg)

So sieht es auf einem SE 1 aus

**Comment by exneralex3009** [comment]
@dennerforen, welche Script hast du den da alle vereint. Kannste mir mal die links schicken?

**Comment by dennerforen** [comment]
.die beiden oberen sind aus einem privaten Projekt, weil noch auf die Freigabe vom Its Register gewartet wird:

https://gist.github.com/kevinkub/46caebfebc7e26be63403a7f0587f664#gistcomment-3513210

Mitte und Rechts ist das Script hier, das car Parking Script ist aus scripdu von Kevin 


https://scriptdu.de/

Unten ist von tzschies

https://gist.github.com/tzschies/be551cc6939e7c1469c2e8407edab517

**Comment by exneralex3009** [comment]
@dennerforen, danke

**Comment by rphl** [comment]
> So sieht es auf einem SE 1 aus

@dennerforen Wie schon oben erwähnt liegt das am Anzeigezoom wenn man kein Standard genutzt (und oder veränderter Systemschriftart) Konnte es so reproduzieren.

Ich glaube auch die Darstellung der Widgets in der Sidebar ist kleiner wie auf dem HomeScreen. _Das müsste ich aber noch prüfen_ 🤔

Hier vergrößert iOS die Schriftgröße, dadurch verändern sich aktuell die Abstände/Dimensionen unvorteilhaft wenn man die diese Bedienungshilfe an hat. Scriptable hat leider kein wirkliches AutolayoutSystem wie eine native App in ObjC/Swift 🤷‍♂️

Gerne ein PR mit Korrekturen für Darstellung mit Anzeigezoom/Anderen Schriftschnitten erstellen: https://github.com/rphl/corona-widget/pulls

![image](https://user-images.githubusercontent.com/97642/98263846-8ce81c80-1f87-11eb-90a8-862d0ba383ed.png)

**Comment by dennerforen** [comment]
Hi, das gibt es auf dem SE 1 nicht, ist aber nicht wichtig, mich stört es nicht. Für mich sind die Inhalte wichtig.

**Comment by dennerforen** [comment]
Seit dem letzten Update sieht man auf einem SE 1 nichts mehr. 

Ist es sinnvoll eine Nachkommastelle anzuzeigen?

**Comment by rphl** [comment]
So war das nicht geplant als ich den PR akzeptiert hab 😬

**Comment by TheSpirit** [comment]
Sorry. Der PR war von mir und ich nutze das ganze auf eine iPhone XR. 
Gibt es die Möglichkeit zu erkennen auf welchem Gerät das Widget läuft?

**Comment by rphl** [comment]
Es ist leider immer noch das Thema mit dem Font Scaling -.-

@TheSpirit Ich werde mal kurzfristig deine Änderung rückgängig machen. 
Evtl kann ich mal am Wochenende endlich das mich dem Fontscaling checken.

**Comment by TheSpirit** [comment]
Ok.

**Comment by rphl** [comment]
Wenn ich das mit dem Fontscaling drin hab, packe ich deine Änderung wieder rein.

**Comment by TheSpirit** [comment]
hab mal nen neuen pull request gemacht (siehe auch commenat #54)

**Comment by dennerforen** [comment]
Geht wieder auf dem SE

Danke
