### ISSUE TITLE
Ich verstehe nicht wie man es einstellt

### ISSUE THREAD

**Issue by Tiger088075** [rphl/corona-widget#34]
Hallo lieber Entwickler ich verstehe nicht wie man das Widget einrichtet also wie man den Landkreis usw. festlegt. Könnten sie mir dabei helfen?

**Comment by rphl** [comment]
Hallo. Steht in der Readme. Aber in Kürze:

**1. Koordinaten ermitteln**
* Karten App öffnen
* Zum Landkreis gehen
* Marker setzen (lange auf karte tippen)
* Breiten/ Längengrad kopieren

**2. Komma in Breiten/Längengrad durch Punkt ersten: 54,49324 wird 54.4932**

**3. Widget Parameter setzen**
* Lange auf Widget tippen
* Widget bearbeiten
  * Script auswählen
  * Parameter setzen z,B `0,{BREITENGRAD},{LÄNGENGRAD},{NAME}`

Weitere Detail zur Konfiguration: https://github.com/rphl/corona-widget/blob/master/README.md

**Comment by Tiger088075** [comment]
Hey, aber ich verstehe die Readme ja nicht

**Comment by Tiger088075** [comment]
Und auch nicht mit den Offline Modus

**Comment by Tiger088075** [comment]
Und wo genau muss man das eintragen im Script?

**Comment by Tiger088075** [comment]
Was hat es mit der 0 aufsich vor dem Längen und Breitengrad

**Comment by Tiger088075** [comment]
![image](https://user-images.githubusercontent.com/54439458/98307598-63021a80-1fc6-11eb-9b0b-eec9a48ed483.jpeg)

**Comment by Tiger088075** [comment]
Der Fehler erscheint

**Comment by Tiger088075** [comment]
![image](https://user-images.githubusercontent.com/54439458/98308598-bd9c7600-1fc8-11eb-93a7-452bf1b0fc26.png)![image](https://user-images.githubusercontent.com/54439458/98308749-24219400-1fc9-11eb-8090-490fe76e1588.jpeg)
Habe die Schritte befolgt und es geht nicht warum??????????

**Comment by Tiger088075** [comment]
Das was bei Notizen steht habe ich in den Parameter eingetragen

**Comment by Tiger088075** [comment]
Hallo lieber Entwickler ich möchte einen Fehler melden. Wenn man das Widget über die Galerie Herunterlädt funktioniert es nicht egal was man macht. Man muss den Script Code aus dem Internet nehmen

**Comment by schlotterp** [comment]
Könnte man das mal anhand eines Screenshots darstellen wo was eingetragen werden soll?

Danke.

**Comment by jipp** [comment]
Ich kann bestätigen, dass das Widget nur funktioniert wenn es aus dem gist kopiert wird.
über die Galerie wird es zwar installiert, aber es funktioniert nicht richtig - unter anderem wird im cache folder keine json Datei angelegt (der Folder wird angelegt). Das führt dazu, dass die cacheid auch nicht gefunden werden kann (kein cache file, keine id)

**Comment by Tiger088075** [comment]
Ja und ich habe das gestern über die Galerie 4Stunden Probiert...

**Comment by tzippy84** [comment]
Hab zum Glück nur eine Stunde verschwendet =)

**Comment by rphl** [comment]
Sorry für den umstand, die Scriptable Gallery jedoch ist noch sehr rudimentär und updates nur schwierig möglich :-(

Gerne lieber direkt hier fragen ;-)
