### ISSUE TITLE
Widget wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by Tiger088075** [rphl/corona-widget#35]
Hallo lieber Entwickler bei mir wird auf meinem IPhone (IPhone SE 1st Generation) das Widget nicht korrekt angezeigt und manche Sachen garnicht. Was muss ich tun? Anbei noch ein Screenshot 
![image](https://user-images.githubusercontent.com/54439458/98311041-b2e4df80-1fce-11eb-8c24-88fc52dfd63e.jpeg)

**Comment by Mathias1103** [comment]
Das ist schon richtig so. Du musst ein paar Tage warten, da Daten aus mehreren Tagen vorliegen müssen für das Script.

**Comment by rphl** [comment]
Jepp das dauert 1-2 Tage. Weil erst dann Daten zur Berechung stehen.

Und Falls du die Verschiebungen meinst, liegt das am Anzeigezoom. Siehe auch Ticket #30

**Comment by Tiger088075** [comment]
Bei mir ist der Anzeigezoom auf ganz klein glaube ich

**Comment by rphl** [comment]
Kann auch an anderer Schrift, bzw. Gerät liegen. 🤷‍♂️ Deine Ansicht kann ich nur mit dem Anzeigenzoom Reproduzieren.

Um die Verschiebungen kann ich mich evtl. am Wochenende kümmern. Oder jemand (in #30) stellt einen ersten PRs bereit.

**Comment by Tiger088075** [comment]
Alles gut an der Verschiebung liegt es nicht meinte nur wegen den Werten.

**Comment by rphl** [comment]
Ok. ich mache das mal dann zu. Wenn die Tage kein Trend angezeigt wird, gerne wieder öffnen.
