### ISSUE TITLE
Cache ID

### ISSUE THREAD

**Issue by kwieser76** [rphl/corona-widget#36]
Servus ,
Ich bekomme immer Fehler .
Wo muss ich diese Cache if setzen ?
Wo finde ich diese id?
Und im Widget Parameter habe ich ja nur ein Feld wo man die lokalen Koordinaten eingibt 

2020-11-06 07:28:17: No cache id in "WidgetParameter" found. See readme.

![image](https://user-images.githubusercontent.com/36126491/98333983-2a803200-2002-11eb-833e-acf7ee28c3f0.png)

![image](https://user-images.githubusercontent.com/36126491/98334036-4552a680-2002-11eb-9238-7e6c8d421472.png)

![image](https://user-images.githubusercontent.com/36126491/98334056-56031c80-2002-11eb-8ba8-7d0567dc939c.png)

**Comment by Eeewald85** [comment]
Zwischen den Koordinaten in den Widget Parametern darf kein Leerzeichen sein. Und das Komma in den Koordinaten muss ein Punkt sein (also 50.1234...), und schreib für die 50 noch eine 0. 

Zum Beispiel: 0,50.1620537,8.5526

**Comment by dennerforen** [comment]
Da die Werte nicht Hausnummer bezogen ausgewertet werden, reicht
 0,50.16,8.55

**Comment by iWampy** [comment]
Die Fehler hatte ich auch. Das liegt daran, das in dem Script aus der Gallery in Scriptable leider ein Fehler ist, wenn noch keine alte Daten vorliegen. 
Benutze das Script hier von Github und kopiere es in Scriptable. Dann kannst du die Werte so eintragen wie oben angegeben. 
In der Gallery ist leider nicht die letzte Version vorhanden. 

Die CacheID ist nur optional für den OfflineModus. 
Aber wenn du diese verwenden möchtest, dann findest du das JSON auf deinem iPhone unter Dateien > iCloucd > Scriptable > CoronaWidget
Die Info wäre eventuell auch was für die Readme.

**Comment by rphl** [comment]
Hello. 
> Die Info wäre eventuell auch was für die Readme.

Habe das mit dem Cacheordner in die Readme eingetragen ;-)


> Ich bekomme immer Fehler .
> Wo muss ich diese Cache if setzen ?
> Wo finde ich diese id?
>Und im Widget Parameter habe ich ja nur ein Feld wo man die lokalen Koordinaten eingibt

>2020-11-06 07:28:17: No cache id in "WidgetParameter" found. See readme.

Problem ist leider aktuell die Script Version in der Scriptable Gallery: Siehe auch: https://github.com/rphl/corona-widget/issues/38

Gerne die aktuelle version aus dem Repo hier testen.
