### ISSUE TITLE
Balken fehlen, R-Wert falsch

### ISSUE THREAD

**Issue by GithubPoot** [rphl/corona-widget#37]
Hallo...

Seitdem ich am gestrigen Abend den Code vom 5. November verwende, werden bei mir im unteren Bereich des Widgets keine Balken mehr angezeigt.
Außerdem gibt das Widget einen R-Wert von 1,02 aus, obwohl er laut andere Quellen bereits seit Tagen unter 1 liegt.

![0615C997-A37F-45AD-B481-27C19DA72775](https://user-images.githubusercontent.com/74044561/98344114-10028480-2013-11eb-8325-8960f719f298.jpeg)

... da ich allerdings gerade meine ersten Erfahrungen überhaupt in diesem Bereich mache, ist es durchaus möglich, dass sich der Fehler vor dem Bildschirm befindet. ;)

Eventuell notwendige Zusatzinformation:
iPhone 11, iOS 14.2

**Comment by GithubPoot** [comment]
Eventuell notwendige Zusatzinformation:
iPhone 11, iOS 14.2

**Comment by rphl** [comment]
Das mit den unteren Diagramen ist komisch 🤔

Wäre super wenn du hier deine Widgetparameter posten könntest die du verwendest. 
Und am besten auch die *.JSON Dateien aus dem Cache ordner: (Ich meine nicht die JS)
**"Dateien (App) > iCloud > Scriptable > coronaWidget"**

Dann kann ich es mir anschauen.

**Comment by GithubPoot** [comment]
So sei es.
Die Parameter lauten:

> 0,51.3260,6.5058;1,51.3400,6.5938

Und anbei die beiden JSONs:

[JSON.zip](https://github.com/rphl/corona-widget/files/5500445/JSON.zip)

**Comment by rphl** [comment]
So wie es aussieht haben einige Tage keine Zahlen für die neuen Fälle gespeichert.
Den Grund kenne ich noch nicht wirklich.

Habe jedoch einen Fix online gestellt der diese Daten Ignoriert, und es werden nur die "gültigen" anzeigt.

![image](https://user-images.githubusercontent.com/97642/98414088-03b21200-207b-11eb-896c-087b0a8b8079.png)

**Comment by GithubPoot** [comment]
Besten Dank!
