### ISSUE TITLE
ℹ️ HINWEIS! Version in Gallery ist aktuell defekt. Die aktuelle aus dem Repo hier nehmen!

### ISSUE THREAD

**Issue by rphl** [rphl/corona-widget#38]
Hello. Wie einige festgestellt haben ist die Version in der Scriptable Gallery leider defekt. 😬

Bitte am besten die Version aus dem Repo hier nehme.

**Update in der Scriptable Gallery is angefragt!**

**Comment by momab** [comment]
Gibt es einen ungefähren Ausblick, ob das Widget aus der Galerie irgendwann wieder funktioniert?

**Comment by rphl** [comment]
Einige male bereits ein Update eingereicht. Aber bisher erfolglos :-(
