### ISSUE TITLE
R Wert

### ISSUE THREAD

**Issue by dennerforen** [rphl/corona-widget#4]
Danke für das R Wert Widget.

**Comment by rphl** [comment]
Ich baue den R-Wert im nächsten Update ein. Dann ist kein separates Widget nötig. So soll es ungefähr aussehen.

![image](https://user-images.githubusercontent.com/97642/97633319-341efe00-1a34-11eb-9558-b70635d2ee08.png)

**Comment by dennerforen** [comment]
Perfect, danke. 

Der Beta Widget zeigt bei mir allerdings den R wert vom 24.10 an.

**Comment by rphl** [comment]
Dies ist die offizielle Quelle vom RKI. Obwohl da "tägliches Update" steht, hinken die Wohl etwas hinterher: 
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.html

Wenn ich soweit bin, checke ich es nochmal. Ansonsten bin ich für Infos & andere Quellen dankbar.

**Comment by rphl** [comment]
Glaube das Datum in der CSV ist eher irreführend. Das Widget gibt 1,17 als "letzten" 7-Tage RWert zurück, was dem heutigen (29.10) Situationsbericht entspricht (1,17) 🤔
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Okt_2020/2020-10-29-de.pdf?__blob=publicationFile

---
<img width="630" alt="Bildschirmfoto 2020-10-29 um 23 16 32" src="https://user-images.githubusercontent.com/97642/97638574-23bf5100-1a3d-11eb-8a42-afb6088fec5a.png">

**Comment by TheSpirit** [comment]
der trendplot unterhalb der zahlen mit "nach unten" gerichteten balken finde ich irgendwie komisch. hab da immer "negative" zahlen im kopf.
ich denke der plot sollte schon nach "oben" gerichtet sein.

**Comment by rphl** [comment]
Update mit R-Wert ist online. Gerne testen.
