### ISSUE TITLE
R Werte unterscheiden sich zw. Code vom 5. und 6. November

### ISSUE THREAD

**Issue by isotopeRal** [rphl/corona-widget#40]
Zu allererst ein großes Lob für dieses tolle Widget. 
Irgendwie verwirrt mich die Darstellung des R-Wertes:
![830D3790-9703-4A69-A0BE-01448AB50864](https://user-images.githubusercontent.com/46352622/98405203-238e0980-206c-11eb-8601-06a5003e0d9d.jpeg)
![F1A4CEEF-12A7-4AE0-8695-F394F98ADB45](https://user-images.githubusercontent.com/46352622/98405206-24bf3680-206c-11eb-946e-b007a28a54e8.jpeg)
Anbei Screenshots des Widgets in einer Version vom 5.11. und 6.11. erstellt innerhalb einer Minute am gleichen Ort. Wie kann es sein, dass der R Wert unterschiedlich ist. Welcher ist richtig bzw. entspricht dem des RKI?

Add on Frage: die Inzidenz wird ohne Nachkommastelle angezeigt obwohl diese laut Code auf eine Nachkommastelle gerundet werden soll (zumindest soweit ich den Code verstehe). 

Nochmals danke für dieses Widget und die Zeit die du da investierst

Ps: runs on iPhone X and iOS 14.2

**Comment by rphl** [comment]
In der Version vom 5. wurden nur die Spaltennummern verwendet weil das RKI Tage zuvor an die Spaltennamen vergeigt hat.
Hier nochmal die Quelle: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile

Danach habe ich es wieder auf die Spaltennamen, jedoch mit einer Variable geändert (Siehe Zeile43 `CONFIG_CSV_RVALUE_FIELD`)

Aktuell ist 1,00 Richtig. Wobei eher präzise 0,99... Das Runden checke ich mal...

<img width="367" alt="Bildschirmfoto 2020-11-06 um 20 28 38" src="https://user-images.githubusercontent.com/97642/98406866-00b12480-206f-11eb-850f-043efa75ff17.png">

**Comment by rphl** [comment]
Ein Update ist online. Das mit der Nachkommastelle sollte gefixed sein.
