### ISSUE TITLE
Wie kann ich zwei Werte nebeneinander anzeigen

### ISSUE THREAD

**Issue by jta1996** [rphl/corona-widget#41]
Bekomme es nicht hin, zwei verschiedene Werte/Städte nebeneinander anzuzeigen. Längen und Breitengrad habe ich jeweils als Parameter angegeben. 
![25616F53-1A23-45A9-8E52-432E744EA983](https://user-images.githubusercontent.com/74073430/98410148-67850c80-2074-11eb-87be-2fa3eb6c8926.png)

**Comment by rphl** [comment]
Die Parameter müssen die Position beinhalten::

0 = Erste
1 = Zweite

WidgetParameter müsste also wie folgt lauten: `0,{LAT},{LONG};1,{LAT},{LONG}`

Siehe auch: https://github.com/rphl/corona-widget#static-coordinatesmediumwidget

**Comment by jta1996** [comment]
Ich trage es folgendermaßen ein: 

0,53.545009,10.007784;1,53279142, 10.382403
und es wird mit trotzdem nur eins angezeigt.

**Comment by caliban73** [comment]
Probiere es doch mal so:

1,53.54 , 10.00 ; 0,53.27 , 10.38

**Comment by rphl** [comment]
Bei der zweiten Position Hast du einen Punkt vergessen.
Es müsste heißen:

0,53.545009,10.007784;1,53.279142, 10.382403

**Comment by dennerforen** [comment]
Wegen der Koordinaten kann man auch kürzen, 

Zwischen 53.54 und 53,64 oder 53,44 liegen jeweils 11 km 

Erspart vertippter und reicht für Landkreis. Würde sogar 53,5 reichen.
