### ISSUE TITLE
Bei den 14-Tage-Diagrammen steht nur n/v

### ISSUE THREAD

**Issue by MickyRoth** [rphl/corona-widget#42]
Fehler, oder müssen sich erst die Daten über die Tage ansammeln?

**Comment by Themivoc** [comment]
Habe auch gerade gelernt dass die Daten wohl erst über die Tage gesammelt und lokal gespeichert werden müssen

**Comment by rphl** [comment]
Ja Trend / Neue Fälle sind erst nach 1-2 Tagen verfügbar. 
Ich mache das mal hier zu. Falls was ist gerne hier Fragen #6
