### ISSUE TITLE
Eingabe von zwei festen Orten 

### ISSUE THREAD

**Issue by toby479** [rphl/corona-widget#43]
Hallo, ich bekomme es einfach nicht hin, das ich zwei feste Städte habe. Es wird immer nur die aktuelle Stadt per gps bei mir Viersen angezeigt.

Ich bekomme einfach die Eingabe nicht hin und wo muss das eingetragen werden.
Habe es die ganzen Abend probiert und egal was ich mache geht es nicht.

Sorry für die Frage, das ist absolutes Neuland für mich

**Comment by GithubPoot** [comment]
Um welche Städte geht es denn?
Dann schicke ich dir die Parameter, die du dafür eintragen musst…

**Comment by toby479** [comment]
Hallo das geht einmal um 47918 Tönisvorst, und Krefeld. 

Und einmal auf einen andere Gerät wollte ich 47918 Tönisvorst und Düsseldorf.

Auch bitte die Info wo ich es eintrage, ich finde es einfach nicht in den ganzen Zeilen.

Das wäre super nett, vielen dank

Von meinem iPhone gesendet

**Comment by GithubPoot** [comment]
Das... ist insofern relativ einfach, als dass ich ebenfalls 47918 Tönisvorst und Krefeld in meinem Widget anzeigen lasse.
Welch eigentümlicher Zufall. 😅

Die Parameter für die erste Option lauten:
0,51.3260,6.5058;1,51.3400,6.5938

Die Parameter für TöVo und Düsseldorf wären dann:
0,51.3260,6.5058;1,51.2328,6.7843

Einfügen musst Du diese Zeile in das Widget-Parameter-Feld, nicht in den Code selber. Der bleibt unberührt.

![IMG_5452](https://user-images.githubusercontent.com/74044561/98448292-4c290880-212b-11eb-9357-fef8c299df61.jpg)

Das Popup erreicht man, indem man den Finger länger auf dem Widget hält und dann "Widget bearbeiten" auswählt.

Wenn's jetzt immer noch nicht klappt, muss ich wohl vorbeikommen. Sollte ja nicht allzuweit sein. 😅
(Außer Du kommst aus Vorst. Da traue ich mich nicht hin. Pfui.)

**Comment by toby479** [comment]
Hatte gedacht ich muss es im Code selber eingeben.

Jetzt habe ich so gemacht, und es wird immer nur Viersen angezeigt. Ich habe auch die verschieden Größen versucht.

Werde es versuchen alles zu löschen und dann neu zu installieren, vielleicht geht es dann 

Von meinem iPad gesendet

> Am 07.11.2020 um 19:03 schrieb GithubPoot <notifications@github.com>:
> 
> 0,51.3260,6.5058;1,51.3400,6.5938
>

**Comment by MartinBraun135** [comment]
Hallo,
Ich hab‘s auch mit Programmmodifikationen probiert, über die Parameter hätte ich mir eine Nervenkrise erspart ! (.... und 2 Stunden !)


Mit freundlichen Grüßen

Martin Braun
(mobil)

**Comment by GithubPoot** [comment]
> Hatte gedacht ich muss es im Code selber eingeben. Jetzt habe ich so gemacht, und es wird immer nur Viersen angezeigt. Ich habe auch die verschieden Größen versucht. 

Das ist sehr seltsam.
Hast du den Code exakt so kopiert, wie ich ihn gepostet habe?
Und ist es die aktuelle Version des Scripts, die schon zwei Städte nebeneinander anzeigen kann?

Dann sollte es eigentlich so aussehen:

![IMG_5457](https://user-images.githubusercontent.com/74044561/98449582-f35e6d80-2134-11eb-8166-bbcd72720a51.jpg)

**Comment by toby479** [comment]
Hallo lauft, irgendwo war ein Fehler nach der Neuinstallation  hat es geklappt.

Und wenn ich das für eine andere Stadt nehmen möchte. Suche ich mir einfach Längen und Breiten grad raus



Von meinem iPad gesendet

**Comment by GithubPoot** [comment]
Wunderbar, dann ist ja alles bestens!

**Comment by toby479** [comment]
Vielen Dank für die Hilfe


Von meinem iPad gesendet

**Comment by rphl** [comment]
Habe mal die Readme aktualisiert: https://github.com/rphl/corona-widget/blob/master/README.md#konfiguration
