### ISSUE TITLE
add Help

### ISSUE THREAD

**Issue by UweLoyal** [rphl/corona-widget#44]
async createWidget() {
        const list = new ListWidget()
        // call Help
        list.url = "https://raw.githubusercontent.com/rphl/corona-widget/master/info.png";

Mit dem Aufruf von einer Hilfeseite kann man einige Missverständnisse und Rückfragen vermeiden.

LG
Uwe Loyal

**Comment by rphl** [comment]
Würde eher auf die Readme verweisen. Müsse ich eh nochmal Überarbeiten.

**Comment by UweLoyal** [comment]
Das ist sogar noch besser und ausführlicher!

LG
Uwe Loyal

Outlook<https://aka.ms/qtex0l> für iOS
________________________________
Von: Raphael <notifications@github.com>
Gesendet: Saturday, November 7, 2020 9:01:01 PM
An: rphl/corona-widget <corona-widget@noreply.github.com>
Cc: UweLoyal <Uwe.Loyal@Googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [rphl/corona-widget] add Help (#44)


Würde eher auf die Readme verweisen. Müsse ich eh nochmal Überarbeiten.

**Comment by rphl** [comment]
Url kann jetzt im Kopfbereich des Skriptes gesetzt werden, und muss nicht mehr im tiefen code geändert werden.
