### ISSUE TITLE
Anzeige des Ortes oder Landkreises ist ungenau

### ISSUE THREAD

**Issue by donfelipo** [rphl/corona-widget#45]
Hi zusammen,

Danke für das super Widget und die tolle Weiterentwicklung.
Mir ist hier noch folgendes aufgefallen, bzw. korrigiere ich das in jeder Version immer noch selbst.

In den Daten des RKI kommt es wohl im Feld areaName welches unter dem Inzidenz Wert liegt zu "Ungenauigkeiten". Hier bei mir z.B. der im Umland von München wohnt. Bei der Anzeige über Standortermittlung steht hier MÜNCHEN. Für das Stadtgebiet wird ebenfalls der gleiche Wert angezeigt.
Habe in den RKI Daten nun das Feld county ermittelt und in meiner lokalen Kopie des Script immer wieder angepasst.
Dann steht hier
LK München für den Landkreis
SK München für die Stadt

Vielleicht wäre das ja hier auch etwas für einen offiziellen Fix.

Viele Grüße

**Comment by rphl** [comment]
Ich finde es persönlich unschön wenn ich das immer "LK" davor stehen hab. In meinen Fall `LK Rhein-Kreis Neuss` bzw. `SK Düsseldorf`

Es gibt die Möglichkeit den Namen für die Postion in den WidgetParametern zu setzten. So das das Skript nicht angepasst werden muss. Du könntest also nur `X,50.1234,6.1235,LK München` in den WigetParametern setzen


Könnte mir aber eine alternative Darstellungsmöglichkeit dafür vorstellen. Denn es gibt deutlich mehr: **Landkreis,  Kreisfreie Stadt, Stadtkreis, Kreis, Kreis, Bezirk**

**Comment by rphl** [comment]
Hatte ein kleines Update online gestellt. Vor dem Namen wird jetzt ein Passendes Icon zum LK, KS, etc angezeigt. Kann mit `CONFIG_SHOW_AREA_ICON` wieder abgestellt werden.

**Comment by donfelipo** [comment]
Mega, vielen Dank.
Klasse Idee mit dem Icon. Du hattest schon recht, mit dem county Feld wird es auch nicht hübscher.

Schönen Abend dir noch.
