### ISSUE TITLE
Tippen auf a Widget leitet auf leere Seite

### ISSUE THREAD

**Issue by UweLoyal** [rphl/corona-widget#49]
Beim tippen auf das Widget wird man auf eine leere Webseite geleitet, ist das richtig?

(https://raw.githubusercontent.com/rphl/corona-widget/master/info.png)

LG
Uwe Loyal

**Comment by rphl** [comment]
Standardmäßig leitet das Öffnen immer noch auf das RKI Dashboard.

Du kannst die URL aber direkt im Kopfbereich des Skriptes setzen: z.B Das Infobild:
```CONFIG_OPEN_URL = "https://raw.githubusercontent.com/rphl/corona-widget/master/screenshots/info.png"```

oder die Hilfe:

```CONFIG_OPEN_URL = "https://github.com/rphl/corona-widget/blob/master/README.md#konfiguration"```

**Comment by UweLoyal** [comment]
Wie reported landet er bei mir auf eine leere Seite

"https://raw.githubusercontent.com/rphl/corona-widget/master/info.png"

[Image.jpeg]LG
Uwe Loyal

Outlook<https://aka.ms/qtex0l> für iOS
________________________________
Von: Raphael <notifications@github.com>
Gesendet: Monday, November 9, 2020 12:55:59 PM
An: rphl/corona-widget <corona-widget@noreply.github.com>
Cc: UweLoyal <Uwe.Loyal@Googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [rphl/corona-widget] Tippen auf a Widget leitet auf leere Seite (#49)


Standardmäßig leitet das Öffnen immer noch auf das RKI Dashboard.

Du kannst die URL aber direkt im Kopfbereich des Skriptes setzen: z.B Das Infobild:
CONFIG_OPEN_URL = "https://raw.githubusercontent.com/rphl/corona-widget/master/screenshots/info.png"

oder die Hilfe:

CONFIG_OPEN_URL = "https://github.com/rphl/corona-widget/blob/master/README.md#konfiguration"

**Comment by TheSpirit** [comment]
propier mal

https://raw.githubusercontent.com/rphl/corona-widget/master/screenshots/info.png

**Comment by rphl** [comment]
> Wie reported landet er bei mir auf eine leere Seite
>"https://raw.githubusercontent.com/rphl/corona-widget/master/info.png"

@UweLoyal  Hattest du diese Url selbst eingetragen? Standardmäßig ist die ja so nicht drin.
 Schon die probiert die ich (& TheSpirit) gepostet haben?

Verwendest du die letzten Version des Widgets?

**Comment by UweLoyal** [comment]
Eintrag in Script:
CONFIG_OPEN_URL = false
Mit neusten Script klappt jetzt alles.
Mich hat aber nur gewundert woher er die URL her hat.

LG
Uwe Loyal

Outlook<https://aka.ms/qtex0l> für iOS
________________________________
Von: Raphael <notifications@github.com>
Gesendet: Monday, November 9, 2020 7:27:13 PM
An: rphl/corona-widget <corona-widget@noreply.github.com>
Cc: UweLoyal <Uwe.Loyal@Googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [rphl/corona-widget] Tippen auf a Widget leitet auf leere Seite (#49)


Wie reported landet er bei mir auf eine leere Seite
"https://raw.githubusercontent.com/rphl/corona-widget/master/info.png"

@UweLoyal<https://github.com/UweLoyal> Hattest du diese Url selbst eingetragen? Standardmäßig ist die ja so nicht drin.
Schon die probiert die ich (& TheSpirit) gepostet haben?

Verwendest du die letzten Version des Widgets?
