### ISSUE TITLE
letztes Update Heute 09.11.2020

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#50]
Hey, nach dem Update von heute Mittag bekomme ich folgenden Fehler....??????
![IMG_00EB7BA25180-1](https://user-images.githubusercontent.com/8932465/98537663-df785000-2289-11eb-9b92-45df839a44c5.jpeg)

**Comment by rphl** [comment]
Ups. Da da habe ich was übersehen. Sollte korrigiert sein.
