### ISSUE TITLE
Widget für Schweiz

### ISSUE THREAD

**Issue by dennerforen** [rphl/corona-widget#51]
Ich habe noch kein Widget für die Schweiz gefunden, hat jemand von euch einen Tipp?

**Comment by smar77** [comment]
https://github.com/rsalzer/COVID_19_CH   ...  wäre ein Anfang. 

Du brauchst dafür erstmal die API's für die Daten. 
Dann müsstest du die in das vorhanden Script einbauen. Für einen Laien eher schwierig.
Vielleicht kann dir der Herr Salzer dabei helfen.

**Comment by smar77** [comment]
evtl hier mehr ...  https://github.com/openZH/covid_19

**Comment by dennerforen** [comment]
Thx. Ich werde mal Salzer anschreiben, vielleicht kann er Sonden Widget schreiben?

**Comment by rphl** [comment]
Hast sich wohl geklärt? Ich mache das mal hier zu, da ich nicht plane wirklich ein SchweizerWidget umzusetzen bzw. das anzupassen. 

Falls ihr es bereits angepasst habt, Gerne ein PR erstellen.
