### ISSUE TITLE
Dunkel-Dunkel-Rot bei Inzidenz über 200 wäre super

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#52]
Hi.
Bei uns in Bayern gibt es jetzt zu Dunkelrot auch noch Dunkel-Dunkel-Rot, falls die Inzidenz über 200 ist.
Kannst du das einbauen?
Danke

Hier sieht man es auf der Karte
https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/

**Comment by smar77** [comment]
Das ist sehr subjektiv und kann man selber machen. Zeile 41ff neue Variablen anlegen und Zeile 568ff einfach ergänzen.

Es wäre etwas praktischer, wenn man alle diese Einstellungen und Parameter in eine fixe libary packen und per import-module ins Script laden könnte. So wäre es leichter, wenn jemand paar optische Sachen anpassen möchte. Bei jedem Update fängt man sonst wieder von vorn an.

**Comment by TheSpirit** [comment]
hab es jetzt mal selbst eingepflegt
