### ISSUE TITLE
Auf kleinem Display nicht lesbar

### ISSUE THREAD

**Issue by dennerforen** [rphl/corona-widget#54]
Nach dem letzten Update (wohl Nachkomma eingeführt?) ist das Widget auf einem iPhone SE nicht mehr lesbar

![IMG_5183](https://user-images.githubusercontent.com/73590285/98933181-940baf00-24e0-11eb-9c8c-4edf1addd38a.jpeg)

**Comment by TheSpirit** [comment]
Sorry. Der PR war von mir und ich nutze das ganze auf eine iPhone XR.
Gibt es die Möglichkeit zu erkennen auf welchem Gerät das Widget läuft?

**Comment by dennerforen** [comment]
Auf iPad Pro 11 auch nicht optimal

![IMG_0771](https://user-images.githubusercontent.com/73590285/98933483-fbc1fa00-24e0-11eb-8eb5-3a1068fa53c9.jpeg)

**Comment by TheSpirit** [comment]
Als fix schau ich mal das man das konfigurierbar machen kann. 
Sorry nochmal

**Comment by rphl** [comment]
Es konfigurierter zumachen wäre zumindest erstmal ein Guter Workaround

**Comment by dennerforen** [comment]
sorry nicht notwendig, Verbesserungen bringen auch mal Probleme, wichtig ist, das man es korrigiert.

Allerdings finde ich die nachkomma Darstellung unnütz, den ob 159 oder 159,46734 ändert ja nichts. Zumal es bei z.bsp. 297.844 Leuten in DaDi würde bei

160 = 476,55 Infizierungen
159 = 473,57 Infizierungen

Bin mir nicht sicher, ob diese 3 Leute nicht in der generellen Schwankungsbreite eines indizienwertes untergehen.

Die Größe des Widgets ist ja auf allen Geräten mehr oder weniger beschränkt und für meine Sicht, wäre die Beschränkung auf aussagekräftige kurze Werte wichtiger, als mathematische Optimierungen.

**Comment by TheSpirit** [comment]
hab mal nen pull request gemacht. default mäßig werden die nachkommastellen nicht angezeigt, man hat aber jetzt die option dies zu tun

**Comment by rphl** [comment]
Zahlen werden wieder ab 100 abgeschnitten... mache das also mal zu :-)
