### ISSUE TITLE
Open RKI deaktivieren

### ISSUE THREAD

**Issue by IstvanTempfli** [rphl/corona-widget#56]
Bei mir `CONFIG_OPEN_URL = false` funktioniert nicht. 
Muss ich noch etwas umstellen um das Widget nicht mehr der RKI Website aufmacht?

**Comment by rphl** [comment]
Kann es nicht reproduzieren. 
Bitte dran denke es ist eine Konstante., und kann nicht zu einem späteren Zeitpunkt geändert werden.

d.H. es muss direkt auf false gesetzt werden, nicht später

```
Zeile 15: const CONFIG_OPEN_URL = false
```

**Comment by IstvanTempfli** [comment]
Der gleiche Code auf einem iPhone 11 funktioniert. Es liegt an der Scriptable und iPhone Model (12)?

**Comment by youmakemyday** [comment]
Wenn du mir dein 12 überlässt, probier ich's gern aus 😁
