### ISSUE TITLE
Lesbarkeit - Dunkeldunkel Rot bei > 200 optimieren

### ISSUE THREAD

**Issue by Rfiach** [rphl/corona-widget#57]
Zahlen sind nicht lesbar aktuell
![D2DBA50E-F749-46EF-9F2C-72EDA508A3F3](https://user-images.githubusercontent.com/74397552/99036083-5317a700-2581-11eb-8996-f4691749ac85.jpeg)

**Comment by TheSpirit** [comment]
es werden doch alle zahlen angezeigt

**Comment by firebowl** [comment]
Ich glaube er meint, dass aktuell im dark mode das dunkelrot schlecht lesbar ist.

**Comment by TheSpirit** [comment]
das ist auch kein dunkelrot, sonder dunkeldunkelrot
dunkeldunkelrot wird genutzt bei einer inzidenz > 200

**Comment by Rfiach** [comment]
Ja sorry, das ist korrekt.

**Comment by TheSpirit** [comment]
mal sehen ob man ein "helleres" dunkeldunkelrot nehmen kann

**Comment by smar77** [comment]
no offense, aber jetzt soll der hintergrund angepasst werden? machen wir ein bisschen heller? dann kommt der nächste, dem das zu hell ist, weil eigentlich ist es ja dark mode. usw. alles subjektiv und man dreht sich im kreis.

ich finde das sollte, sofern möglich, frei konfigurierbar sein. evtl via modul? aus dem script rausgelöst. 
oder in der section wo die ampelfarben definiert werden, könnte man auch die hintergrundfarben für die einzelnen stacks hinzufügen. so kann jeder seine farb und kontrasteinstellungen selber machen.

**Comment by dennerforen** [comment]
Zudem sollte ich in der Lage sein, auch ohne dark rot, die Bedeutung von einer 259 Inzidenz zu erfassen. 

Evtl kann man das darkrot auf das tagsüber Widget begrenzen, wenn man das überhaupt so dunkel haben will. 

Gefahr wird von Signalton signalisiert, nicht von einem fast braun.

**Comment by dennerforen** [comment]
Ich bin dafür das dunkelrot wieder aus dem Code zu entfernen, vorher war es gut, jetzt ist es schlecht.

**Comment by TheSpirit** [comment]
dann sollte aber konsequenterweise sowohl dunkelrot als auch dunkeldunkelrot entfernt werden

**Comment by rphl** [comment]
Ich werde mal die Farbabstufungen zwischen den Rots checken. 
So das ich das DD-Rot behalten kann, und es auch noch mit weniger Helligkeit bei DarkMode besser lesbar ist.

Bis dahin kann ja die Farbe von D-Rot `#a1232b` auch für DD-Rot verwendet werden.

Falls ihr bereits gute Abstufungen für das Rot habt, die gut mit Light/Darkmode funktionieren, gerne posten.

**Comment by rphl** [comment]
Für mich würden diese gehen. gerne feedback.
![farbcodes](https://user-images.githubusercontent.com/97642/99076296-2ed8bc00-25bb-11eb-876f-719dcd712ae5.png)

**Comment by TheSpirit** [comment]
Sieht gut aus hätt ich gesagt

**Comment by rphl** [comment]
Update mit den Farben ist online....

**Comment by Rfiach** [comment]
Perfekt! Danke für das Update und vor allem die sehr zügige Umsetzung. Danke!
