### ISSUE TITLE
Inzidenz-Wert ändert sich nicht

### ISSUE THREAD

**Issue by chimcen** [rphl/corona-widget#58]
Hi,

warum auch immer bleibt bei meinem Widget der Inzedenz-Wert seit Tagen bei 0,93...
Laut anderen Apps wäre der bei 0,79...

Habe auch schon das Script nochmals zur sicherheit aktualisiert - hat das sonst noch jemand?

**Comment by STJIKA** [comment]
> Hi,
> 
> warum auch immer bleibt bei meinem Widget der Inzedenz-Wert seit Tagen bei 0,93...
> Laut anderen Apps wäre der bei 0,79...
> 
> Habe auch schon das Script nochmals zur sicherheit aktualisiert - hat das sonst noch jemand?

...bei mir das gleiche mit 0.93.....?????

**Comment by rphl** [comment]
Das ist die Quelle https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile (Auch im Code wiederzufinden)

Das Widget zeigt den 7 Tage Schätzwert.  Die Spalte `Schätzer_7_Tage_R_Wert`. 
So wie ich das sehe, hat das RKI **(mal wieder)** den Namen der Spalte in `Punktschätzer des 7-Tage-R Wertes` geändert  :-(

Keine Ahnung ob das sich nicht wieder ändert...

**Comment by rphl** [comment]
Wenn Ihr ihr stabilere **offizielle** Quellen für den R-Wert findet gerne posten.

**Comment by chimcen** [comment]
Leider bisher nicht - alle scheinen Ihre Daten aus der Liste vom RKI zu ziehen...

**Comment by fireman130655** [comment]
Bei mir gerade R 0,00

**Comment by firebowl** [comment]
Stimmt, gerade auf 0,00 gesprungen.

**Comment by dennerforen** [comment]
Evtl beim ECDC?

https://reproduktionszahl-corona.de/

**Comment by dennerforen** [comment]
Script for downloading the CSV file into “R” software

https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

**Comment by chimcen** [comment]
Ausführliche Listen in div. Formaten - nicht schlecht.

Aber dort gibts die Daten ja nur Länderspezifisch. Ich denke hier ist der Inzedenz-Wert ja pro Landkreis oder @rphl?

**Comment by rphl** [comment]
Das Widget zeigt den Gesamt-R an.

...

Problem beim ecdc ist die Dateigröße. Jedes Mal ~3mb zu laden und zu Parsen ist suboptimal.

Außerdem ändert sich beim ecdc ab Dezember die Bereitstellung: 

> ECDC will switch to a weekly reporting schedule for the COVID-19 situation worldwide and in the EU/EEA and the UK from December this year. All daily updates will be discontinued from then.

**Comment by dennerforen** [comment]
ECDC berechnet den R wert pro Land, Bundesländer werden vom rki berechnet.

Rki berechnet auch den r wert für Deutschland, aber Lt. obigem Link:

Das RKI ermittelt die Reproduktionszahl anhand der dem RKI übermittelten Daten zu den bestätigten Fällen. Allerdings liegen diese Daten dem RKI mit einem gewissen Meldeverzug vor. Um diesen Meldeverzug auszugleichen und aktuelle Werte von R angeben zu können, wird ein statistisches Verfahren (das sogenannte Nowcasting) vorgeschaltet. Das RKI gibt wegen der statistischen Unsicherheit ein Konfidenzintervall an.


Manche geben auch nur einen 4 Tageswerk an. Da ich aber nicht täglich die Widgets austausche, ist der angezeigte Wert für mich genügend, da er ja immer gleich berechnet wird.

Und ob 1,09 oder 0,97 macht den Bock nicht fett.

ab 0,50 wird es interessant.

**Comment by rphl** [comment]
Finde der Wert ist für mich auch etwas zweitrangig. Da bin mit den Lokalen Inzidenz Werten für mein Gefühl besser über die Lage informiert.

Nichtdesto trotz... Wenn der Wert da ist, ist er ja auch Informativ und sollte stimmen 🤷‍♂️...

Habe mal jetzt eine option hinzugefügt, die aus der CSV die möglichen Spalten für den R-Wert sucht. (Bis das RKI wieder einen neuen Namen findet) 

Solange es keine vernünftige Api dazu gibt, werde ich erstmal bei der CSVLösung bleiben. Gerne also Berichten wenn das RKI mal wieder Namen würfelt 😄

**Comment by rphl** [comment]
Mache das erstmal hier zu da ein Update online. Gerne testen und ggfls wieder hier aufmachen.

**Comment by chimcen** [comment]
Merci 🤩

**Comment by fireman130655** [comment]
👏👏👏
