### ISSUE TITLE
R-Wert nur noch 0,00

### ISSUE THREAD

**Issue by compoundbow83** [rphl/corona-widget#59]
Seit zwei Tagen wird bei mir nur noch ein R-Wert von 0,00 angezeigt.
![IMG_9161](https://user-images.githubusercontent.com/74456101/99147146-cfdc7b00-267e-11eb-9a7d-8d296b34010c.jpg)

Kann ich das irgendwie selber beheben, oder an was liegt das?

**Comment by rphl** [comment]
Schau mal hier, das wurde bereits gemeldet und ist korrigiert. https://github.com/rphl/corona-widget/issues/58
