### ISSUE TITLE
14 tage Diagram 

### ISSUE THREAD

**Issue by marcuscgn** [rphl/corona-widget#60]
Der 14 Tage trend funktioniert nicht 
![IMG_8451](https://user-images.githubusercontent.com/73420542/99152641-43907f00-26a3-11eb-830b-d361d0e62f26.jpg)

**Comment by rphl** [comment]
Hmmm. Poste mal bitte deine Widgetparamter + die Jsons aus dem cache. Dann könnte ich es mal checken.

**Comment by marcuscgn** [comment]
die Jsons aus dem cache  wo finde ich die ? 
![IMG_8455](https://user-images.githubusercontent.com/73420542/99156228-84968c80-26bf-11eb-957e-d9d09ef77fcf.PNG)
![IMG_8456](https://user-images.githubusercontent.com/73420542/99156220-7e081500-26bf-11eb-903a-9888b8e4d203.PNG)

**Comment by fireman130655** [comment]
iCloud Drive - Scriptable - Corana Widget

**Comment by marcuscgn** [comment]
![IMG_8458](https://user-images.githubusercontent.com/73420542/99156537-d5a78000-26c1-11eb-8c2f-8d8ebb76023c.PNG)
![IMG_8457](https://user-images.githubusercontent.com/73420542/99156541-d9d39d80-26c1-11eb-9ed5-9d56c6c6c646.PNG)

**Comment by fireman130655** [comment]
Example: 51.3630,7.4810,Home,05914;1,51.5583,7.0649,GE,05513

**Comment by chimcen** [comment]
Funktioniert bei mir problemlos - wann hast Du denn das Widget hinzugefügt? Den 14 Tage Trend erhält man auch nur wenn das Widget seit 14 Tagen in Nutzung ist. D.h. man es auch min 1*täglich ausführt/anzeigen lässt, da bei nichtanteige auch keine Daten abgerufen und in Deinem *.json file in Deiner iCloud auch keine Daten für diese Tage dann gespeichert werden - falls ich damit falsch liege bitte berichtigen.

Deine bereitgestellten Screenshots bringen rhpl leider nichts. Er braucht den Parameter-String aus Deinem Widget (einfach hier rein kopieren) und die dazugehörige *.json (nicht *.js) Datei bzw. deren Inhalt...

**Comment by rphl** [comment]
@marcuscgn Wie schon von _chimcen_ erwähnt worden ist, muss das Skript aktiv in einem Widget eingebunden sein. z.B. Homescreen oder Seitenlleiste, da es aktiv die Daten holen muss. 

1. Es wäre super wenn du die Wigetparamter hier Komplett als Text Posten würdest (copy/paste)

2. Zu den Jsons: Diese findest du in der **Dateien (App)** > **Scriptable** > **coronaWidget (ordner)** > ***.json**


Es sieht aber so aus als ob für die "grauen" Tage nichts getrackt worden ist, weil des Skript nicht aktiv war. Denn nur 3 tage hintereinander zeigen z.B einen Trend an.

**Comment by marcuscgn** [comment]
So ? 

Es wird auch ab und zu nur eine Seite angezeigt :-/ 

050.861997, 6.930881,Home

`{"01.11.2020":{"area":{"incidence":205.4,"name":"Köln","dailyCases":-1,"areaCases":11122},"state":{"incidence":147.3,"name":"NRW","cases":136116,"dailyCases":-1},"d":{"incidence":103.4,"dailyCases":14177},"updated":"01.11.2020, 00:00 Uhr","updatedTS":1604185200000},"02.11.2020":{"area":{"incidence":216.8,"name":"Köln","dailyCases":394,"areaCases":11516},"state":{"incidence":151.8,"name":"NRW","cases":139485,"dailyCases":3369},"d":{"incidence":109.2,"dailyCases":12097},"updated":"02.11.2020, 00:00 Uhr","updatedTS":1604271600000},"05.11.2020":{"area":{"incidence":195.3,"name":"Köln","dailyCases":-1,"areaCases":12347},"state":{"incidence":168.3,"name":"NRW","cases":153766,"dailyCases":-1},"d":{"incidence":112.5,"dailyCases":19990},"updated":"05.11.2020, 00:00 Uhr","updatedTS":1604530800000},"08.11.2020":{"area":{"incidence":194.1,"name":"Köln","dailyCases":-1,"areaCases":13452},"state":{"incidence":165,"name":"NRW","cases":168205,"dailyCases":-1},"d":{"incidence":121.9,"dailyCases":16017},"updated":"08.11.2020, 00:00 Uhr","updatedTS":1604790000000},"11.11.2020":{"area":{"incidence":188.4,"name":"Köln","dailyCases":-1,"areaCases":14222},"state":{"incidence":167.9,"name":"NRW","cases":180523,"dailyCases":-1},"d":{"incidence":121.1,"dailyCases":18487},"updated":"11.11.2020, 00:00 Uhr","updatedTS":1605049200000},"12.11.2020":{"area":{"incidence":175.8,"name":"Köln","dailyCases":261,"areaCases":14483},"state":{"incidence":164.8,"name":"NRW","cases":185138,"dailyCases":4615},"d":{"incidence":120.4,"dailyCases":21866},"updated":"12.11.2020, 00:00 Uhr","updatedTS":1605135600000},"14.11.2020":{"area":{"incidence":176.7,"name":"Köln","dailyCases":-1,"areaCases":15232,"areaIBZ":40},"state":{"incidence":166,"name":"NRW","cases":196363,"dailyCases":-1},"d":{"incidence":122.3,"dailyCases":22461,"r":1.05},"updated":"14.11.2020, 00:00 Uhr","updatedTS":1605308400000,"rs":"05315"},"15.11.2020":{"area":{"incidence":174.3,"name":"Köln","dailyCases":283,"areaCases":15515,"areaIBZ":40},"state":{"incidence":165.7,"name":"NRW","cases":200063,"dailyCases":3700},"d":{"incidence":124.7,"dailyCases":16947,"r":1.05},"updated":"15.11.2020, 00:00 Uhr","updatedTS":1605394800000,"rs":"05315"}}`

**Comment by marcuscgn** [comment]
So sieht es jetzt aus. 

![IMG_8482](https://user-images.githubusercontent.com/73420542/99185705-da187b00-274b-11eb-90ae-900b8c53e5f9.jpg)

**Comment by chimcen** [comment]
Dein String gibt aber auch nur eine Location an... und ist leider auch bisserl falsch.

Richtig:
0,50.861997,6.930881,Home

Zwei Locations:
0,50.861997,6.930881,Home;1,Breitengrad,Längengrad,optional-eigenes-gewünschter-Städtename

**Comment by chimcen** [comment]
Oder falls die erste Stad per GPS und die zweite fix müsste es so aussehen (falls ich sas richtig verstanden hab ;) ):

1,50.861997,6.930881,Home

**Comment by marcuscgn** [comment]
der erste Ort soll home sein und der zweite GPS 
Sorry das ich so viel umstände mache

zwischen durch sieht es auch mal so aus :-/ 
![IMG_8499](https://user-images.githubusercontent.com/73420542/99189511-cd068680-2761-11eb-8490-db066fbfa42a.jpg)

**Comment by fireman130655** [comment]
Das Widget erkennt automatisch den Standort. Es ist jedoch möglich den Standort fest zu setzten. Die Koordinaten können z.B. über die Karten App ermittelt werden. Format: {POSITION},{LAT},{LON};{POSITION},{LAT},{LON}

{POSITION} = Position im Widget. z.B: 0=ErsterStandrt, 1=ZweiterStandort (Zweispaltes MediumWidget)
{LAT} = Breitengrad. z.B: 51.1234 (NICHT 51,1234 - Kein Komma!)
{LON} = Längengrad. z.B: 11.1234 (NICHT 11,1234 - Kein Komma!)
Beispiele

Erster Standort statisch (SmallWidget): 0,51.1244,6.7353
Zweiter Standort ist statisch (MediumWidget): 1,51.1244,6.7353
Beide Standorte sind statisch (MediumWidget): 0,51.1244,6.7353;1,51.1244,6.7353
Nur zweiter Standort ist statisch (MediumWidget): 1,51.1244,6.7353
Eigene Standortnamen

Standorte selbst bennenen. Format: {POSITION},{LAT},{LON},{NAME};{POSITION},{LAT},{LON},{NAME}

{NAME} = Name der anstalle der offizielen Bezeichnung aus der API verwendet wird.
Beispiele

Eigener Name z.B "Home" für den ersten Standort: 0,51.1244,6.7353,Home
Eigener Name z.B "Work" für den zweiten Standort: 1,51.1244,6.7353,Work
Offlinemodus

Falls mal keine Daten abgerufen werden können, kann der Offlinemodus eingerichtet werden. Dafür muss die CacheID gesetzt werden: Format: {POSITION},{LAT},{LON},{NAME},{CACHEID};{POSITION},{LAT},{LON},{NAME},{CACHEID}

Die {CACHEID} ist der numerische Teil der JSON Dateien die im Cacheordner zu finden sind: Dateien (App) > iCloud > Scriptable > coronaWidget > *.json

Beispiel:

Dateiname = coronaWidget01511.json CacheID = 01511
Cache für Düsselforf setzen: 0,51.1244,6.7353,Work,01511

**Comment by dennerforen** [comment]
.die Koordinaten kann man auf zwei nachkommastellen kürzen, zwischen 51.1 und 51.2 sind 13 km Luftlinie

**Comment by chimcen** [comment]
> der erste Ort soll home sein und der zweite GPS
> Sorry das ich so viel umstände mache
> 
> zwischen durch sieht es auch mal so aus :-/
> ![IMG_8499](https://user-images.githubusercontent.com/73420542/99189511-cd068680-2761-11eb-8490-db066fbfa42a.jpg)

Das ist kein Problem. Um es einfach zu beschreiben:
Trägst Du keine Koordinaten ein, ermittelt das Widget Deinen jeweiligen Standort und zeigt dessen Werte an.
Beim Doppel-Widget würde ohne Koordinaten zweimal der aktuelle Standort angezeigt.
Willst Du dass einmal der aktuelle Standort und als zweites ein fester Ort angezeigt wird, musst Du nur die Koordinaten des Festen Ortes angeben. Mit der führenden „0,“ oder „1,“ gibst Du nur an ob der eingegebene Standort als Erstes oder zweites angezeigt wird. 0 ist links, 1 ist rechts.

**Comment by rphl** [comment]
@marcuscgn Auf der zweiten Position funktioniert aktuell kein GPS. Du müsstest also nur den Parameter etwas anpassen. Dann würdest einfach nur GPS auf 1 und FEST (Home) auf 2 haben:

Müsste also nur lauten: `1,50.861997,6.930881,Home`

Danke für die JSON, wegen den Lücken werde ich es später mal checken.
