### ISSUE TITLE
Dunkeldunkelrot erst bei > 250 laut RKI

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#61]
Hi. 
Von mir kam ja das dunkeldunkelrot bei Inzidenz > 200. 
Hab heute gesehen, das das nur bei uns in Bayern beim LGL so ist. 
Auf der Seite vom RKI, wenn man sich das PDF zum R-Wert durchliest ist dunkeldunkelrot erst bei über 250. 
Kannst du das vielleicht anpassen?
Danke

LGL:
https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/

RKI:
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Nov_2020/2020-11-15-de.pdf?__blob=publicationFile

**Comment by rphl** [comment]
Habe mal das neue Limit aus der pdf übernommen. 

Deinen PR habe ich kommentiert
