### ISSUE TITLE
Darker colors too dark for dark mode

### ISSUE THREAD

**Issue by dersvenhesse** [rphl/corona-widget#62]
When using dark mode, the darker red colors are too dark to read:

![IMG_7254](https://user-images.githubusercontent.com/1202880/99193332-96883600-2778-11eb-808b-5f4acce9eac6.jpg)

**Comment by TheSpirit** [comment]
Nutzt du die aktuellste Version?

**Comment by dersvenhesse** [comment]
I thought I did, but apparently, the latest update didn't sync properly from my computer. The in https://github.com/rphl/corona-widget/commit/566e93a3bda5422c61223b3bde2c8adefea5be2d updated colors with work so much better. Thanks for the hint!
