### ISSUE TITLE
Caching suboptimal meiner Meinung nach

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#66]
Hi.
Das mit dem Caching ist meiner Meinung nach leider nicht die beste Idee.
Wenn ich am WE nicht in der Arbeit bin, kann dort der aktuell Wert nicht abgeholt werden und dann am Montag morgen, stimmen die berechneten Pfeile nicht und es fehlen die Werte eben vom Wochenende.
Auch in Landkreisen in denen ich nicht so oft bin, haben keine "alten" Daten.
Da finde ich mittlerweile die Idee von https://github.com/tzschies/incidence besser, da er sich die alten Daten holt.
Kannst du mal schauen, ob man das nicht einbauen kann, dann spart man sich das Caching und alle Probleme die damit einhergehen.
Euch für Leute die das Widget neu nutzen haben den Vorteil, sofort alle Daten der letzten 14 Tage zu sehen.
Das finde ich daher mittlerweile die elegantere Lösung.
Von der Art und Weise wie du die Daten anzeigst, finde ich deine Version aber definitiv die schönere.
Danke

**Comment by Dimakap** [comment]
Ich bin viel im Außendienst unterwegs und würde mich auch über eine Verbesserung der Darstellung freuen!

[image](https://user-images.githubusercontent.com/73642725/99526628-cc593480-299b-11eb-87a7-fa9fc87df48c.jpeg)

**Comment by TiborAdk** [comment]
Ich schätze einen Teil des Problems ließe sich leicht beheben, wenn man die Daten für Bund, Länder und Landkreise getrennt speichert und nicht die Daten von Bund und Ländern im Datensatz des Kreises speichert.
Dadurch könnte man zumindestens die Daten für Bund und Länder für mehrere Widgets nutzen und neue Orte können zumindestens bei diesen auf Werte aus der Vergangenheit zugreifen.

Das Problem, dass vergangene Daten für den Landkreis nicht zur Verfügung stehen, bzw, diese nicht aktualisiert werden, solange man nicht am entsprechend Ort ist löst, das natürlich nicht.

**Comment by rphl** [comment]
Über das habe bereits schon nachgedacht, aber noch nicht wirklich dazu gekommen. Bin auch kein wirklicher Pendler, deswegen war da nicht so die Prio drauf.

Hier müsste noch geprüft werden, was alles an "historischen" Daten als der Api ausgelesen / errechnet werden kann. 
So wie ich das auf den ersten Blick bei _tzschies_ sehe, sind es nur lokale Indizenzwerte. _(Erstmal nur seine doku gelesen)_

Für ein Update müsste man also checken wie/ob man **ALLE** historischen Werte ausgelesen bekommt:

* Stadt/Kreis: **inzidenz + gesamt fälle** oder **täglich neue fälle** _(sonst kann "tägl." aus dem gesamt diff. errechnet werden)_
  * - [x] Stadt/Kreis inzidenz  ist wohl möglich siehe _tzschies_
* Bundesland: **inzidenz + gesamt fälle** oder **täglich neue fälle** _(sonst kann "tägl." aus dem gesamt diff. errechnet werden)_
* Bund: **inzidenz + gesamt fälle** oder **täglich neue fälle** _(sonst kann "tägl." aus dem gesamt diff. errechnet werden)_


@TiborAdk Das mit dem Split macht auch sinn. Habe ich bereits in einem noch nicht veröffentlichen update umgesetzt. So wird auch der overhead an Daten kleiner. Hatte es im Zuge des Caching ohne cacheid umgebaut. So am Rande...

**Comment by TheSpirit** [comment]
Höhrt sich super an.

**Comment by h-johan** [comment]
Genau sowas hatte ich ja auch schon in #6 angemerkt (Hier nur in bezug auf Kreise, in denen man noch nicht war). Das Würde dann ja mit dem caching für unkonfigurierte widgets zusammenspielen (#64). Dann könnte man eine Datei, die die Widgets und die cacheId der Locations der Widgets speichert und cache dateien für bl (Gibt das Feld BL_ID in der db, soweit ich weiß), bund und kreis getrennt anlegen (Overhead reduzieren). Dann könnte das widget auch daten anzeigen, bevor der download der neuen daten abgeschlossen ist.

Sollte es nicht möglich sein, die daten aus der Vergangenheit abzufragen, könnte man doch eine methode einbauen, die die cacheIds der vorhandenen Cache dateien ausliest und dann im hintergrund aktualisiert, wenn internet vorhanden ist. Das sind ja maximal einige kb die da geladen werden.

@rphl Es scheint so als hättest du bezgl caching einiges in Arbeit / Planung. Gibt es da Möglichkeiten, sich dran zu beteiligen. Dieses widget ist m. M. n. das beste aktuell verfügbare corona widget.

**Comment by rphl** [comment]
> @rphl Es scheint so als hättest du bezgl caching einiges in Arbeit / Planung. Gibt es da Möglichkeiten, sich dran zu beteiligen. Dieses widget ist m. M. n. das beste aktuell verfügbare corona widget.

@h-johan Wenn das nächste Update fertig ist (habe bereits einiges strukturell geändert) kann ich mir eine Liste mit weiteren Features/Fixes vorstellen, an denen man sich gerne direkt beteiligen kann. 

Ab einen gewissen Zeitpunkt wären direkte Commits / PRs auch fein. Muss mir da aber noch was überlegen. Ich mache mal ein Features Ticket. Dann wird auch sichtbar was so grob geplant ist.

**Comment by rphl** [comment]
Bzgl. der historischen Daten. Soweit bekomme ich folgende Daten ausgelesen:

* **Stadt/Kreis:** 
  * täglich neue Fälle für X Meldetage 
  * indizenz für heute
* **Bundesland:** 
  * täglich neue Fälle für X Meldetage
  * indizenz für heute
* **Bund:** 
  * täglich neue Fälle  für X Meldetage

D.h 7Tage-Inzidenz für vorhergehende Tage müsste Berechnet werden.

**Comment by TheSpirit** [comment]
wenn ich das in tzschies Version richtig im Code gesehen habe, berechnet er auch den 7-Tage-Inzidenz Wert selber

**Comment by rphl** [comment]
Endlich dazu gekommen. Morgen stelle ich mal das Update online.

**Comment by TheSpirit** [comment]
kann man im breiten widget nicht auch 28 tage anzeigen lassen für den graph? fände das einen "schöneren" wert, da es dann immer ca. 1 monat ist. Hab in der config schon von 21 auf 28 gestellt, jedoch zeigt der graph weiterhin nur 21 tage an.
Danke für die super arbeit

**Comment by rphl** [comment]
Gerne eine PR bzw. Ticket mit Vorschlag erstellen. Mache das erstmal zu, da das Cache Thema durch sein sollte. Falls nicht gerne aufmachen.
