### ISSUE TITLE
R-Faktor mit altem Wert

### ISSUE THREAD

**Issue by UweLoyal** [rphl/corona-widget#67]
R-Faktor
Letzter Stand 13.11. laut Link

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile

Link falsch, oder fehlende RKI Daten?

**Comment by rphl** [comment]
Es ist schon der Korrekte link. Die offizielle Quelle. Hier hatten die Zahlen immer einen "Verzug", gerade der 7Tage R. Dachte die haben wieder die Spalte geändert ist aber ok.

Steht aktuell auf 0,97, was auch im täglichen Situationsbericht steht. https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Nov_2020/2020-11-17-de.pdf?__blob=publicationFile

**Comment by UweLoyal** [comment]
Stand soll laut RKI 17.11. sein!
Woher stammt dann der Wert in den öffentlichen Medien?

**Comment by rphl** [comment]
Das muss du die Medien fragen... Ist das zufällig der 4 Tage R? Oder gibt es einen anderen?

**Comment by UweLoyal** [comment]
Wie bei meinem Arbeitgeber, alle hauen sich Zahlen um den Kopf und jeder macht sich seine eigenen!
;-)

**Comment by rphl** [comment]
Denke das hast sich geklärt? Mache mal hier zu. Sonst gerne wieder aufmachen
