### ISSUE TITLE
Diagrammauswertung fehlerhaft bei kreisfreien Städten und Landkreisen mit gleichem Namen

### ISSUE THREAD

**Issue by pille85** [rphl/corona-widget#7]
Bei der Auswertung der Fallzahlen der letzten 7 Tage gibt es ein Problem, sobald man versucht eine kreisfreie Stadt und einen Landkreis mit gleichem Namen auszuwerten. 
In meinem Fall handelt es sich um die Stadt und den Landkreis München. 
Vermutlich bedingt dadurch, dass die für die Auswertung benötigte json-Dateiein sich lediglich im Städte/Landkreisnamen unterscheidet, wird in meinem Beispiel für die Stadt und den Landkreis München nur eine dieser Dateien angelegt. Somit stimmen spätestens am zweiten Tag die Vergleichswerte für einen der beiden Bereiche nicht mehr.

Dieser Fehler müsste aber bei weitaus mehr Städten/Landkreisen auftreten. (München, Rosenheim, Landshut, Regensburg, Augsburg, Ansbach, Bamberg, Schweinfurt, Coburg, Osnabrück, usw.

**Comment by pille85** [comment]
Auf dieser Seite sieht man übrigens die Bezeichnungen:
http://www.arcgis.com/home/webmap/viewer.html?url=https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/RKI_Landkreisdaten/FeatureServer&source=sd

Unter "GEN" werden beide mit München bezeichnet.
Unter "BEZ" erfolgt die unterscheidung "Kreisfreie Stadt" und "Landkreis"

Das Problem tritt auch beim widget von @kevinkub auf.

**Comment by rphl** [comment]
Kannst du mal ein paar Widgetparameter Posten, mit denen ich es checken kann?

**Comment by youmakemyday** [comment]
Kann den Bug bestätigen:
0,47.85,12.11,Rosenheim;1,47.77,12.07,LK Rosenheim

**Comment by rphl** [comment]
Danke für die Info. Man könnte hier die IBZ an den JSON Namen hängen:

**BEZ + IBZ**
```
Kreisfreie Stadt "40"
Landkreis "43"
Stadtkreis "41"
Kreis "42"
Bezirk "-"
```

Wäre dann:
```
covid19rosenheim_43.json
covid19rosenheim_40.json
```

Finde aber generell die Verwendung des Namens in der JSON nicht optimal.

Evtl. könnte ich das direkt mit Ändern und eine ID verwenden: Hier scheint **`RS`** die eindeutige Bezeichnung zu sein
Also Also anstatt: 

```
covid19rosenheim_43.json  >> covid19_09187.json
covid19rosenheim_40.json  >> covid19_09187.json
covid19mühlheim an der ruhr_43.json  >> covid19_01235.json
covid19rhein-kreis Neuss_40.json  >> covid19_02345.json
```

**Comment by youmakemyday** [comment]
jepp, die ID ist ja eindeutig, dann sollte es klappen. An dieser Stelle ganz dickes Dankeschön für deine tolle Arbeit.

**Comment by youmakemyday** [comment]
Hab noch ne Frage. Seit dem du auf das Repo umgestellt hast, kann das Widget keine Daten mehr abrufen. Die älteren Versionen im gist funktionieren normal. Ich markiere den kompletten Inhalt (RAW) in Safari und füge dann das Skript per C&P in Scriptable ein. Bisher lief das problemlos. Sobald ich eine der älteren Versionen nehme, gehts auch normal. Kannst das bei Gelegenheit nochmal verifizieren? Es ist hierbei auch egal ob Standortdaten fix hinterlegt sind oder angerufen werden. Motivation per Kaffee ist unterwegs ;)

**Comment by pille85** [comment]
Hier wären noch meine Beispielparameter:

0,48.06,11.61,München Land;1,48.13,11.57,München

Und wie es @youmakemyday beschrieben hat, wechselt bei mir auch täglich der richtige Wert zwischen Landkreis und Stadt.

Auch von meiner Seite vielen Dank für die tolle Arbeit.

**Comment by rphl** [comment]
Habe mal eine Version hochgeladen. In der anstatt dem Namen die erwähnte ID verwendet wird.

Auch werden die alten Daten übernommen, damit keine Trends verloren gehen. 
Es wird also aus `covid19{STADTNAME}.json` > `coronawidget{ID}.json` 

Das Update ist im **Develop/Test Branch** online. Wäre super wenn Ihr es testen könntet: (JSONs zuvor sicher ;-))
https://github.com/rphl/corona-widget/blob/develop/incidence.js

Für das Beispiel mit Rosenheim / Rosenheim LK werden die Daten jetzt wie folgt, getrennt, gespeichert:
<img width="283" alt="Bildschirmfoto 2020-10-31 um 20 43 58" src="https://user-images.githubusercontent.com/97642/97788585-65293b00-1bba-11eb-8ea4-025491ea8824.png">

**Comment by youmakemyday** [comment]
Vielen Dank für das schnelle Update. Habe es getestet, hab aber hiermit das gleiche Problem wie dass das Widget keine Daten findet (Siege Comment).

**Comment by rphl** [comment]
Hast du iCloud aktiviert? 

Sonst müssten diese unter: Dateien (App) >> iCLoud Drive >> Scriptable >> *.json
zu finden sein.

Ansonsten check mal Dateien (App) >> "Auf meinen iPhone/iPad" >> Scriptable?

**Comment by youmakemyday** [comment]
Hallo. iCloud ist deaktiviert, unter Dateien taucht kein Scriptable Ordner auf. Notfalls warte ich ein paar Tage bis sich ein neuer Trend ergibt.

**Comment by pille85** [comment]
Bei mir hat's geklappt. 
Beide Dateien wurden erstellt.
Die Daten für den Landkreis wurden übernommen.

Danke für die schnelle Bearbeitung!!!

**Comment by rphl** [comment]
> Hallo. iCloud ist deaktiviert, unter Dateien taucht kein Scriptable Ordner auf. Notfalls warte ich ein paar Tage bis sich ein neuer Trend ergibt. Hab aber weiterhin das Problem, dass die Daten mit den neueren Versionen nicht mehr geladen werden können. Hab auch testweise komplett neue Koordinaten genommen und auch testweise ein anderes jungfräuliches iOS Device genommen.

Problem ist hier das kein iCloud verwendet wird, und somit die Ordner zum Zwischenspeichern nicht existieren. 
Habe jetzt einen Workaround drin, der auch auf dem Gerät zwischenspeichert. Die JSON werden jetzt direkt in Scriptable gespeichert (Nicht Sichtbar in "Dateien") 

Ob der Trend auch mit dieser "lokalen" version geht, kann ich nicht garantieren. Gerne berichten... 

Ich mache das ticket erstmal zu, da das Problem mit "kreisfreien Städten und Landkreisen mit gleichem Namen" behoben ist.

**Comment by youmakemyday** [comment]
N'Abend, die letzte Version mit dem fix für den filemanager läuft jetzt auch bei mir. Vielen Dank für deine Mühen. Das Widget ist toll geworden, lediglich die Balken nach unten sind sehr gewöhnungsbedürftig ;)
