### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#72]
1) Optik: Könntest Du im Medium -Widget den Hintergrund für die Felder BL und D auch wie im kleinen Widget leicht grau machen.....

2) Inzidenz: ...ich habe auch das Problem mit der abweichenden Inzidenz in Nürnberg... (Parameter: "0,49.38,11.35,NÜRNBERG LAND;1,49.44,11.08)

Danke und VG

**Comment by STJIKA** [comment]
![IMG_C5FACE84156D-1](https://user-images.githubusercontent.com/8932465/100214921-b950e200-2f10-11eb-8d42-5aae3fa0747e.jpeg)

...das helle Grau für alle "Felder/HIntergründe" fände ich optisch besser und leichter erkennbar/erfassbar fürs Auge....

**Comment by rphl** [comment]
1. Sollten eigentlich auch Grau sein 🤔 Schaue ich später mal.
2. Wegen der Inzidenz siehe #71.

Sehe beim medium Widget fehlen die Hintergründe für die BL/D Daten, wie im SmallWidget. Das isst es nämlich so.

**Comment by rphl** [comment]
Sollte gefixed sein.

**Comment by STJIKA** [comment]
...sieht bei mir immer noch so aus.....zwar ein kleines bisschen heller aber immer noch kaum erkennbar.......

....etwas hellere "4 Felder" so wie das 1. Feld (bei mir "NÜRNBERG LAND" wär schöner und besser zu erkennen.... finde ich.....
![IMG_90E21ECE1BDB-1](https://user-images.githubusercontent.com/8932465/100312085-962a3f00-2fb1-11eb-8519-3943c576bd3a.jpeg)

**Comment by STJIKA** [comment]
> ...sieht bei mir immer noch so aus.....zwar ein kleines bisschen heller aber immer noch kaum erkennbar.......
> 
> ....etwas hellere "4 Felder" so wie das 1. Feld (bei mir "NÜRNBERG LAND" wär schöner und besser zu erkennen.... finde ich.....
> ![IMG_90E21ECE1BDB-1](https://user-images.githubusercontent.com/8932465/100312085-962a3f00-2fb1-11eb-8519-3943c576bd3a.jpeg)

....oder kann ich das selbst bei mir umstellen ...ohne größer in den Code einzugreifen...????
