### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#73]
..bei  den Parametern: "0,49.0134,12.1016;1,51.51,7.465"bekomme ich siehe Bild als Fehlermeldung.......????
![IMG_B12A6028A133-1](https://user-images.githubusercontent.com/8932465/100213624-22cff100-2f0f-11eb-8244-668e56ab3a5d.jpeg)

**Comment by rphl** [comment]
Danke für den report. War ein Problem wenn zwei unterschiedliche Bundesländer angezeigt werden. Ist gefixed.
