### ISSUE TITLE
Aufnahme der "Aktiven Fälle" möglich....?

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#74]
Wäre es evtl. möglich wie "tzschies" die "Aktiven Fälle" mit aufzunehmen....

![IMG_FD0A748C88A9-1](https://user-images.githubusercontent.com/8932465/100222458-667c2800-2f1a-11eb-8789-5675c8f87123.jpeg)

**Comment by rphl** [comment]
Erstmal nicht auf der meiner Todo. Gerne PR. Wenn es passt dann kann ich es mergen.
