### ISSUE TITLE
Region bei Small Widget ignoriert

### ISSUE THREAD

**Issue by steilerDev** [rphl/corona-widget#75]
Hallo! Super Widget, ich finde es super!

Ich habe das Problem bereits identifiziert, aber das fixen ist nur eine Zeile, deshalb kein Pull-Request.

**Problem:** Bei einem kleinen Widget wird die Region immer als 'KS' angezeigt.
**Ursache:** [Zeile 222 hat den IBZ Wert fest auf '40' stehen](https://github.com/rphl/corona-widget/blob/e6cf258980b02254a8d44b23ba985ae1908050a6/incidence.js#L222):  ```UIComp.areaIcon(bb3, 40)```
**Lösung:**: Und hier kenn ich mich mit Scriptable nicht gut genug aus. Für mich funktioniert es wenn ich auf die IBZ des Cache 0 zugreife: ```UIComp.areaIcon(bb3, ENV.cache[0].meta.IBZ)```

Ich hoffe das hilft dir!

**Comment by rphl** [comment]
Danke für die Info/Fix. Das sind wohl noch ein zwei Dinge durchgerutscht. ist gefixed
