### ISSUE TITLE
Andere Daten im Chart anzeigen?

### ISSUE THREAD

**Issue by TheSpirit** [rphl/corona-widget#76]
aktuell zeigt der chart ja die neuen fälle an. dies ist aber keine anzeige für mich, wie sich die pandemie bei mir im landkreis entwickelt. ich würde im chart einfach gleich die inzidenz anzeigen. der wert der neuen fälle sagt ja nix über das geschehen aus. wenn dann müsste man meiner meinung nach die differenz zwischen neuen und genesenen fällen im chart anzeigen. denn wenn mal länger keine neuen fälle da sind zeigt der graph dann ja immer 0 an. das sagt mir dann aber nix über das geschehen. kann ja sein, das keine neuen fälle dazu kommen, aber auch keiner gesund wird. oder ob eben jeden tag welche gesund werden, und keine neuen fälle dazu kommen. für die beiden fälle würde der chart die gleichen werte anzeigen, aber es hätte keine aussage, ob es "besser" wird oder eben nicht.

**Comment by rphl** [comment]
Aktuell kann man sich die Inzidenz oder neue Fälle im Chart anzeigen lassen.
