### ISSUE TITLE
Error on line 384:34: Expected value of type string but got value of type undefined.

### ISSUE THREAD

**Issue by w33zel** [rphl/corona-widget#77]
Ich bekomm eine Fehlermeldung seit dem Update. 

![image](https://user-images.githubusercontent.com/6563221/100250928-7f96d000-2f3e-11eb-8602-7aa0625dfb12.jpeg)

**Comment by rphl** [comment]
Es wäre gut zu wissen was für WidgetParameter du nutzt bzw. grober dein Standort. Damit ich es reproduzieren kann.

**Comment by w33zel** [comment]
Ich hab das Script mit ScriptDude installiert und aus der scriptable direkt gestartet. 🤔

Die Parameter die ich in dem Widget habe (hab das alte wieder installiert) sind einmal das kleine mit:

0,52.396149,13.058540,Potsdam,14473

Und einmal das große mit:

0,52.396149,13.058540,Potsdam,14473;1,52.514560,13.498310,Work,10365

Habe das neue gerade noch mal installiert und bekomme jetzt:

![image](https://user-images.githubusercontent.com/6563221/100270165-f42a3880-2f57-11eb-9233-9ce23d6c92af.jpeg)

🤔

**Comment by rphl** [comment]
Eine Kleinigleit die mir schon auffällt. Es gibt keinen Cache-Paramteter mehr. Caching funktioniert jetzt auch ohne.

`0,52.396149,13.058540,Potsdam`
`0,52.396149,13.058540,Potsdam;1,52.514560,13.498310,Work`

Ich checke es mal...

**Comment by rphl** [comment]
Habe mal ein Update Online gestellt. Batte was mit Berlin zu tun. Ist der einzige Standort in der API der Bezirke hat.

**Comment by w33zel** [comment]
Super, funktioniert einwandfrei jetzt. Besten Dank, sieht schick aus. 👍
