### ISSUE TITLE
Chart verschoben

### ISSUE THREAD

**Issue by Skjall** [rphl/corona-widget#78]
![image](https://user-images.githubusercontent.com/13360352/100278105-96501d80-2f64-11eb-9d71-66bff76aa242.png)
Wenn ein Inzidenzwert < 100 ist, rutscht die statistik nach links.
Ggf. weil mit Komma länger.

**Comment by rphl** [comment]
Widgetparameter wären nice. Macht es mir etwas einfacher zum testen.

**Comment by Reini2512** [comment]
So zum Beispiel:

0,48.708406,9.147385; 1,47.842099,9.672237

**Comment by Skjall** [comment]
1,51.74791,10.290089

**Comment by rphl** [comment]
Sollte jetzt korrigiert sein. 

Es bleibt aber noch eine kleine Lücke rechts von Diagramm im kleinen Widget. Muss mir da was überlegen.

Evtl auch bei 2-Stelligen Zahlen auf die Nackomme zu verzichten... und diese erst bei < 10 anzuzeigen
