### ISSUE TITLE
...sorry...nochmal wegen dem Darkmode"....

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#79]
...sieht bei mir immer noch so aus.....zwar ein kleines bisschen heller aber immer noch kaum erkennbar.......

....etwas hellere "4 Felder" so wie das 1. Feld (bei mir "NÜRNBERG LAND" wär schöner und besser zu erkennen.... finde ich.....
![IMG_90E21ECE1BDB-1](https://user-images.githubusercontent.com/8932465/100312085-962a3f00-2fb1-11eb-8519-3943c576bd3a.jpeg)

_Originally posted by @STJIKA in https://github.com/rphl/corona-widget/issues/72#issuecomment-734085423_

**Comment by rphl** [comment]
Erstmal nicht auf der meiner Todo. Gerne PR. Wenn es passt dann kann ich es mergen.
