### ISSUE TITLE
Inzidenz wird abgeschnitten

### ISSUE THREAD

**Issue by Eeewald85** [rphl/corona-widget#8]
Nabend ;)

Hab mir gerade die neue Version vom genialen Script mit den Neuerungen reinkopiert. Aber leider wird jetzt der Inzidenzwert abgeschnitten:

![image](https://user-images.githubusercontent.com/73432625/97764327-83396180-1b0e-11eb-9276-360650f782ad.jpeg)

Zumindest bei mir auf dem iPhone 12 Pro. 

Hab ich etwas übersehen?

Viele Grüße

**Comment by rphl** [comment]
Hello, da hab ich was übersehen ;-) Habe mal eine schnellen fix online gestellt.

**Comment by Eeewald85** [comment]
Wow, echt schnelle Reaktion ;-) danke!

Hatte in der Zwischenzeit in Zeile 214 "einfach" die Schriftgröße von 27 auf 25 geändert, dann wurde auch nichts mehr abgeschnitten 😅😉

**Comment by rphl** [comment]
Schliesse es mal als gefixed :-)
