### ISSUE TITLE
Abweichung von RKI

### ISSUE THREAD

**Issue by UweLoyal** [rphl/corona-widget#80]
Warum weichen die Werte des Main-Kinzig-Kreis ab, die des Wetteraukreises aber nicht?

![00AE631A-804D-4295-911F-85F65C201145](https://user-images.githubusercontent.com/5464553/100348556-5aaa6780-2fe7-11eb-8e33-ca6a8660ae0c.png)
![7DB23309-166E-4084-B441-3748C3598E42](https://user-images.githubusercontent.com/5464553/100348585-66962980-2fe7-11eb-8ecc-7462115cb3be.png)
![65C3D29B-442B-4A07-AB6F-235D408621E1](https://user-images.githubusercontent.com/5464553/100348593-68f88380-2fe7-11eb-8b8a-676d8f4dd6db.png)

Gruß
Uwe Loyal

**Comment by rphl** [comment]
Das Thema haben wir in #71. Es sieht so aus das manche Standorte (Kreise, Städte, etc) die täglichen neuen Fälle "anders" (ich bezeichne es erstmal so) bereitstellen. Mit Lücken etc.

Die Daten für die Fälle kommen immer "Live" aus der Api. z.B für meinen Kreis (Rhein-Kreis Neuss) sind die errechneten Inzidenz-Werte mit den "vordefinierten" aus der Api **identisch**.

Eine der Gründe sind eben Lücken. (z.B bei Nürnberg der Fall) Siehe wie gesagt #71

... Hatte im letzten Update eine Option eingeführt. Die vorübergehend die "vordefinierten" Inzidenzwert aus der Api verwenden soll. Dazu `useFallbackIncidence` muss auf `true` stehen


Wäre super wenn du die WidgetParameter posten könntest. Dann kann ich das mit deinen Daten checken.

**Comment by rphl** [comment]
Eben mal gecheckt: Die berechneten Werte passen bei mir für den MainKinzigKreis: **212** Auch ohne die aktivierte Option. 

@UweLoyal Sehe bei dir im Screenshot fehlen die "Lücken" im Diagram. Hast du auch die neuste Bersion? Siehe hier. MainKinzigKreis hat eine Lücke:

<img width="137" alt="Bildschirmfoto 2020-11-26 um 14 23 40" src="https://user-images.githubusercontent.com/97642/100356044-ff7e7200-2ff2-11eb-8736-13a515ac7986.png">

**Comment by UweLoyal** [comment]
Habe die neuste Version jetzt geladen.
Alte und neue Version zeigen unterschiedliche Werte.

LG
Uwe Loyal

[Image.jpeg]

[Image.jpeg]

Outlook<https://aka.ms/qtex0l> für iOS
________________________________
Von: Raphael <notifications@github.com>
Gesendet: Thursday, November 26, 2020 2:24:29 PM
An: rphl/corona-widget <corona-widget@noreply.github.com>
Cc: UweLoyal <Uwe.Loyal@Googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [rphl/corona-widget] Abweichung von RKI (#80)


Eben mal gecheckt: Die berechneten Werte passen bei mir für den MainKinzigKreis: 212 Auch ohne die aktivierte Option.

@UweLoyal<https://github.com/UweLoyal> Sehe bei dir im Screenshot fehlen die "Lücken" im Diagram. Hast du auch die neuste Bersion? Siehe hier. MainKinzigKreis hat eine Lücke:

[Bildschirmfoto 2020-11-26 um 14 23 40]<https://user-images.githubusercontent.com/97642/100356044-ff7e7200-2ff2-11eb-8736-13a515ac7986.png>

**Comment by rphl** [comment]
Bilder sind nicht zu sehen.

**Comment by UweLoyal** [comment]
[Image.jpeg][Image.jpeg]
Outlook<https://aka.ms/qtex0l> für iOS
________________________________
Von: Raphael <notifications@github.com>
Gesendet: Thursday, November 26, 2020 3:59:43 PM
An: rphl/corona-widget <corona-widget@noreply.github.com>
Cc: UweLoyal <Uwe.Loyal@Googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [rphl/corona-widget] Abweichung von RKI (#80)


Bilder sind nicht zu sehen.

**Comment by UweLoyal** [comment]
![744933B1-0FCA-4576-BD8D-3BE4F712B645](https://user-images.githubusercontent.com/5464553/100366478-280d6880-3001-11eb-8b39-1ca229d6f48d.png)
![F4F1DD58-D3CB-4DEA-B836-5B2E957DC55A](https://user-images.githubusercontent.com/5464553/100366485-2a6fc280-3001-11eb-8944-74646e00ff0e.png)

**Comment by rphl** [comment]
_Zum verständnis._ Die alte Version hatte MeldeLücken für neue Fälle mit dem nächsten Tag aufgefüllt. Deswegen erscheint da die Inzidenz höher. Die neue Version rechnet für MeldeLücken mit einer 0.

Mit der neuen Version stimmt es also auch bei dir. Ich mache das dann mal zu. Gerne wieder öffnen wenn noch Probleme sind...
