### ISSUE TITLE
Keine Veränderung der Farbe bei Inzidenzwert < 50 etc.

### ISSUE THREAD

**Issue by MeteoMartini** [rphl/corona-widget#82]
Möglicherweise lagen wir auch schon lange nicht mehr unter 50. Daher meine Frage, ob hier ein Bug vorliegt. ![image](https://user-images.githubusercontent.com/75040651/100414048-2089a600-3079-11eb-94ad-34157e71b985.jpeg)

**Comment by rphl** [comment]
Stimmt war leider ein Fehler. Sollte aber jetzt korrigiert sein. Ein Update ist online.

**Comment by MeteoMartini** [comment]
Gesehen! Es funktioniert! Vielen Dank! 👍🏼
