### ISSUE TITLE
Oben neben dem Logo steht n/v und der Balken mit dem Inzidenzwert ist nicht mittig

### ISSUE THREAD

**Issue by leon47331** [rphl/corona-widget#83]
![IMG_5913](https://user-images.githubusercontent.com/48152632/100555940-0f21e300-329f-11eb-9001-b0d2be1d5d45.PNG)

Ich nutze das iPhone 8

Oben neben dem Logo steht n/v und der Balken mit dem Inzidenzwert ist nicht mittig.

Vielen Dank schonmal für die Hilfe! :)

**Comment by rphl** [comment]
Tritt das Problem bei dir immer noch auf? Konnte es nicht wirklich reproduzieren.

<img width="126" alt="Bildschirmfoto 2020-12-02 um 20 38 54" src="https://user-images.githubusercontent.com/97642/100922653-7083c500-34de-11eb-9f18-eded0f7e796b.png">

**Comment by leon47331** [comment]
Hallo,
mittlerweile funktioniert alles ohne Probleme! :)
