### ISSUE TITLE
Darstellungsformen 

### ISSUE THREAD

**Issue by RosoV89** [rphl/corona-widget#84]
Schau mal hier: 

![E34EFA5D-76F5-4CAA-9E75-AA7FD9EB4404](https://user-images.githubusercontent.com/73339863/100595271-fba46580-32fa-11eb-88e9-140171fbf909.jpeg)

Was kann ich hier machen?

**Comment by rphl** [comment]
Hmm Strange. Selbst bei hohen werten sollte es passen 🤔

**Comment by RosoV89** [comment]
Inzwischen passt es wieder. Weiß jetzt nicht mehr, was für ein wert das war, aber vielleicht waren die Zahlen an der Zehner und Einser Position zu dick, bspw. ne 8

**Comment by rphl** [comment]
Habe es mal mit der vorzeige Stadt Passau 🙈 geprüft hier passt es auch. Hmm. 

![image](https://user-images.githubusercontent.com/97642/100922063-af654b00-34dd-11eb-920a-77844f4acc02.png)

Sonst updaten und gerne melden wenn es wieder auftritt
