### ISSUE TITLE
Formatierungs Fehler

### ISSUE THREAD

**Issue by 1rNidiD** [rphl/corona-widget#85]
Meine Parameter: 0,48.1351,11.5819,Stadt München;1,48.0782,11.6392, Neubiberg

![image](https://user-images.githubusercontent.com/47744797/100831159-6f628180-3465-11eb-865d-d65360bcf97a.jpeg)

Volle verfügbare Breite kann für den String "Stadt München" nicht genutzt werden.

**Comment by rphl** [comment]
Ein Update mit Optimierungen ist online. Auch etwas mehr Platz für den Namen... gerne testen. sonst wieder hier aufmachen.

**Comment by fireman130655** [comment]
Jetzt passt es. Super und danke!

**Comment by 1rNidiD** [comment]
Perfekt danke!!
