### ISSUE TITLE
Alle Tendenz-Pfeile seit letztem Update grün und nach unten zeigend...

### ISSUE THREAD

**Issue by medicus07** [rphl/corona-widget#86]

**Comment by medicus07** [comment]
Stimmt aber nicht... habe es mehrfach beobachtet. Inzidenz ist nach z.B Wochenende wieder gestiegen...

**Comment by firebowl** [comment]
![E1F72068-30A6-43F4-BFF0-04391847513C](https://user-images.githubusercontent.com/73579226/100911798-f9dfcb00-34cf-11eb-86de-832fe4b56dd8.jpeg)
Definitiv nicht grün

**Comment by rphl** [comment]
Bei mir auch nicht. Poste bitte deine WidgetParameter oder groben Standort. Dann könnte ich es prüfen
 ![image](https://user-images.githubusercontent.com/97642/100912368-a4f08480-34d0-11eb-857c-1a3c4ce13b49.jpeg)

**Comment by medicus07** [comment]
Hmmm... komisch.

0,49.459,8.170,Bad Dürkheim;1,49.346,8.150,Neustadt

<img width="363" alt="Bildschirmfoto 2020-12-02 um 19 51 43" src="https://user-images.githubusercontent.com/24975901/100917740-db7dcd80-34d7-11eb-8d1c-1debf9504242.png">

altes und neues Widget, selbe Parameter...

**Comment by rphl** [comment]
So wie es aussieht fallen bei dir die Werte oft... Was die vielen grünen Pfeile erklären würde.

Habe mal eine Option hinzugefügt, mit der man sich die Live berechneten Inzidenzen der letzten Tage lassen kann. Sieht für mich plausiblel aus.

```
2020-12-02 20:16:06: "calcIncidence" | "s0"
2020-12-02 20:16:06: "02.12.2020" | 106.27793564531812 << fällt
2020-12-02 20:16:06: "01.12.2020" | 115.32286633853668 << steigt
2020-12-02 20:16:06: "30.11.2020" | 107.78542409418787 << fällt
2020-12-02 20:16:06: "29.11.2020" | 119.09158746071108 << fällt
2020-12-02 20:16:06: "28.11.2020" | 121.35282013401572 << steigt
2020-12-02 20:16:06: "27.11.2020" | 119.09158746071108 << fällt
2020-12-02 20:16:06: "26.11.2020" | 128.89026237836453 << fällt
2020-12-02 20:16:06: "25.11.2020" | 136.42770462271332 << fällt
2020-12-02 20:16:06: "24.11.2020" | 143.21140264262726  << fällt
2020-12-02 20:16:06: "23.11.2020" | 145.4726353159319 << steigt
2020-12-02 20:16:06: "22.11.2020" | 134.92021617384356
....
```

Sehe das Alte Widget hat Lücken unten für heute/gestern. Somit fehlen Werte.

**Comment by medicus07** [comment]
Ok...
Auch gestern war der Pfeil grün, obwohl er am 1.12. hätte rot/steigend sein müssen.

**Comment by rphl** [comment]
Glaube das könnte auch an Zeitverzögerten Meldungen der Fälle liegen. Die werden ja immer Live aus der API gezogen. 

Sollten also für einen vorhergehenden Zeitraum die Fälle sich ändern (MeldeDatum beim Gesundheitsamt ist entscheidend), würde sich ja auch die Inzidenz ändern.

Ich werde mal auch die Fälle in console darstellen. Dann kann man es noch besser vergleichen.

**Comment by medicus07** [comment]
Same today... der eine Pfeil hätte rot sein müssen.

![IMG_3269](https://user-images.githubusercontent.com/24975901/100977250-03ede200-3541-11eb-8485-f4fddbe51a32.jpg)

**Comment by 1rNidiD** [comment]
Warum müssen die Pfeiler oder einer davon rot sein? Es handelt sich doch hier um den 7-Tages Wert und nicht um einen direkten Vergleich zum Vortag? 
Wenn die neuen Zahlen reinkommen mit zb +10 Fällen und deinem Landkreis, allerdings der Tag "gestern vor einer Woche" mit +20 raus fällt, dann ist es insgesamt ein Minus von 10 Fällen und somit grün. 

Also ich glaube das passt mit den Pfeilen oder?

**Comment by medicus07** [comment]
Das ist mir klar... aber die 109 sind ja der 7-Tageswert und gestern lag dieser bei 106, also heute höher... ich beziehe mich ja nicht auf die absoluten Zahlen.

**Comment by dennerforen** [comment]
Wenn die Daten live ausgewertet werden, macht ein Vergleich mit alten Zahlen keinen Sinn. Es ist doch ein dynamischer Vorgang mit nach Meldungen, Korrekturen und Nachmeldungen.

**Comment by 1rNidiD** [comment]
Ok jetzt habe ich mal bei mir geschaut, habe auch den selben Fehler..

Gestern:
![image](https://user-images.githubusercontent.com/47744797/101128905-e2ecc600-3600-11eb-8d0b-820ef5e569c7.jpeg)

Heute:
![image](https://user-images.githubusercontent.com/47744797/101128937-f1d37880-3600-11eb-8ec5-11c87ffb3ba4.jpeg)

Meine Parameter:
0,48.1351,11.5819,Stadt München;1,48.0782,11.6392, Neubiberg

Der Grüne Pfeil bei Stadt München, Bayern und Deutschland müsste eig rot sein..

**Comment by medicus07** [comment]
![IMG_3270](https://user-images.githubusercontent.com/24975901/101142448-e474b900-3615-11eb-905a-c6b75788d204.jpg)

Es müsste bei  mir heute auch alles rot sein...

**Comment by mmattersdorfer** [comment]
Im Landkreis Ludwigsburg (0,48.917605,9.223896) müsste der Pfeil heute auch rot sein. Er ist aber grün.

**Comment by tomacco81** [comment]
Bei mir ist es auch wieder so, dass der Trendpfeil für den LK nach unten zeigt, obwohl der Wert gestiegen ist (gestern 202, heute 212). Ich habe mir daraufhin das debug-Log näher angeschaut und festgestellt, dass der gestrige Wert im Log viel höher ist, als das Widget angezeigt hat (gestern 234, heute 212). Ich kapiere nicht warum der Wert rückwirkend nach oben korrigiert wurde. Die Historie wird doch vom Widget erstellt und nicht neu abgerufen, daher dürfte der Wert ja nicht rückwirkend verändert worden sein oder liege ich da falsch?
Gestern haben die Werte im Debug-Log jedenfalls noch gepasst...

**Comment by medicus07** [comment]
Bei mir sind alle Pfeile nur noch grün und das seit vielen Tagen, einen Wechsel hat es nicht mehr gegeben. Irgendwie scheinen im Hintergrund die Zahlen wirklich falsch zu sein.￼

**Comment by tomacco81** [comment]
Ich glaube das Problem gefunden zu haben.
Das Widget ruft zum einen den aktuellen Tageswert vom RKI ab. Außerdem werden in der neuen Widget-Version auch die Historiendaten vom RKI geladen.
Wenn das RKI nun die Historiendaten rückwirkend nach oben korrigiert, tritt das Problem mit dem Trendpfeil auf...
Ich habe bei mir eben verschiedene Stände der json Datei (Landkreis) verglichen und tatsächlich unterschiede in den Historienwerten festgestellt.
Das erklärt auch warum bei mir heute der Inzidenzwert für den Vortag höher und somit der Pfeil grün ist.

**Comment by rphl** [comment]
Das ist leider das Problem, was ich bereits erklärt habe. Je nachdem wieviel das RKI Nachträgt/Korrigiert ändert sich eben die Inzidenz (Was eben Korrekt ist).

Hier stellt sich die Frage wie man trotz des verspäteten Updates in einigen Regionen, man valide Trendpfeile anzeigen lassen kann. 
**Option1:**
Evtl. muss man hier gestern <> vorgestern vergleichen und auf den Tagesaktuellen Inzidenzwert verzichten. 
**Option2:**
Auf Wochebasis verlgleichen? Sowas wie Wochentag (Gestern) <> Wochentag (Gestern) Vorwoche.

**Comment by rphl** [comment]
@mmattersdorfer 

Das sind die Inzidenzwerte für deinen Standort (Kann via `debugIncidenceCalc` angezeigt werden). Grün ist wohl schon Richtig.. Auch wenn man gestern <> vorgestern vergleicht. Hmm.

```
2020-12-10 20:04:18: "10.12.2020" | 201 | 130.72422688445482
2020-12-10 20:04:18: "09.12.2020" | 102 | 145.5750857591264
2020-12-10 20:04:18: "08.12.2020" | 117 | 153.8255629117217
2020-12-10 20:04:18: "07.12.2020" | 83 | 160.0592567603493
2020-12-10 20:04:18: "06.12.2020" | 15 | 158.2258173931059
```

**Comment by tomacco81** [comment]
> Das ist leider das Problem, was ich bereits erklärt habe. Je nachdem wieviel das RKI Nachträgt/Korrigiert ändert sich eben die Inzidenz (Was eben Korrekt ist).

Du hast völlig recht, und die Berechnung und die Trendpfeile passen in dem Fall. Mir war nur nicht klar, dass das RKI rückwirkend teilweise so viel verändert. Bringt ja auch nix wenn sich durch das Nachtragen der Inzidenzwert der Vergangenheit verändert - die Zahlen wurden ja bereits so an die Bevölkerung kommuniziert und rückwirkend schaut sich das keiner mehr an.
Bestes Beispiel:
Das RKI kommuniziert am 08.12.2020 für den LK Rottweil einen Wert von 186,6. 
Und wenn man das ganze jetzt betrachtet lag der Wert eigentlich bei 234,5 🙈

**Comment by rphl** [comment]
@tomacco81 Hier sind die Regionen sehr Unterschiedlich... Finde es auch seeeeehr suboptimal. Die Berichte sind auch nur eine Momentaufnahme, und das Widget macht gerade irgendwie ein Spagat... 

Naja, habe deswegen erstmal den Trend auf Wochenbasis (Option3) umgebaut. Finde es aktuell so robuster, auch für die Regionen die viel Nachpflegen. Habe dementsprechend die README aktualsiert.

<img width="266" alt="Bildschirmfoto 2020-12-10 um 20 55 42" src="https://user-images.githubusercontent.com/97642/101831048-b7ecff80-3b35-11eb-9f23-5e13c0508347.png">

**Comment by tomacco81** [comment]
Ich denke das mit dem Wochendurchschnitt trifft es ganz gut. 
Super, dass du es so schnell anpassen konntest!
