### ISSUE TITLE
Medium widget

### ISSUE THREAD

**Issue by Thronis** [rphl/corona-widget#87]
Da fehlt was. 
Oder könnte es daran liegen, dass ich Medium gerade erst eingestellt habe?

**Comment by Thronis** [comment]
![image](https://user-images.githubusercontent.com/74420375/100923288-4252b500-34df-11eb-8d73-43da9bcec2bc.jpeg)

Sorry falsches foto eben...

**Comment by rphl** [comment]
Hmm. Sollte natürlich nicht abgeschnitten werden. Hast du mal die WidgetParameter auf die schnelle?

**Comment by Thronis** [comment]
Na logisch. 

0,53.5953,10.7531;1,53.5060,9.9747

**Comment by rphl** [comment]
Sollte jetzt passen.. hoffentlich 🙃 Ein Update ist online.

<img width="277" alt="Bildschirmfoto 2020-12-02 um 20 54 43" src="https://user-images.githubusercontent.com/97642/100924339-c6596c80-34e0-11eb-9d24-29d0fbe461d2.png">

**Comment by Thronis** [comment]
Jupp. Perfekt danke
