### ISSUE TITLE
Inzidenz Wert 

### ISSUE THREAD

**Issue by zefu-mm** [rphl/corona-widget#88]
![3747A6D5-E4ED-4DC9-B892-B3615DD6C6F7](https://user-images.githubusercontent.com/73780730/100975178-e3705880-353d-11eb-8b24-0fda9bfd2ba1.jpeg)

Wie können die Werte zwischen den beiden Versionen abweichen? Laut RKI ist der niedrigere Wert der alten Version richtig.

**Comment by MeteoMartini** [comment]
In der neuen Version ist defaultmäßig wieder "useFallbackIncidence: false". Mit "true" funktioniert es weiterhin. 
Leider ist dadurch dann für einige ein self-Update unmöglich, da er dann o.g. Wert überschreibt.

**Comment by rphl** [comment]
Wie schon mal in den anderen Tickets erwähnt, wird der Inzidenzwert Live berechnet (Es fliessen also direkt die neusten Fallzahlen in die Brechnung ein, die vom RKI in der API zur verfügung stehen ein)

Die option `useFallbackIncidence` nutzt hier nur den Einmallig berechneten Wert. Was jedoch schon nach dem ersten Api update obsolute (falsch) ist.

Hier wurden wohl bei dir in der Stadt, einige Fallzahlen auch für die vorhergehen Tage eingepflegt/korrigiert. Dies beeinflusst natürlich auch die Inzidenz.

Mit der option `debugIncidenceCalc` kannst du dir alle Berechneten Inzidenzwerte der Tage anschauen.

Ich schaue es mir mal an, aber vermute das es schon so ok ist, und es bei dir in der gegend an der MeldeArt liegt.

**Comment by zefu-mm** [comment]
Danke für eure Antworten :)

**Comment by rphl** [comment]
Habe mir eben die Zahlen angeschaut. Auch mit `disableLiveIncidence` passen die Zahlen. Denke es hatte was mit den Meldeverzögerungen zu tun. Die 72,6 ist auch nur solange gültige bis keine Aktualisierungen seitens RKI kommen. Weil die Fallzahlen sich auch über den Tag ändern, dieser Wert aber nie. Siehe auch: https://github.com/rphl/corona-widget#quelledatenbasis

<img width="142" alt="Bildschirmfoto 2020-12-10 um 22 33 48" src="https://user-images.githubusercontent.com/97642/101832839-62662200-3b38-11eb-80b9-61fe64f8dc02.png">

https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/#karte

Memmingen 120,18 (Vortag: 106,58)
