### ISSUE TITLE
Rückfrage zu den Koordinaten

### ISSUE THREAD

**Issue by djpln** [rphl/corona-widget#89]
Hi Zusammen,

ich bin leider kein "Pro" in Sachen Code. Deswegen entschuldigt die vielleicht blöde Frage. Aber in welcher Zeile füge ich den die Koordinaten ein für meinen SK?

Vielen Dank schonmal!

Liebe Grüße
Paul

**Comment by Thronis** [comment]
Guck dir mal die Anleitung an.
Das machst du im Widget Parameter.
