### ISSUE TITLE
Gesamtinzidenz falsch

### ISSUE THREAD

**Issue by medicus07** [rphl/corona-widget#9]
Der Trendbalken scheint ok, der Wert -25, stimmt definitiv nicht:

![image](https://user-images.githubusercontent.com/24975901/97771619-bdbaf280-1b3e-11eb-91e3-486056d38065.jpeg)

**Comment by TheSpirit** [comment]
Hab hier auch die 25 rechts oben stehen

**Comment by TheSpirit** [comment]
Jetzt stimmt der Wert wieder. Wahl wohl ein Fehler in den Daten.

**Comment by rphl** [comment]
Die 25 wäre Wünschenswert, aber stimmt so nicht. Der Wert kommt direkt aus der API.
Ist also alles wieder fein? Falls ja gerne Ticket schliessen.

Ansonsten gerne melden wenn was ist. Ich mache das mal zu.
