### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by Rfiach** [rphl/corona-widget#90]
Seit heute Morgen erhalte ich beim Ausführen des Scripts eine Fehlermeldung und das Widget funktioniert nicht mehr:

2020-12-07 06:48:51: Error on line 773:49: TypeError: undefined is not a function

**Comment by Rfiach** [comment]
Update: habe nichts verändert, aber das Script funktioniert nun wieder. Vielleicht eine kurzzeitige Störung?

**Comment by bennoire** [comment]
Selber Fehler, allerdings "line 770:49".
Tritt nur auf bei der manuellen Standorteingaben.

**Comment by rphl** [comment]
Bitte die Widgetparameter / groben Standort posten. Dann könnte ich es mal checken.

**Comment by bennoire** [comment]
0,50,9.074
Mittlerweile zeigt er aber wieder korrekt an. Vielleicht ein Daten Import Problem von der API?

**Comment by rphl** [comment]
Ok Strange. Wahrscheinlich was mit der RKI API. 
Die Fehlermeldung ist in der Funktion zur Ermittlung der InzidenzLimits. evtl ist da was Schiefgelaufen.

Mache das mal hier erstmal zu. Wenn es nochmal auftritt gerne wieder aufmachen.
