### ISSUE TITLE
Tendenzpfeil für R-Wert 

### ISSUE THREAD

**Issue by jnhllTM4** [rphl/corona-widget#91]
Hallo,

vielen Dank für das tolle Widget. Wie wäre, wenn du dem R-Wert noch einen Tendenzpfeil spendieren würdest? Dann müsste man nicht immer selbst überlegen, ob der jetzt gestiegen oder gefallen ist im Vergleich zum Wert davor. 

Danke, jnhll

**Comment by rphl** [comment]
Aktuell ist es Platztechnsich schwierig weil schon so viele infos im Widget sind.
