### ISSUE TITLE
Standortdaten konnten nicht geladen werden. Kein Cache verfügbar.

### ISSUE THREAD

**Issue by ofb72** [rphl/corona-widget#92]
Guten Morgen,

Beim starten deines Scriptes bekomme ich oben genannte Fehlermeldung. Ich stehe gerade auf dem Schlauch. Was ist Falsch ?

Mit freundlichen Grüßen
Oliver

**Comment by rphl** [comment]
Hast du die neuste Version aus dem Repo hier in Verwendung? Poste bitte deine Widgetparameter / groben Standort daten, dann könnte ich es mal checken.

**Comment by tomacco81** [comment]
Heute Morgen hatte ich das Problem auch als ich ein zusätzliches Widget mit manuell hinterlegten Koordinaten erstellt hab. Eine Stunde später hat dann alles funktioniert ohne Veränderung der Einstellungen. Ich glaube da hatte der Server Schluckauf...

@ofb72 tritt das Problem bei dir immer noch auf?

**Comment by ofb72** [comment]
> Heute Morgen hatte ich das Problem auch als ich ein zusätzliches Widget mit manuell hinterlegten Koordinaten erstellt hab. Eine Stunde später hat dann alles funktioniert ohne Veränderung der Einstellungen. Ich glaube da hatte der Server Schluckauf...
> 
> @ofb72 tritt das Problem bei dir immer noch auf?

Hallo, 

Mit dem Update von vorm2 Stunden läuft alles super.

Mit freundlichen Grüßen
Oliver

**Comment by Endlessknight** [comment]
Der Fehler tritt seit heute bei mir auf. Habe die neuste Scriptversion nochmal kopiert. Selfupdate ist auf true, sonst wurde am Script nichts verändert

**Comment by rphl** [comment]
@Endlessknight Hast du Widgetparameter gesetzt? Grober Standort? Mal testweise die neuste version https://raw.githubusercontent.com/rphl/corona-widget/master/incidence.js als neues Skript anlegen?

**Comment by Endlessknight** [comment]
Ich habe das Skript auch schon neu angelegt und nur Selfupdate auf true gesetzt. sonst habe ich nix verändert oder hinzugefügt

**Comment by rphl** [comment]
Kannst du mal bitte deinen Groben Standort nennen? Sonst kann ich es nicht reproduzieren.

**Comment by Endlessknight** [comment]
Grob...Köln^^

**Comment by xerxes87** [comment]
Das gleiche bei mir. Standort München.

**Comment by rphl** [comment]
Es scheint das aktuell für manche Orte das RKI Api Limit überschritten wird: Köln

<img width="835" alt="Bildschirmfoto 2021-04-15 um 12 18 40" src="https://user-images.githubusercontent.com/97642/114854128-c9486000-9de4-11eb-9715-491edd6967ff.png">

**Comment by xerxes87** [comment]
Bei mir geht es heute wieder.

**Comment by rphl** [comment]
Die Rki Api scheint wie erwartet wieder zu funktionieren...
