### ISSUE TITLE
Medium Widget keine Werte für den zweiten Standort

### ISSUE THREAD

**Issue by w33zel** [rphl/corona-widget#93]
![image](https://user-images.githubusercontent.com/6563221/101749194-c3a4db80-3acd-11eb-88c4-7a9027781c33.jpeg)

Hi, ich habe seit heute plötzlich keine Werte mehr für den zweiten Standort im Medium Widget. 

Hier die Parameter:
0,52.396149,13.058540,Potsdam;1,52.514560,13.498310,Work

**Comment by 1rNidiD** [comment]
Hey,
Ich glaube du verwendest garnicht die aktuelle Version? Kann das sein?

![image](https://user-images.githubusercontent.com/47744797/101753270-b76f4d00-3ad2-11eb-98e9-4a4c574e645a.jpeg)

Zieh dir nochmal den neuen Code, überschreib den alten damit und probiers nochmal aus. Bei mir kam des mit NaN (Not a Number) auch schon öfters. Wenn ich bei der Konfiguration einstelle, dass er beim "tippen auf das Widget" das Skript ausführen soll, dann wird des Widget neu geladen und danach sind alle Werte richtig hinterlegt.

Hoffe des hilft dir. Beste Grüße

**Comment by w33zel** [comment]
Habe gerade ein neues Script angelegt in scriptable und den Code rein kopiert. Leider das selbe Problem. 

Aber aktuell sollte das andere auch sein, im scriptdude werden keine Updates angezeigt. 🤔

Wenn ich das Script direkt in scriptable starte, werden mir Daten für den Standort hier angezeigt. 🤔

![image](https://user-images.githubusercontent.com/6563221/101755738-85abb580-3ad5-11eb-9c35-812febb1ff80.jpeg)

**Comment by dennerforen** [comment]
Bei mir geht es, evtl fehlen die Daten für den Standort oder sind fehlerhaft. Einfach warten.

**Comment by w33zel** [comment]
Ich nutze das Medium Widget. 

Habe jetzt mal das kleine für den aktuellen Standort und das Medium mit den Parametern wie oben neu erstellt. 

Für den aktuellen Standort im kleinen Widget werden Daten angezeigt, bei dem Medium nicht. 

Momentan ist mein aktueller Standort (kleines Widget) == dem zweiten Parametern zum Standort im Medium Widget. 🤔

![image](https://user-images.githubusercontent.com/6563221/101801124-506f8980-3b0e-11eb-8b10-158a1913ad1c.jpeg)

**Comment by rphl** [comment]
@w33zel Irgendwas stimmt mit den Koordinaten deines zweiten Standortes nicht. Habe den Punkte bei GoogleMaps nur um Halbe Strasse verschoben, und schon bekomme ich Daten für Berlin angezeigt:

`1,52.516783392847024,13.498846946642358`

**Comment by w33zel** [comment]
Ha, mit deinen Koordinatoren funktioniert es. 😅

Hatte die Koordinaten von latlong.org und bis gestern haben die auch funktioniert. 🤔 Vielleicht hat sich Berlin einfach verschoben. 😅

Danke dir. 👍
