### ISSUE TITLE
Seit gestern wird das Datum und die Zahlen nicht aktualisiert 

### ISSUE THREAD

**Issue by gunti-2020** [rphl/corona-widget#94]
Seit gestern wird das Datum und die Zahlen nicht aktualisiert 
Das neuste Repository habe ich schon rüber kopiert. 
![2A80B55D-79A9-4D3E-988A-FB08C6821267](https://user-images.githubusercontent.com/73196506/101783305-62473180-3afa-11eb-9332-bb67e24c9413.jpeg)

**Comment by rphl** [comment]
Das is Strange. Vor allen weil bei dir 2x NRW steht. Normalerweise werden Bundesländer nicht doppelt aufgeführt.

Mal Das Skript/JSON komplett entfernen und nochmal ausprobieren?

Bitte auch mal die Widgetparameter / groben Standort posten. Dann könnte ich es mal bei mir checken.

**Comment by gunti-2020** [comment]
1,51.92,8.39
Das sind die Parameter. 

Nachdem ich das Coding in ein anderes Script kopiert habe, geht es. Die Daten für NRW kommen trotzdem 2x

![1A5CDAC8-E139-4AFB-8C7E-0D1943A7DCFE](https://user-images.githubusercontent.com/73196506/101803927-587cf880-3b11-11eb-8aaf-fadec36765e9.jpeg)

**Comment by rphl** [comment]
Mit der letzten Version, und deinen Parametern sieht es bei mir ok aus. 

<img width="260" alt="Bildschirmfoto 2020-12-10 um 19 18 20" src="https://user-images.githubusercontent.com/97642/101813197-b3681d00-3b1c-11eb-94f1-c01ab637901d.png">

Kannst du bitte den CacheOrdener (CoronaWidgetNext) löschen (Wird beim Öffnen automatisch wieder angelegt)? Und nochmal testen?

**Comment by gunti-2020** [comment]
Vielen Dank für die tollen Tipps und Support. Jetzt sieht es wie bei Dir aus

Gruß aus Bielefeld 
Jens

**Comment by rphl** [comment]
Super. Ich mache das Ticket zu. Gerne wieder öffnen wenn probleme auftreten.
