### ISSUE TITLE
Text oder Pfeil Offset 

### ISSUE THREAD

**Issue by isotopeRal** [rphl/corona-widget#95]
Hallo Raphael.
Nochmal vielen Dank für das tolle Widget.
Was mir seit dem letzten Update auffällt ist, dass der Trendpfeil und/ oder die Inzidenz Vertikal nicht mittig angeordnet sind.
Kann es sein, dass es an meinem iPhone liegt (iOS 14.3 auf nem iPhone X), denn in deinem Screenshot sieht es sehr gut angeordnet.

**Comment by rphl** [comment]
Hallo, hatte die Pfeile etwas verkleinert und unten an der Zahl ausgerichtet, da ich etwas mehr Platz gebraucht habe. Generell ist aber aber so gewollt das die kleiner / unten ausgerichtet sind.

<img width="261" alt="Bildschirmfoto 2020-12-10 um 22 18 50" src="https://user-images.githubusercontent.com/97642/101885732-cb7e8180-3b9a-11eb-8484-e52a92fa6f80.png">

**Comment by isotopeRal** [comment]
Moin, 
Hier bei mir sieht es so aus, als ob die Trendpfeile wie gewollt angeordnet sind. 


Die Inzidenzen sind etwas off und weiter oben angeordnet.

Aber ist nur kosmetisch und nicht weiter tragisch...alles in allem super Widget.

Ralf

**Comment by rphl** [comment]
Werde mal die Abstände kontrollieren.
