### ISSUE TITLE
Optik......

### ISSUE THREAD

**Issue by STJIKA** [rphl/corona-widget#96]
...hätte noch ein paar optische Kleinigkeiten ...weiss nicht ob es machbar oder viel Aufwand wäre.....denke wäre aber optisch (noch) etwas „aufgeräumter“ und „logischer“ ....sorry....ich bin ein „Symmetriefan“ .....

...
![D8535585-F151-4F31-89A1-A97083A805F1](https://user-images.githubusercontent.com/8932465/101992412-4aff7400-3cb3-11eb-93c1-cf004061ecd8.jpeg)

**Comment by rphl** [comment]
Mit dem Scriptablelayout system ist das zentriere schwierig. Evtl. wenn ich einen größeren Umbau machen.

Über die Kleinigkeiten, wie die neuen Fälle zu verschieben, werde ich mal nachdenken.
