### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by kaile1503** [rphl/corona-widget#98]
Hallo, ich habe im "kleinen" Widget seit gestern die Fehlermeldung. ![image](https://user-images.githubusercontent.com/73854505/102327304-d1eb6f80-3f85-11eb-94e5-7536a022d979.jpeg)

**Comment by rphl** [comment]
Es gab heute wohl ein Problem mit dem RKI server. Siehe auch #99 Was sich aber wohl bereits gelöst hat.

Am besten immer die WidgetParameter / groben Standort posten. Sonst kann ich es schwer prüfen.
