### ISSUE TITLE
RKI API nicht erreichbar

### ISSUE THREAD

**Issue by pickmylight** [rphl/corona-widget#99]
Seit heute (16.12.2020) scheint es ein neues Update gegeben zu haben:

Die Arcgis7 Seite ist zwar zu erreichen, aber man bekommt keine Daten zurück!

{"error":{"code":400,"message":"Invalid URL","details":["Invalid URL"]}}

Ich habe aktuell noch keinen Workaround gefunden. Arbeite aber gerade an einer Lösung.

Getestet mit mehreren randomisierten Standorten.
![IMG_E2F88BA3F08D-1](https://user-images.githubusercontent.com/48281381/102329966-4673dd80-3f89-11eb-9f3e-855d1e8f0652.jpeg)

**Comment by shendralar** [comment]
Ich hab das Widget 3 mal auf dem Homescreen. Zwei mal mit festen Koordinaten (Memmingen und LK Unterallgäu) diese zeigen beide die Werte von Memmingen an. Und eines habe ich mit den aktuellen Koordinaten, da wird nur eine Fehlermeldung angezeigt.

**Comment by pickmylight** [comment]
Genau da liegt auch das Problem. Memmingen ist bei dir noch im Cache. 

EDIT:
Problem hat sich mittlerweile gelöst. Server ist wieder erreichbar.
